### ISSUE TITLE
Fix formatting issues in about_Comparison_Operators for 3.0,4.0 and 5.0 version of document

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#1000]
Current rendering of [3.0](https://msdn.microsoft.com/en-us/powershell/reference/3.0/microsoft.powershell.core/about/about_Comparison_Operators), [4.0](https://msdn.microsoft.com/en-us/powershell/reference/4.0/microsoft.powershell.core/about/about_Comparison_Operators) and [5.0](https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.core/about/about_Comparison_Operators) version of this document is difficult to read and understand.
Thanks to @doctordns via #953, 5.1 version of the document is fixed. /cc: @juanpablojofre

**Comment by kiazhi** [comment]
Fixed 3.0 about_Comparison_Operators.md Issue #1000 with #1047
Fixed 4.0 about_Comparison_Operators.md Issue #1000 with #1048
Fixed 5.0 about_Comparison_Operators.md Issue #1000 with #1049

**Comment by kiazhi** [comment]
Since we all agreed that we need more work in fixing all the versions of about_Comparison_Operators.md , I will suggest that we can close this issue and work on the new issue #1051 you have logged.

**Comment by HemantMahawar** [comment]
@kiazhi Yes, this issue was addressed with your #1047, #1048 and #1049
