### ISSUE TITLE
About_Splatting doesn't renders correctly due to incorrect markdown

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#1010]
Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Splatting
- [x] Impacts 5.0 document
https://msdn.microsoft.com/powershell/reference/5.0/Microsoft.PowerShell.Core/about/about_Splatting
- [x] Impacts 4.0 document
https://msdn.microsoft.com/powershell/reference/4.0/Microsoft.PowerShell.Core/about/about_Splatting
- [x] Impacts 3.0 document
https://msdn.microsoft.com/powershell/reference/3.0/Microsoft.PowerShell.Core/about/about_Splatting

**Comment by wsmelton** [comment]
The output on this [line](https://github.com/PowerShell/PowerShell-Docs/pull/1011/files#diff-82a6442a5bff21ad3bfa9e3a3bb1653aR190) is not correct.

It is not even close...the correct output

```powershell
PS C:> Test2 -a 1 -b 2 -c 3
1
2
3

Key Value
--- -----
b       2
c       3
```

**Comment by exchange12rocks** [comment]
@wsmelton Why do you think the output is not correct? My looks exactly like in the docs:
```
PS C:\> function Test1
>> {
>>     param($a, $b, $c)
>>
>>     $a
>>     $b
>>     $c
>> }
PS C:\>
PS C:\> function Test2
>> {
>>     param($a, $b, $c)
>>
>>     #Call the Test1 function with $a, $b, and $c.
>>     Test1 @PsBoundParameters
>>
>>     #Call the Test1 function with $b and $c, but not with $a
>>     $LimitedParameters = $PSBoundParameters
>>     $LimitedParameters.Remove("a") | Out-Null
>>     Test1 @LimitedParameters
>> }
PS C:\>
PS C:\> Test2 -a 1 -b 2 -c 3
1
2
3
2
3
PS C:\>
```

**Comment by wsmelton** [comment]
Ran that the first time and the output I provided is what I got on my machine. Ran it again though and it matches...oh well.

**Comment by DCtheGeek** [comment]
This appears to have been self-resolved and most of the changes @HemantMahawar started to make have been made since through other PRs.  Going to close this.  If it becomes an issue again, please open a new issue.
