### ISSUE TITLE
Question about line breaks

### ISSUE THREAD

**Issue by exchange12rocks** [PowerShell/PowerShell-Docs#1039]
IIRC, initially, all rows in PS help didn't exceed 80 characters. Now I see that several files have rows more than twice long. As I understand, that means that PS help is not trying to fit into a console window anymore, relying to a word-wrap ability of the console.

The question is: Should we remove those line-breaks, which restrict rows to 80 characters, (un-wrap) when updating help-topics?

**Comment by zjalexander** [comment]
ok, I looked into this and the answer is.... it's complicated.
@HemantMahawar to correct me if I'm wrong:
PowerShell 3: requires 80-character lines
PowerShell 4+: Does **not** require 80-character lines

PlatyPs: supposed to take care of the 80-character line work for us, but @joeyaiello is looking into that. 

Long term, yes, feel free to remove those line breaks. 
Short term, hold off i can dig into the current status of the 80char thing

**Comment by zjalexander** [comment]
@sdwheeler is looking into some other process improvements which will remove the need for 80char linebreaks manually inserted into about_ topics. This issue itself is low priority but it might get fixed incidentally along with some PS6 work :)

**Comment by sdwheeler** [comment]
We are switching to use Pandoc instead of PlatyPS for About topics. For now we need to wrap lines so that everything fits in 80 columns. The Style guide has been updated to talk about this. Longer term we need to update PowerShell's help system to use and render the Markdown source.
