### ISSUE TITLE
Install-Module -AllowClobber is not documented

### ISSUE THREAD

**Issue by davidreher** [PowerShell/PowerShell-Docs#1045]
Issue Details
-----------------
The -AllowClobber switch under `/reference/5.1/PowershellGet/Install-Module.md` is not documented, yet it is advised to use it, if (parts of) the module are already installed.

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
fixed

**Comment by DCtheGeek** [comment]
Ref: #2621
