### ISSUE TITLE
More fixes to formatting of about_Comparison_Operators

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#1051]
Issue Details
-----------------
Opening per @nzubair comments on #1047, #1048, and #1049 
 
- The operator names should be level 2 headers, e.g. ##-le insetad of bold **-le**. It conveys a better semantic structure of the document.
- The operator names should be lower-case throughout the entire document. The beginning of the document and section headers are lowercase, but document still contains instances of title-cased operators. e.g. -NotMatch' instead of-notmatch`
- Convert the bitwise operators table to proper markdown table.
- Under the bitwise operators section, some examples are not properly highlighted as code, making it difficult to read them.

Version(s) of document impacted
------------------------------
- [x] Impacts [5.1 document](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_comparison_operators)
- [x] Impacts [5.0 document](https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.core/about/about_comparison_operators)
- [x] Impacts [4.0 document](https://msdn.microsoft.com/en-us/powershell/reference/4.0/microsoft.powershell.core/about/about_comparison_operators)
- [x] Impacts [3.0 document](https://msdn.microsoft.com/en-us/powershell/reference/3.0/microsoft.powershell.core/about/about_comparison_operators)

**Comment by kiazhi** [comment]
Fixing PowerShell\PowerShell-Docs Issue #1051 with #1053
Let me know if it looks fine because I cannot visualise if the bitwise operator markdown table that has included code syntax highlight will render properly within the cell.

**Comment by nzubair** [comment]
Left a detailed comment on the PR about it. I think that should work.

**Comment by kiazhi** [comment]
@nzubair Thank you for the PR.

**Comment by nzubair** [comment]
anytime.
