### ISSUE TITLE
Purge the plague of "-------------------------- EXAMPLE"

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1063]
This applies to all versions of the reference docs.

https://github.com/PowerShell/PowerShell-Docs/search?utf8=%E2%9C%93&q=%22--------------------------+EXAMPLE%22

This is not good Markdown and this gets rendered poorly by OPS.
![image](https://cloud.githubusercontent.com/assets/6953993/23191366/1481175c-f852-11e6-8e08-c3c7094d0ba9.png)

I'm going to do a global search + replace to fix this, unless there are any objections from @HemantMahawar , @juanpablojofre or @eslesar . 

Alternatively, we could consider regenerating the MD, but I'm not a fan of that approach and I suspect no one else is.

**Comment by zjalexander** [comment]
Going to close #980 since this is more specific and concrete and I forgot I opened that old one.

**Comment by nzubair** [comment]
Given the large number of files being touched, splitting the PRs for 3.0, 4.0, 5.0, and 5.1.
