### ISSUE TITLE
What are .psd1-help.xml files?

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#1067]
Filed here at the request of @JKeithB 

Appx and Applocker have psd1-help.xml files. What are these for? I don't think Get-Help gets them because no commands are defined in .psd1 files.

I thought they might be something for PS Gallery, but these aren't PS Gallery modules...

```
dir ($env:PSModulePath.split(';')) -Recurse -Include "*psd1-help.xml"

    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\AppLocker\en-US


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         7/1/2015   9:31 AM         116599 AppLocker.psd1-help.xml


    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Appx\en-US


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         7/1/2015   9:18 AM         123142 Appx.psd1-help.xml

```

**Comment by zjalexander** [comment]
@HemantMahawar @joeyaiello @juanpablojofre

**Comment by eslesar** [comment]
@juneb  This is not a naming convention known about by the PowerShell team. I have not gotten a response from the teams that are using it. I will re-visit this issue if and when I do.

**Comment by JKeithB** [comment]
@juneb, @eslesar Turns out this is help content supplied in the generic Windows xml-based-help format. See https://msdn.microsoft.com/en-us/library/aa730773(v=vs.71).aspx (old topic, but still valid). These teams were required to supply help in this structure to meet Windows requirements for their feature.

**Comment by jvierrajrv** [comment]
My files "Appx.psd1-help.xml" are all n MAML.  They are not in the old and defunct XML help format.  Perhaps pre-WMF5 versions were this way???
