### ISSUE TITLE
Get-ChildItem Notes are broken

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1075]
Issue Details
-----------------
about_providers should be an inline link
there is a misplaced * causing the list to not be bulleted properly

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document - also needs backticks around Get-PsProvider
- [x] Impacts 3.0 document - also needs backticks around Get-PsProvider

**Comment by zjalexander** [comment]
open question: how many other docs are affected in this way and is there a more systematic fix possible?

**Comment by juanpablojofre** [comment]
Thanks @kiazhi !!

Closing as fixed.
