### ISSUE TITLE
Missing " * " twice in about_CommonParameters Foreach-Object example

### ISSUE THREAD

**Issue by ITMSupportem** [PowerShell/PowerShell-Docs#1078]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by juanpablojofre** [comment]
Closing as resolved in #1103
