### ISSUE TITLE
Get started with Desired State Configuration (DSC) for Linux - additional documentation is needed

### ISSUE THREAD

**Issue by rkyttle** [PowerShell/PowerShell-Docs#1079]
The "Get started with Desired State Configuration (DSC) for Linux" page found at https://msdn.microsoft.com/en-us/powershell/dsc/lnxgettingstarted seems to make assumptions about the reader's understanding of Linux and could use some additional information.

Run the following command to install OMI on a CentOS 7 x64 system.
# sudo rpm -Uvh omiserver-1.0.8.ssl_100.rpm

Run the following command to install DSC on a CentOS 7 x64 system.
# sudo rpm -Uvh dsc-1.0.0-254.ssl_100.x64.rpm

The commands above will not work unless the rpm files have already been downloaded, but the article doesn't mention how or where to download those files from.  I understand someone with Linux experience may quickly understand what prereq steps are needed, but it would be nice if the documentation included this as well.

**Comment by eslesar** [comment]
@rkyttle Please feel free to re-open this if I am missing something, but the paragraph immediately preceding the command reads:

To install DSC, install the package that is appropriate for your Linux system (.rpm or .deb) and OpenSSL version (ssl_098 or ssl_100), and architecture (x64/x86). RPM packages are appropriate for CentOS, Red Hat Enterprise Linux, SUSE Linux Enterprise Server, and Oracle Linux. DEB packages are appropriate for Debian GNU/Linux and Ubuntu Server. The ssl_098 packages are appropriate for computers with OpenSSL 0.9.8 installed while the ssl_100 packages are appropriate for computers with OpenSSL 1.0 installed.
