### ISSUE TITLE
workflow topics are missing WorkflowCommonParameters

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1080]
Issue Details
-----------------
filed by @juneb [on uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/17999017-workflow-common-parameters). 
>The WorkflowCommonParameters entry is missing from help for workflows.
PowerShell workflows have both common parameters and workflow common parameters.
Get-Help help for workflows has an entry in the Parameters section for CommonParameters, but not for WorkflowCommonParameters. It needs both

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by HemantMahawar** [comment]
#1020 is also related to this

**Comment by bobbytreed** [comment]
This was resolved when other missing workflow topics were restored.
