### ISSUE TITLE
Get-AuthenticodeSignature is missing parameter descriptions and examples

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#1086]
For 5.1, Get-AuthenticodeSignature has Content and SourcePathOrExtension parameters. Content has no description; SourcePathOrExtension has a description, but it doesn't make sense. Neither of these parameters are represented in the examples. 

Hope this helps.

**Comment by kiazhi** [comment]
Agreed, the -Content and -SourcePathOrExtension parameter are not properly documented.

There is also another issue where there is description for -SourcePathOrExtension parameter in PowerShell 5.1 ([https://msdn.microsoft.com/en-sg/powershell/reference/5.1/microsoft.powershell.security/get-authenticodesignature#-sourcepathorextension]) but displayed as @{Text=} in PowerShell when issued with the command below.

`Get-Help Get-AuthenticodeSignature -Parameter SourcePathOrExtension`

<img width="631" alt="screen shot 2017-05-22 at 11 16 38 pm" src="https://cloud.githubusercontent.com/assets/13409063/26305916/5eb85210-3f45-11e7-93e6-b953af1a04bf.png">
