### ISSUE TITLE
WMF 5.1 missing compatibility with 1st party products

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1092]
https://twitter.com/no_identd/status/841613708463869956

>https://msdn.microsoft.com/en-us/powershell/wmf/5.0/productincompat missing this page for WMF 5.1. Please fix it. Please also list Exchange Console & Shell separately.

**Comment by zjalexander** [comment]
@JKeithB

**Comment by zjalexander** [comment]
addressed by #1093

**Comment by juanpablojofre** [comment]
Closed as fixed
