### ISSUE TITLE
Get-Content has incorrect, missing, and unformated content

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1101]
Issue Details
-----------------
via [Uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/18608338-the-description-attached-to-the-parameters-delimi#comments)

[Get-Content](https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.management/get-content)  

>The description attached to the parameters 
-Delimiter 
-Encoding 
-Raw 
-Stream 
-Wait 
(This parameter is not supported by any providers that are installed with Windows Powershell.) 
is both incorrect and useless.
It is incorrect because the parameters are supported by the FileSystem provider (at least).
It is useless because it gives no information about the reason for the existence of the parameter. Is it a deleted function for which the parameter name is retained for legacy scripts? Is it a planned future addition?
My suspicion is that it is a place holder description that was never updated. (As an aside, there are/were many help entries where the description for some parameters had been replaced by that for -UseCredential)
Additionally, where it is decided that a cmdlet should have multiple help entries if a it has different behaviour depending upon which provider is invoked then the general (non-provider specific) version should clearly indicate that fact (with appropriate links). So '-Delimiter' would be described thus:
-Delimiter 
(FileSystem provider, ...) 
Provider specific behaviour.
where 'FileSystem provider' is a link to 'Get-Content for FileSystem'. Indeed, if the behaviour is the same for all applicable providers then the behaviour could be described in the general help entry (instead of just 'Provider specific behaviour.').

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by PeteH32** [comment]
This part of the documentation if definitely incorrect. The FileSystem provider installs with Windows PowerShell, and it does support the "-Wait" parameter.

> "-Wait - This parameter is not supported by any providers that are installed with Windows PowerShell"

**Comment by zjalexander** [comment]
yeah, provider help in general needs some work. Related: https://github.com/PowerShell/platyPS/issues/245

**Comment by sdwheeler** [comment]
@SteveL-MSFT What is the purpose of the -Wait parameter for Get-Content.

**Comment by mklement0** [comment]
@sdwheeler:

`-Wait` is already documented in the [_filesystem-provider-specific topic_](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Providers/FileSystem-Provider/Get-Content-for-FileSystem.md):

> `-Wait`
> Waits for the cmdlet to get the content before returning the command prompt. While waiting, Get-Content checks the file once each second until you interrupt it, such as by pressing CTRL+C.
>
> Wait is a dynamic parameter that the FileSystem provider adds to the Get-Content cmdlet. This parameter works only in file system drives.

(As an aside: This description could stand improvement along the lines of:

> After outputting the file's existing lines, `-Wait` keeps the file open and outputs new lines as they are being appended to it. 
While waiting, Get-Content checks the file once each second until you interrupt it, such as by pressing CTRL+C. 
Waiting also ends if the file gets deleted, in which case a non-terminating error is reported.
)

How hard it is to discover _provider-specific_ help topics is also the subject of #2213.

**Comment by sdwheeler** [comment]
@mklement0 Yeah, the provider-specific help is a work-in-progress. Long story but we are working on it. The goal is to wrap all of that content into the provider-affected cmdlets and get rid of the provider-specific docs.

**Comment by joeyaiello** [comment]
This will be fixed by #1562 if I EVER get around to it.

**Comment by bobbytreed** [comment]
This is closed by #3191

Though, there are other intances of placeholder parameters (Credential) that say they are not supported by any provider.
