### ISSUE TITLE
Please add PowerShell supported version to cmdlet help

### ISSUE THREAD

**Issue by f0rt** [PowerShell/PowerShell-Docs#1105]
Team,

Please add to cmdlet help which PowerShell version it was released wtih. We have internal build system VMs with PS 3.0. Every time we're using a cmdlet we had to check if the cmdlet exist on PS 3.0. This is a pain because our local workstations are with PS 5.1.

Thanks,
Nedko

**Comment by zjalexander** [comment]
Also raised as a UserVoice item, crosslinking: https://windowsserver.uservoice.com/forums/301869/suggestions/19073182

**Comment by mklement0** [comment]
That would certainly be a very helpful complement to the existing practice of noting when a new _parameter_ was introduced.

**Comment by PolarBearGod** [comment]
Has there been any further update to this issue?

**Comment by joeyaiello** [comment]
We will be doing this for versions going forward, but this will not be done all up and backfilled for old versions. Sorry....

**Comment by kubilayelmas** [comment]
having this feature would be really useful. It's very time consuming and frustrating to find out that half of your cmdlets are not working in your script, on some older systems. Looking forward to have this feature. I'm sure that the get-command cmdlet can have a parameter to display that information.

**Comment by mklement0** [comment]
@kubilayelmas: 

Agreed. In the meantime, try [this](https://github.com/PowerShell/PowerShell-Docs/issues/2270#issuecomment-409003217) (which has limitations).

**Comment by alfredmyers** [comment]
Having to switch the version combo to find the version of PowerShell where a cmdlet was introduced is cumbersome.
At least, indicate what is the version of PowerShell a given cmdlet was introduced.
The folks over the .NET API Browser have resolved it adding an [Applies to](https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=netframework-4.7.2#applies-to) section where all versions of the .NET Framework a given type or member are supported are listed.
