### ISSUE TITLE
Find-Module -name: wildcard or not, which is it?

### ISSUE THREAD

**Issue by Bartolomeus-649** [PowerShell/PowerShell-Docs#1109]
-Name
Specifies the names of one or more modules to search for. **This parameter supports wildcard characters**. If wildcard characters are not specified, only modules that exactly match the specified names are returned. If no matches are found, and you have not used any wildcard characters, the command returns an error. If you use wildcard characters, but do not find matching results, no error is returned.

Type: String[]
Parameter Sets: (All)
Aliases: 

Required: False
Position: 0
Default value: None
Accept pipeline input: True (ByPropertyName)
**Accept wildcard characters: False**

**Comment by exchange12rocks** [comment]
```
Find-Module -Name 'ad*' | select Name

Name
----
AdministratorRole
ADtoO365
AdmxPolicy
ADPolicyAudit
ADGrouper
AddCustomAvailabilityDB
ADConfiguration
Add-HostFileEntry
ADAudit
AdsiPS
ADMirror
add-multipleusers
ADCSTemplateParser
```

Apparently, it *does* support wildcards.
