### ISSUE TITLE
Module folder name should match with base module name

### ISSUE THREAD

**Issue by amitsara** [PowerShell/PowerShell-Docs#111]
Please remove ‘s’ from module folder name ‘MyDscResources’
Resource will not be discovered by DSC if user follows exactly what is written in the document.

$env: psmodulepath (folder)
    |- MyDscResources (folder)
        |- MyDscResource.psm1 
           MyDscResource.psd1

**Comment by amitsara** [comment]
This bug is about this document
https://github.com/PowerShell/PowerShell-Docs/blob/live/dsc/authoringResourceClass.md

**Comment by HemantMahawar** [comment]
@amitsara Addressed this via #112. Should go live shortly.

**Comment by HemantMahawar** [comment]
@amitsara  It is now live https://msdn.microsoft.com/en-us/powershell/dsc/authoringresourceclass
