### ISSUE TITLE
document XDG env variables for Unix

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell-Docs#1126]
PowerShell Core 6 will use these env vars if defined on Unix:

XDG_CONFIG_HOME, XDG_CACHE_HOME, and XDG_DATA_HOME

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SteveL-MSFT How will these environment variables be used? What document should this go in?

**Comment by SteveL-MSFT** [comment]
Typically, an end user does not need to do anything with these environment variables and they only apply to non-Windows.

XDG_CONFIG_HOME defaults to `~/.config/powershell`
XDG_DATA_HOME defaults to `~/.local/share/powershell`
XDG_CACHE_HOME defaults to `~/.cache/powershell`

XDG_CONFIG_HOME is path used to find the powershell profile.ps1 script if it exists
XDG_DATA_HOME is used for the user module path: `XDG_DATA_HOME/modules`
XDG_CACHE_HOME is used for cache files produced by PowerShell (like the module discovery cache)

The only time a user needs to define these if if they are using powershell from an account that doesn't have a home directory (like a service account).

**Comment by sdwheeler** [comment]
This is covered in https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60
