### ISSUE TITLE
PowerShell-Docs/dsc/builtInResource.md needs updating for Server 2016

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell-Docs#1141]
Issue Details
This document needs to have the new DSC Resources present in Server 2016 to the list of DSC resources, Additionally there needs to be sub pages for each of the new resources. 

As I see it the following resources need to be added:

GroupSet
ProcessSet
ServiceSet
SignatureValidation
WaitForAll
WaitForAny
WaitForSome
WindowsFeatureSet
WindowsOptionalFeature
WindowsOptionalFeatureSet
WindowsPackageCab

Version(s) of document impacted
------------------------------
- [X ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
this should be addressed by #1198
