### ISSUE TITLE
Document "MOFs encrypted by default"

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#115]
We've documented this new WMF 5.0 behavior [in the release notes](../blob/live/wmf/dsc_encryptedmof.md) but not yet [in the official DSC documentation](../blob/live/dsc/secureMOF.md). 

Maybe the latter becomes "securing a MOF in PowerShell 4.0" and we add another article to describe the 5.0 behavior?

**Comment by GoateePFE** [comment]
Also, we need to include a warning that if credential encryption is not used, then there are still plain text passwords on the build server and the pull server.  The pull server copy lives inside a ZIP file, but that is not a security boundary.  Build server copies of the MOF files must be deleted immediately to prevent further exposure if only relying on encrypted MOFs at the node.

**Comment by DonGill** [comment]
Not sure if this was completed. Capturing OneView TFS bug ([46613](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#_a=edit&id=46613&triage=true)).

**Comment by juanpablojofre** [comment]
Closed by VSTS #46613 status: Fixed and verified.
