### ISSUE TITLE
Server 2008 R2 Enterprise / Standard

### ISSUE THREAD

**Issue by martin0641** [PowerShell/PowerShell-Docs#1161]
When installing on a fresh and fully patched Windows Server 2008 R2 Enterprise or Standard this breaks the ability to run SYSPREP on the image.  It will fail during the "generalization" phase, and no amount of playing with the registry, permissions in the registry, has alleviated it.  My only method is to install this patch via MDT after imaging and know that going forwards, that image will never be able to run SYSPREP unless the issue is addressable via a patch or configuration change.

I tried 3 times using ESXi 6.5 and doing snapshots, I was able to SYSPREP at every step until running the powershell script on top of the default Powershell 2.x that came on the system.  

I did not try removing Powershell 2.x first.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

**Comment by ArieHein** [comment]
martin, you should probably open this issue in the PowerShell repo, not the documentation.

Generally if you install any patches with MDT after imaging, there's no need anymore to use sysprep.
At least that's not what its meant for. You always keep an un-syspreped image to add anything to it at later time.

as for the specific issue, have you tried:
https://msdn.microsoft.com/en-us/powershell/wmf/5.0/limitation_overview

hope this helps slightly :)

**Comment by martin0641** [comment]
In this case, it was before the MDT in the initial WIM creation - not patching after a deployment.

After looking, it's listed under the 5.0 section of limitations - but it also effects 5.1 which is why I didn't see it.  It might not be a bad idea to link it under 5.1 also and put a mention of it under the install section where it's more available.  I really looked for hours and never came across that.

In any case, thank you - my imaging woes are over for now :)
