### ISSUE TITLE
Need About_Windows_PowerShell_5.1

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/PowerShell-Docs#1171]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

Can we get an updated about topic for 5.1? All I see now is
about_Windows_PowerShell_5.0 and I know things have changed. I suppose you could leave the 5.0 topic file and add a second one for 5.1. But I supposed I'd rather one topic file that would cover both 5 and 5.1.

**Comment by JKeithB** [comment]
The best version is the WMF 5.1 release notes, removing the setup info.
