### ISSUE TITLE
PowerShell using lower and uppercase letters

### ISSUE THREAD

**Issue by Raymo931** [PowerShell/PowerShell-Docs#1175]
I was wondering why in Power Shell  why some of the commands or Objects are in upper or lower case letters. I have just begun the coarse and this caught my eye. Can anyone tell me if there is a reason for it. I copied the page below as an example from the about_Aliases page

SEE ALSO

New-Alias

Get-Alias

set-alias

export-alias

import-alias

get-psprovider

get-psdrive

about_functions

about_profiles

about_providers

**Comment by zjalexander** [comment]
Proper style is to have these Pascal Cased, let me add this to the style guide.

**Comment by zjalexander** [comment]
The rest should be addressed by #950 so let's track it over there. @Raymo931 thanks for raising the issue
