### ISSUE TITLE
Missing dash in TITLE metadata

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1188]
**Originally reported by Chrissy LeMaire**:

I find it disconcerting that searching for PowerShell commands returns pages with titles that are missing the dash.
 
For example:
![bug1](https://cloud.githubusercontent.com/assets/6953993/25642811/01d1d912-2f51-11e7-8cb6-b21f6849c176.png)

 
 
The page itself has a proper title
 
 
![bug2](https://cloud.githubusercontent.com/assets/6953993/25642814/0564b41e-2f51-11e7-9eca-f84673dec791.png)

 
 
Can this be fixed? The reason it's an issue is because I initially scan over it. I assume others may too. My brain is trained to look for the dash, otherwise, it lumps the result in with ads or rando blog posts.
 
In the end, I end up having to fight my natural response that tells me to click on SS64.com. 
 
![bug3](https://cloud.githubusercontent.com/assets/6953993/25642819/0c035406-2f51-11e7-824b-9a33c18fc27b.png)

 ----
If you look at [the raw markdown](https://raw.githubusercontent.com/PowerShell/PowerShell-Docs/a0e9fc02c8433d80c98ea769db337ed7ec3935e8/reference/4.0/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md), you will see a bunch of tags, including:
`title:  Get AuthenticodeSignature`

That title tag is what we use to generate the page title, which is what search engines pick up, and it is missing the dash. 

So, not an infrastructure problem! Just a metadata problem that we need to fix. Now we need to see how many items are missing the dash in the title….

**Comment by juanpablojofre** [comment]
The other similar problem we're facing is the casing in the filenames.
We have put some effort in making sure cmdlets are documented using Pascal casing; and, at the same time, we made all reference filenames lowercase (forgetting the UX community, where names are case sensitive).
I'm working on finding and fixing all metadata titles that don't match the exact cmdlet name (with casing and dash).

**Comment by zjalexander** [comment]
@juanpablojofre your comments about casing are in reference to #1175, is that accurate?

**Comment by juanpablojofre** [comment]
It seems, this issue was part of the migration process.
Almost all topics have the same problem.
I have identified 1769 topics with this issue. 
I'm ready to fix; expect a large PR for you to review.

**Comment by juanpablojofre** [comment]
PR #1190 should fix this issue (#1188)

**Comment by zjalexander** [comment]
oops.... this impacts at LEAST psget as well. @juanpablojofre would you mind re-running your amazing script against the different directories? we should also keep an eye out for underscores in page title. 
https://msdn.microsoft.com/en-us/powershell/gallery/psget/module/psget_find-module
![image](https://cloud.githubusercontent.com/assets/6953993/26020016/d3e071ae-372e-11e7-9af5-f7fc0e757bc2.png)
![image](https://cloud.githubusercontent.com/assets/6953993/26020019/dd252ac0-372e-11e7-9901-4a8797aa24a8.png)

**Comment by juanpablojofre** [comment]
@zjalexander, @bmanikm 

I think we need define better our reference strategy for the Gallery.
I feel it is confusing for all PowerShell users to find duplicate content for PowerShell Get.
Some content exists as versioned content under PowerShell X.Y reference and other content exists under Gallery/PSGET.
What do you think about this, Zach, Manik?

**Comment by bmanikm** [comment]
@JKeithB please take a look at above concern. I agree with @juanpablojofre to unify the PowerShellGet content under single location.

**Comment by juanpablojofre** [comment]
Updating Title metadata tag as requested by @zjalexander

**Comment by juanpablojofre** [comment]
Fixed
