### ISSUE TITLE
There is a typo in all the Examples, one m to much

### ISSUE THREAD

**Issue by inghak** [PowerShell/PowerShell-Docs#1201]
Test-WSMman instead of Test-WSMan

**Comment by zjalexander** [comment]
https://github.com/PowerShell/PowerShell-Docs/search?utf8=%E2%9C%93&q=Test-WSMman&type= looks like this hit 5.0, 5.1 and 6.

**Comment by juanpablojofre** [comment]
Closing as fixed.
