### ISSUE TITLE
Typo in Script Resource Example 2 code

### ISSUE THREAD

**Issue by cmcapellan** [PowerShell/PowerShell-Docs#1207]
Example 2 code on [Script Resource](https://msdn.microsoft.com/en-us/powershell/dsc/scriptresource ) page has a small typo.

`return @{ 'Result' = "Version: $currentVersion" }`
should be 
`return @{ 'Version' = "$currentVersion" }` to work with later references in `$state`

**Comment by eslesar** [comment]
Thanks @lidopaglia! Closing this.
