### ISSUE TITLE
Incorrect Parameter Documentation for New-PSSession -RunAsAdministrator

### ISSUE THREAD

**Issue by comnam90** [PowerShell/PowerShell-Docs#1209]
Issue Details
-----------------
On the new PSsession Documentation the details for the `-RunAsAdministrator` parameter is a straight copy/paste from the `-AllowRedirection` parameter details and doesn't make any sense.
[Example]( https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md#-runasadministrator )

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
fixed
