### ISSUE TITLE
Missing documentation for publishing signed modules to the Gallery

### ISSUE THREAD

**Issue by mattifestation** [PowerShell/PowerShell-Docs#1210]
Issue Details
-----------------
The process for publishing a signed module to the PowerShell Gallery is not documented and should be. Module signing is an important way to validate that a module originated from the publisher. The PackageManagement module contains functionality to validate catalog and embedded Authenticode signatures so this process should be documented so that non-Microsoft contributors can reap the benefits of additional code validation.

Personally, I think catalog signing is the best approach to use and requires the following steps:
1) Generate a catalog file for your module using the New-FileCatalog cmdlet.
2) Name the catalog file the name of the module and move it into the module root directory.
3) Sign the catalog file using Set-Authenticode signature using an issued code signing certificate. Not a self-signed cert.
4) Publish to the gallery.

It would also be valuable to explain what signing gets you and what it doesn't. For example, it doesn't guarantee the following:
1) That the code is not malicious
2) The fact that it is signed should not serve as the basis for implicit trust 

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [X] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by JKeithB** [comment]
@mattifestation Please take a look at the description for code signing in https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md. Is it sufficient? If not, what should be expanded?

**Comment by mattifestation** [comment]
Hey @JKeithB. I did realize that was out there. Great resource! I think the Catalog Cmdlets reference could at least be a little more explicit about how to name catalog files, where to place them, and guidance on commercial versus self-signed certificates.

Additionally, I would remove the reference to "PowerShell can be constrained using the Execution Policy cmdlets to ensure use of signed scripts. This feature is frequently used in highly secure environments." Such a statement could lead people to believe that the execution policy is an actual prevention mechanism against attacks. The validation of the signature simply serves to validate the integrity of the module you're saving/installing. It should never serve to imply that it should be implicitly trusted. That's why Save-Module is there in the first place - to permit a code review to take place prior to trusting the module in your environment, right?

Thanks!
-Matt

**Comment by JKeithB** [comment]
@mattifestation - thanks for the feedback.
I modified the Publishing Guidelines (removed the highly secure comment) in a recent PR, you should see the update shortly. 
With that change I'm going to close this particular issue, because there's another issue noting that the [File Catalog](https://github.com/PowerShell/PowerShell-Docs/issues/1266) cmdlet docs are only stubs.
