### ISSUE TITLE
Get-Help about_Pipelines is missing a section for collection

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell-Docs#1219]
Issue Details
-----------------
Get-Help about_Pipelines is missing a section for collection in which it explains that when enumerating objecst to the pipleline we lose the the fact that an object is a collection of size one, e.g., 

following scenarios:
``` powershell
$o = @(1)
$o.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array


$o | % {$_.GetType()}

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType
```

This affects how the objects from the pipeline are passed to the next command, e.g.,

``` powershell
$o = @(1) 

$o | ConvertTo-Json
1

ConvertTo-Json -InputObject $o
[
  1
]


$o = @(1)
$o | Get-Member
Get-Member -InputObject $o

```

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
This is explained in the topic under the "One-At-A-Time Processing" heading.
