### ISSUE TITLE
fix WMF documentation for clarity

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1220]
Issue Details
-----------------

Several parts to this:
https://msdn.microsoft.com/en-us/powershell/wmf/5.1/compatibility needs to be better-surfaced
The WMF documentation needs to be better surfaced
We need to clarify the following in our documentation:

We ship WMI +WinRM +SIL +PowerShell               in Windows. 
We ship WMI +WinRM +SIL +PowerShell +Setup as WMF.  

When Win10 RTM released in Summer '15, it contained a version of PowerShell that was production ready. The WMI+WinRM+SIL+PowerShell code corresponded to WMF5.0 The WMF 5.0 preview contained the production-ready bits for WMI +WinRM +SIL +PowerShell, but the Setup & upgrade code was still in preview state, so the WMF 5.0 package shipped as a Preview. 

When WMF 5.0 RTM'd, we grabbed the version of PowerShell that shipped in Windows 1511 (November Update). 

Every release of Windows 10 rebuilds and changes the version number of PowerShell. There can be (and probably are) bug fixes in those versions. Even if there were NO changes to PowerShell, the build version would still be different, because it’s a later version of the Windows and .Net Framework components that PowerShell is built on so the version number must be updated.

PowerShell 5.1.* is compatible with PowerShell 5.1.* , regardless whether it ships in Windows or WMF. Similarly, 5.0.* is compatible with 5.0.*, regardless of ship vehicle. 

This is all a very long-winded and technical way of saying that Windows does not "contain the WMF". They share components, but the WMF is a specific package that includes setup bits. The WMF can be in "preview" but the version of PowerShell that ships in Windows, is included as part of Windows, and therefore is supported as a part of Windows. 

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by JKeithB** [comment]
This page and issue is causing significant confusion for customers and support.

**Comment by JKeithB** [comment]
Addressed in [PR 1950](https://github.com/PowerShell/PowerShell-Docs/pull/1950)
