### ISSUE TITLE
clarify metadata and fix author tags

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1227]
This impacts at least the WMF documents. If 'author' is an MSFT alias instead of a github alias, you will experience something undesirable: https://msdn.microsoft.com/powershell/wmf/5.1/release-notes has @JKeithB 's MSFT alias, and so doesn't pick up on his GitHub alias leading to incorrect information and avatar.  

| Metadata tag | Purpose
| --------| ------------ |
| author | Your github alias
| ms.author | Your MSFT alias. Can be a DL alias

I need to check the author tags and see who else might have impacted this. Then I need to add this to a contribution guide, so we can have this documented.

**Comment by zjalexander** [comment]
@sdwheeler has some proposals in a onenote. we are finalizing that and then we'll put it in the documentation for this repo.... somewhere...

**Comment by sdwheeler** [comment]
I am still working out some of the details about how and where to put the metadata (see Scope below). But this is the metadata we are implementing.

Definitions
* Tag – the metadata tag
* Scope? – where the metadata can be defined (in preferred order). File metadata always wins but we can set metadata values globally or at the folder level.
* Required? – indicates whether we require this in our content (note: not all are required by OPS)
* Values – a list of possible values
* Notes – extra information about usage

|Tag|Scope?|Required?|Values|Notes|
|---|---|---|---|---|
|ms.prod|folder, file|yes|powershell|Don't use both ms.prod and ms.service|
|ms.technology|folder, file|yes|developer, dsc, gallery, jea, powershell|This only applies when using ms.prod.|
|ms.service|global, folder, file|yes|azure-powershell, azure-stack|Don't use both ms.prod and ms.service.|
|ms.topic|file|yes|article, conceptual, get-started-article, reference|More values defined but these are the values we want to use|
|title|file|yes|Sentence-case text|Limit to ~ 60 characters|
|author|file, folder|yes|your github alias| |
|ms.author|file, folder|yes|your MSFT alias or a DL alias| |
|ms.date|file|yes|mm/dd/yyyy| |
|manager|global, folder|yes|MSFT manager alias| |
|ms.devlang|file|no|csharp, powershell, xml, mof, dotnet|More values defined|
|keywords|file|no|comma separated list|Keywords used in the topic for SEO optimization|
|ms.tgt_pltfrm|file|no|windows, macos, linux| |
|description|file|No?|Sentence-case text|Not required but best practice. Limit to < 160 characters|

**Comment by sdwheeler** [comment]
@zjalexander - I added my notes. I can work on wording for the contributor's guide if you like.

**Comment by sdwheeler** [comment]
I fixed all of the metadata.
