### ISSUE TITLE
style guide: formalize "Windows PowerShell" vs "PowerShell"

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1228]
from @joeyaiello:
> Should "Windows PowerShell" ALWAYS get replaced with "PowerShell", even on old docs? In many cases, "Windows PowerShell" is the correct term, as that's the only kind of PowerShell where that version shipped, but if we think about "PowerShell" the platform, then something could have been "introduced in PowerShell 3.0". 

The style guide should allow people to distinguish between using "Windows PowerShell" where it makes sense vs "PowerShell" which is the overall platform name. 

Feedback is welcome on this issue, I'm honestly not sure about the best way to handle it.

**Comment by pcgeek86** [comment]
I'd recommend using the "PowerShell Desktop Edition" or "PowerShell Core Edition" where necessary, to keep consistent with the product development. Referring to PowerShell 1.0 through 5.1 would imply Desktop Edition.
