### ISSUE TITLE
Missing Cmdlet Development Guidelines

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell-Docs#1231]
I can't seem to find all of the conceptual documentation about PowerShell, cmdlet design guidelines,  construction of formatting files, etc. that's documented here: https://msdn.microsoft.com/en-us/library/dd878268(v=vs.85).aspx

Is that documentation community editable, and if not, can we get that ingested into this repository?

Cheers,
Trevor Sullivan
Amazon Web Services (AWS)

**Comment by zjalexander** [comment]
It's not editable right now, and @eslesar  working on getting into this repo. It's taking a while since the conversion process from the old docs format to Markdown can be very, very painful.

thanks!

**Comment by eslesar** [comment]
This is ready to go, awaiting publication of the SDK reference so that links will resolve. Expected in June.

**Comment by bobbytreed** [comment]
@pcgeek86 Now that the SDK content has been migrated into docs.microsoft.com, is this the information you were looking for? https://docs.microsoft.com/en-us/powershell/developer/cmdlet/cmdlet-development-guidelines

Is anything missing?

**Comment by sdwheeler** [comment]
Closing - no response from submitter.
