### ISSUE TITLE
ConfigurationModeFrequencyMins and RefreshFrequencyMins multiplication

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell-Docs#1244]
Reading

Configuring the Local Configuration Manager
https://msdn.microsoft.com/en-us/PowerShell/DSC/metaConfig

especially the ConfigurationModeFrequencyMins and RefreshFrequencyMins
I was under the impression the multiplication was removed ages ago.

So which one is it ?

**Comment by DCtheGeek** [comment]
This page has long since been migrated to docs.microsoft.com and the language clarified.  To be specific, ConfigurationModeFrequencyMins and RefreshFrequencyMins have no requirement to be multiplications of each other.  Thanks!
