### ISSUE TITLE
Description of file formats needed in Parameters section of Export-Counter documentation

### ISSUE THREAD

**Issue by MiaRomero** [PowerShell/PowerShell-Docs#1245]
Issue Details
-----------------
Add description of file formats (binary performance log (.blg), comma-separated value (.csv), or tab-separated value (.tsv)) in Parameters, -FileFormat section of document.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
The acronyms are described at the top of the article. Documenting how to use performance logs is out of scope for this article.
