### ISSUE TITLE
about_history incorrect alias, spacing

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1256]
re: #1253 
Issue Details
-----------------
Fixed incorrect alias for Clear-History.
Also fixed up the spacing of the table.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.1 fixed by #1253

**Comment by kiazhi** [comment]
Fixed the Typo for 3.0, 4.0, 5.0 and 6.0.
Fixed the Formatting for 3.0, 4.0, 5.0, 5.1 and 6.0.

**Comment by juanpablojofre** [comment]
Thanks @kiazhi .

Closing as fixed.
