### ISSUE TITLE
Measure-command doesn't adhere to style. 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1259]
Issue Details
-----------------

see #1233:
>Change capitalization of headers/titles to sentence case
Change highlighting of cmdlet names to use backticks instead of double-asterisks
Format PowerShell code syntax using code highlighting
Correct unnumbered lists' indentation and bullets

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.1 fixed by #1233

**Comment by kiazhi** [comment]
Do we have anything else to fix for Measure-Command style?

**Comment by sdwheeler** [comment]
Fixed
