### ISSUE TITLE
about_requires -RunAsAdmin requires PS4

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1260]
Issue Details
-----------------

See #1230:
>Clarified -RunAsAdministrator requires PowerShell 4

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.1 fixed by #1230

**Comment by pauby** [comment]
Updated other versions of the document. Removed it from PS v3.

**Comment by zjalexander** [comment]
awesome, thanks! Submit it as a PR to our repo and I'll merge it in!

**Comment by juanpablojofre** [comment]
closed as fixed.
