### ISSUE TITLE
about_comment_based_help has .LINE instead of .LINK

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1261]
Issue Details
-----------------

See #1215 

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.1 fixed by #1215

**Comment by juanpablojofre** [comment]
closing as resolved
