### ISSUE TITLE
about_pipelines is totally busted. 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1262]
Issue Details
-----------------

first issue is ridiculous formatting as described in #950 
second issue is #1166 which addressed a 5.1 issue but not others

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by kiazhi** [comment]
Updated the about_pipelines.md formatting for 3.0, 4.0, 5.0 , 5.1, 6.0. I have contained the command lines into the line issue reported in #1166 should be resolved on all versions.
```PowerShell
$services = get-service
format-table -inputobject $services -property name, dependentservices
```
Let me know how it goes. Cheers.

**Comment by zjalexander** [comment]
thank you!
