### ISSUE TITLE
Invoke-RestMethod should conform to style 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1263]
Issue Details
-----------------

see #895 

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
fixed
