### ISSUE TITLE
FileCatalog Cmdlets are Missing Documentation

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell-Docs#1266]
Issue Details
-----------------
The follow documents are empty stubs:
PowerShell-Docs/reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md 
PowerShell-Docs/reference/5.1/Microsoft.PowerShell.Security/Test-FileCatalog.md 

Partial documentation could be extracted from the release notes here:
PowerShell-Docs/wmf/5.1/catalog-cmdlets.md 

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
Closing as a dupe of #652
