### ISSUE TITLE
./dsc/pullServer.md needs attention

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell-Docs#130]
The pull server creation example code is neither complete nor correct nor current. Customers need a working example.
https://github.com/PowerShell/PowerShell-Docs/blob/master/dsc/pullServer.md

**Comment by GoateePFE** [comment]
Specifically, the sample configuration provided for the pull server has multiple syntax and naming errors.  Simply pasting this sample into the ISE reveals the following:

•	Closing quote missing at the end of the DependsOn line
•	Yes. DSC resource module should be both xPSDesiredStateConfiguration and PSDesiredStateConfiguration 
•	The resource name should be xDSCWebService, not DSCService
•	The Name property should be EndpointName
•	The EnableFirewallException line should be completely removed
•	For good style the ‘=’ character of all resource propertites should be spaced to align vertically for easier reading

This is the struggle our customers are facing daily with the documentation. Beginners do not have enough knowledge to make these corrections.

**Comment by eslesar** [comment]
Addressed with #131
