### ISSUE TITLE
PR#1270 fixed typo in 5.1 'about_Execution_Policies', other versions pending

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1300]
Issue Details
-----------------
PR#1270 fixed typo in 5.1 'about_Execution_Policies', other versions pending
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
Contributor only fixed v5.1.

Fix applied:
-- Warns the user before running srcipts and configuration 

+- Warns the user before running scripts and configuration

**Comment by kiazhi** [comment]
Fixed the Typo and Formatting.

**Comment by juanpablojofre** [comment]
Thanks @kiazhi !!
Closing as fixed
