### ISSUE TITLE
PR#1304 fixed typo in 5.1 'about_Data_Sections', other versions pending

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1305]
@Hugo-KTM fixed formatting issues in **5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md**.

Other versions are in need of the same fixes.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document

- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by kiazhi** [comment]
Fixed the formatting for 3.0, 4.0, 5.0 and 6.0
Updated the formatting on 5.1 to keep all version consistent

**Comment by juanpablojofre** [comment]
Thanks @kiazi.

Closing as fixed.
