### ISSUE TITLE
cookbooks terminology

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShell-Docs#1333]
I just wanted to file an issue to evaluate the term "cookbook" used on this page.
https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/basic-cookbooks

The content of the page is GREAT, and clearly someone contributed a ton of work effort.  I'm only concerned that the PowerShell community is unfamiliar with the term "cookbook" as a reference to examples and that might lead to the content be less discoverable.  I understand other communities do use this term but I'm not sure whether that alone will lead the reader intuitively.

Feedback and discussion is welcome.  TY

**Comment by zjalexander** [comment]
Haven't had any user feedback on this through the docs site and it's been this way for a while. Plus we have published a few books with the title "PowerShell Cookbook" :)
