### ISSUE TITLE
Update 'FileSystem-Provider' to latest edit

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1345]
Issue Details
-----------------
In PR #1339, @yeremee updated 5.1 version of the 'FileSystem-Provider'.
This issue tracks the update of the remaining versions to the latest update.

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document

- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

**Comment by kiazhi** [comment]
Updated FileSystem-Provider.md for 3.0, 4.0, 5.0 and 6.0 to be consistent with 5.1
Fixed some other formatting and typo issue for 5.1

**Comment by bobbytreed** [comment]
This is closed by #3191
