### ISSUE TITLE
FileSystem-Provider.md not loading when selected in ToC

### ISSUE THREAD

**Issue by kiazhi** [PowerShell/PowerShell-Docs#1350]
Issue Details
-----------------
- Unable to select "Microsoft.PowerShell.Core > Provider > FileSystem-Provider" page on live site ToC

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by juanpablojofre** [comment]
Closing as fixed
