### ISSUE TITLE
Error in https://github.com/PowerShell/PowerShell-Docs/blob/live/dsc/pullServer.md

### ISSUE THREAD

**Issue by HSchwichtenberg** [PowerShell/PowerShell-Docs#136]
The command

New-SelfSignedCertificate -CertStoreLocation 'CERT:\LocalMachine\MY' -Subject 'CN=PSDSCPullServerCert'.

only runs on Windows 10 and Windows Server 2016!

On older OS there is no parameter "Subject"!

Error message:
New-SelfSignedCertificate : A parameter cannot be found that matches parameter name 'Subject'.

**Comment by eslesar** [comment]
Thank you! The command has been changed to use the DnsName parameter rather than Subject.
