### ISSUE TITLE
code blocks in reference content have different casing for powershell

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1368]
Having different casing for the language specification, in fenced code blocks, seems to have rendering problems.

**Comment by kiazhi** [comment]
Hi @juanpablojofre,

I found another 27 files that has ```PowerShell code tag instead of ```powershell code tag. Are you able to reopen this Issue #1368?

Below are the list of files:
- dsc/configDataCredentials.md
- gallery/psget/psgallery_status.md
- gallery/psget/repository/bootstrapping_nuget_proivder_and_exe.md
- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Core/About/about_Enum.md
- scripting/core-powershell/ise/How-to-Use-Profiles-in-WIndows-PowerShell-ISE.md
- scripting/core-powershell/ise/The-ISEAddOnToolCollection-Object.md
- scripting/core-powershell/ise/The-ISEEditor-Object.md
- wmf/5.0/class_base.md
- wmf/5.0/class_baseconstructor.md
- wmf/5.0/class_basemethod.md
- wmf/5.0/class_interface.md
- wmf/5.0/dsc_testconfiguration.md
- wmf/5.0/dsc_updateconfig.md
- wmf/5.0/feedback_archive.md
- wmf/5.0/feedback_formathex.md
- wmf/5.0/feedback_moduleversionranges.md
- wmf/5.0/feedback_nonnewline.md
- wmf/5.1/catalog-cmdlets.md
- wmf/5.1/DSC-improvements.md
- wmf/5.1/known-issues.md
- wmf/5.1/scenarios-features.md
