### ISSUE TITLE
WMF 5.1 relnotes needs to say .NET 4.5.2 or greater

### ISSUE THREAD

**Issue by JKeithB** [PowerShell/PowerShell-Docs#1369]
Issue Details
-----------------
The release notes currently read:
WMF 5.1 requires the .NET Framework 4.5.2. Installation will succeed, but key features will fail if .NET 4.5.2 is not installed. Instructions are available in the Install and Configure WMF 5.1 topic.

Needs to read 4.5.2 or greater

Version(s) of document impacted
------------------------------
- [ ] Impacts 5.1 document

**Comment by DCtheGeek** [comment]
This was completed with PR #1460.  Closing.
