### ISSUE TITLE
about_escape_characters should mention that escape character is ignored inside single quotes

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1370]
Issue Details
-----------------
The _about_escape_characters_ topic doesn't mention that escape characters are ignored inside single quote text.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
fixed
