### ISSUE TITLE
WindowsOptionalFeature doc gives wrong values for 'Ensure' property

### ISSUE THREAD

**Issue by david-in-perth** [PowerShell/PowerShell-Docs#1382]
The documentation for the DSC WindowsOptionalFeature resource says that 'Ensure' should be set to either 'Present' or 'Absent'.
However, running it on Windows 10 with `Ensure = "Present"` gives the following error:
> At least one of the values 'Present' is not supported or valid for property 'Ensure' on class 'WindowsOptionalFeature'. Please specify only supported values:
> Enable, Disable.

Running it with `Ensure = "Enable"` (contradicting the documentation) appears to be working as intended.

Windows version: 10.0 (Build 10240)

**Comment by eslesar** [comment]
@david-in-perth Thanks for catching this!
Addressed with #1389

**Comment by ArieHein** [comment]
This is a bug in the resource code, not the documentation then.
For every DSC resource, Ensure will only accept Present or Absent. This is the validation set of the parameters. I went over the code for the resource, and I think definitely something wrong in it if you managed to set a different value of the two. 

As you mentioned "..appears to be working as intended, I would suggest you try more variations and have a reproducible steps and then open an issue at the dsc repo on GitHub.

**Comment by eslesar** [comment]
@ArieHein In both WindowsOptionalFeature and WindowsOptionalFeature, Ensure is defined with "Enable" and "Disable" on the box, but with "Present" and "Absent" on GitHub.

This raises an issue of how we doc resources when there is a disparity, and perhaps about where resource docs should live altogether.

@joeyaiello @zjalexander @kwirkykat @Indhukrishna @grayzu  Could you weigh in on this?

**Comment by kwirkykat** [comment]
@eslesar 
There was a discussion in the DSC Resource Kit repo around where resource documentation should live: https://github.com/PowerShell/DscResources/issues/263

The conclusion was that the documentation should reside with the repository/resource module.
So I would say that PSDscResources should not be documented here.

However there is no other documentation for the PSDesiredStateConfiguration module.
PSDscResources (on GitHub) is considered the 'new home' of the in-box resources, but it only works on WMF 5.1 and above, and the documentation for PSDesiredStateConfiguration is still valuable for those that haven't updated their systems yet.

So I would say that the documentation here for PSDesiredStateConfiguration should be kept, but it should be made clear that this is for resources only in that module and not PSDscResources. There can be a link to the documentation for PSDscResources if they want to see documentation for the updated versions of the resources.

**Comment by ArieHein** [comment]
There is an Enable/Disable notion but that's the state the DISM Get-WindowsOptionalFeature returns which is what this DSC resource relys on. So I'm not sure what "is defined with "Enable" and "Disable" on the box" means.

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/aeee88345908b8f0a6aef516bf800e62845df382/DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1
lines 309-338 is the conversion function.

Is this code new and didnt exist in early versions ?
Perhaps OP is using an old version of PSDscResource ?

**Comment by david-in-perth** [comment]
For context:
* Initially, we were using the Chef [dsc_script][1] resource to run the WindowsFeature DSC resource.
* In order to support Windows 10 in addition to Windows Server 2012 R2, I changed our Chef recipes to use WindowsOptionalFeature in the dsc_script code. 
* I tried using WindowsOptionalFeatureSet, but it wasn't available. I think I tried using Import-Module PSDscResource, but that didn't work either.

Apologies for not giving these details in the OP.

[1]: https://docs.chef.io/resource_dsc_script.html

**Comment by zjalexander** [comment]
Oh jeez, yeah. Here are my opinions, which aren't binding and are open to further discussion:
1) We need an issue to track documentation of the PsDscResource module as it continues to change
2) I think we should maintain documentation for only the latest version of PsDscResource and include instructions on how to update to the latest version at the top of the inbox module resources. This decision has several consequences I need to think through with @Indhukrishna @kwirkykat and @mbreakey3. However, since we don't have breaking changes in PsDscResources, the documentation should be strictly additive.
3) Sounds like WindowsOptionalFeatureSet isn't well documented about where its present and not present either (iirc it shipped in WMF 5.1) 

I'm going to sync up with Eric and the others I mentioned in this thread offline and probably open a new issue with our suggestions. 

Cool?
