### ISSUE TITLE
How should we deal with code snippets inside of numbered lists? 

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#14]
Right now, putting a code snippet inside of a numbered list breaks the numbering. Potential options include:

* Scope listed instructions to end with code snippets (i.e. don't do that)
* Use HTML tags?
* Hardcode something like "Step 1" in the front of items. 

Currently occurring in (at least) `pullServer.md`.

**Comment by eslesar** [comment]
Resolved to hardcoding with step numbers.
