### ISSUE TITLE
Documentation for writing multiCLR modules

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell-Docs#1401]
I would like some documentation on how I, as a module author, should create my modules to ensure that they operate correctly both on CoreCLR and FullCLR.

Areas of interest:

* What limitations apply ("Target netstandard" or something more?).
* What packages do I need to reference to pull in the correct PowerShell APIs.
* What sort of files must be present in my module (do I need to do something special to mark it MultiCLR capable? Do I need to ship multiple versions of my assemblies?).
* How to publish such a module in a way that allows PowerShell to use it without issues.

**Comment by zjalexander** [comment]
@joeyaiello - tagging you because this is part of the PS6 plan we discussed.
