### ISSUE TITLE
Contributing.md suggests tagging new issues as "In Progress" but only PowerShell org members can label issues.

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/PowerShell-Docs#141]
In [Contributing.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/CONTRIBUTING.md) it is suggested that new issues are tagged with "In Progress":
* *Open a new issue tagged as "in progress" to tell others what you're working on*

However, only members of the organization that owns the repository can tag (label) issues. So, only members of the PowerShell org can tag (label) new issues or PR's. This suggestion should be clarified to prevent confusion.

Also, "tagged" should be changed to "labeled" to match what GitHub calls tags.

I didn't tag this issue as "In Progress", because I can't, but it is "In Progress". :smile:

**Comment by vors** [comment]
Fair point
