### ISSUE TITLE
Need about_PowerShellCore help topic

### ISSUE THREAD

**Issue by JKeithB** [PowerShell/PowerShell-Docs#1435]
Issue Details
-----------------
Multiple situations exist where users will try to understand what PowerShellCore is, and how it differs from PowerShell 5.1. Best way to provide that info is in an About_PowerShellCore help topic.

This is related to a PR for OneGet, here: https://github.com/OneGet/oneget/commit/d3aff70 

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document

**Comment by sdwheeler** [comment]
@zjalexander @joeyaiello Do we need to add an about_ topic in v6.x?

**Comment by joeyaiello** [comment]
Hmmm, we don't have an about_WindowsPowerShell. Would an about_PSEdition be too undiscoverable? @JKeithB: you could include it in your error message, at least.

**Comment by sdwheeler** [comment]
@joeyaiello @SteveL-MSFT What is your take on this request? What would be in this article that is not already in the release notes on the web?

**Comment by sdwheeler** [comment]
We are also working on how to move About_ topics into the conceptual TOC but still ship updateable help. 
This will reduce duplication in the conceptual space. This will also solve this problem, as we could ship the "What's New" and "Breaking Changes" articles as updateable help and fill this request.
