### ISSUE TITLE
Dsc Group Resource Documentation needs to explain syntax of member properties

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#145]
I got the following request from a customer.

> Hello,
> 
> I am attempting to use the built-in DSC Group Resource but I am finding that the documentation does not fully explain how to use the resource, and needs to be updated.
> 
> I am referring to the following page: https://msdn.microsoft.com/en-us/powershell/dsc/groupresource 

 https://github.com/PowerShell/PowerShell-Docs/blob/master/dsc/groupResource.md

 
> I would like to use the Group resource to define the desired list of members for the Administrators group on my server.  Unfortunately the documentation provides no syntax on how to define the values for Members, MembersToExclude or MembersToInclude.  It also took me a few minutes to understand the difference between Members and MembersToInclude, so I feel more detail could be added here on why you would use one over the other.  The documentation needs to show how to define a domain user, or a domain group, or a local user, or a local group and should show the proper syntax to use when defining multiple users and/or groups, as this would be a typical example.
> 
> I have brought up instances in the past where DSC documentation could be improved, and some feedback that I got from the content developers was agreement that it would make a lot of sense to ensure that example sections show syntax for how to use all of the available properties for a resource, but it doesn’t seem like much has changed yet on that front.  In the case of the Group Resource, the example is not really helpful as it shows how to use the resource to ensure that a group is absent, which is not really the best first example to be showing the power of this resource to our customers.
> 
> If I can help in any way to expand this documentation out further, please let me know as I would be happy to help! :) 
> 
> Thank you,
> 
> Ralph Kyttle
> Microsoft ...
>

**Comment by DonGill** [comment]
Not sure if this was resolved. Adding OneView TFS item ([46626](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=46626&fullScreen=false&_a=edit)).

**Comment by eslesar** [comment]
Addressed in #364
