### ISSUE TITLE
MSDN text contains wrong format

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell-Docs#1453]
On this web page https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_language_modes  see 'Allowed Types: ' section

Section Example Mode Result
https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_parsing

**Comment by sdwheeler** [comment]
These articles have been fixed.
