### ISSUE TITLE
Edit to About_Arrays

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1455]
Issue Details
-----------------
@jmorey4158 opened a PR to start fixing 'reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md'

LINE 470: The Line says "The Where method can be used to swiftly cast" but it should read "The ForEach method can be used to swiftly cast". That is the method in the example.

Documents for versions 6, 5.0, 4.0, and 3.0 need to be reviewed and fixed.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by zjalexander** [comment]
Fixed in 5.1
