### ISSUE TITLE
Build process is growing in time

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1459]
We need the build process to be smarter about what files it runs through PlatyPS as our builds are taking longer and longer to finish.

Is it possible to have AppVeyor only run necessary processing on files that have changed in the most recent pull?

cc @joeyaiello

**Comment by sdwheeler** [comment]
Closing this issue. Build times have been stable. We are in discussions with APEX Engineering about changes to the build pipeline.
