### ISSUE TITLE
Outdated "Installing" and "Requirements" docs

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#1539]
Both of the following documents should cover at least PowerShell 5.1:

https://docs.microsoft.com/en-us/powershell/scripting/installing-windows-powershell?view=powershell-6
https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell-system-requirements?view=powershell-6

As we can now target documentation for the specific PowerShell versions (in the upper left-hand side corner), it would be even better if every selection would actually load a document that covers installation and requirements for that specific version (instead of just one page that covers all versions as we have now).

**Comment by juanpablojofre** [comment]
@alexandair,
I'll add you to the reviewers of the Installing guide.
Coming soon.
