### ISSUE TITLE
add-content-for-filesystem , and all the other -for-filesystem links lead to 404

### ISSUE THREAD

**Issue by gabrielmccoll** [PowerShell/PowerShell-Docs#1544]
Issue Details
-----------------

On the POSH v6 Page, the links for add-content-for-filesystem and anything else ending in -for-filesystem, just go to dead links

Version(s) of document impacted
------------------------------
- [x ] Impacts 6 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ x] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
Nice catch. This is heavily related to #1548. The difference is that when a folder is nested two deep instead of just 1, the view breaks in the webview as well. We need to fix the build for this issue.

**Comment by zjalexander** [comment]
fixed
