### ISSUE TITLE
Installing Windows PowerShell is outdated

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1550]
The document is outdated.
Targeted specifically for version 3.0.
Needs to be updated and brought to current versions of PowerShell.

**Comment by alexandair** [comment]
I've already opened issue #1539 for outdated installation and requirements docs.

**Comment by juanpablojofre** [comment]
Thanks @alexandair!!

I'm closing this as duplicate of #1539.
I also have a branch: jpjofre-I1550; where I'm fixing this issue.
