### ISSUE TITLE
A help topic for a nonexistent cmdlet

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#1565]
https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/6/Microsoft.PowerShell.Core/Get-HashValueFromString.md

Cmdlet Get-HashValueFromString doesn't exist.

**Comment by juanpablojofre** [comment]
Also, removing '_Get-OSVersion_'; that doesn't exist either.

**Comment by alexandair** [comment]
Closing the issue. PR #1580 contains a fix.
