### ISSUE TITLE
PowerShellGet functions redirecting to a wrong page

### ISSUE THREAD

**Issue by matt9ucci** [PowerShell/PowerShell-Docs#1572]
All the following `Get-Help <function> -Online` commands redirect to the same page <https://technet.microsoft.com/library/cc732148.aspx>
```powershell
Get-Help Find-RoleCapability -Online
Get-Help Find-Script -Online
Get-Help Get-InstalledScript -Online
Get-Help Install-Script -Online
Get-Help New-ScriptFileInfo -Online
Get-Help Publish-Script -Online
Get-Help Save-Script -Online
Get-Help Test-ScriptFileInfo -Online
Get-Help Uninstall-Script -Online
Get-Help Update-ModuleManifest -Online
Get-Help Update-Script -Online
Get-Help Update-ScriptFileInfo -Online
```

These functions have "online version: \<url\>" metadata as follows:
* Find-RoleCapability <http://go.microsoft.com/fwlink/?LinkId=822321>
* Find-Script <http://go.microsoft.com/fwlink/?LinkId=822322>
* Get-InstalledScript <http://go.microsoft.com/fwlink/?LinkId=822324>
* Install-Script <http://go.microsoft.com/fwlink/?LinkId=822327>
* New-ScriptFileInfo <http://go.microsoft.com/fwlink/?LinkId=822329>
* Publish-Script <http://go.microsoft.com/fwlink/?LinkId=822331>
* Save-Script <http://go.microsoft.com/fwlink/?LinkId=822334>
* Test-ScriptFileInfo <http://go.microsoft.com/fwlink/?LinkId=822336>
* Uninstall-Script <http://go.microsoft.com/fwlink/?LinkId=822338>
* Update-ModuleManifest <http://go.microsoft.com/fwlink/?LinkId=822341>
* Update-Script <http://go.microsoft.com/fwlink/?LinkId=822342>
* Update-ScriptFileInfo <http://go.microsoft.com/fwlink/?LinkId=822343>

It seems that these urls are correct, but go.microsoft.com redirection settings are incorrect.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
Thanks for the report! We often use placeholders during development, seems like we never changed the fwlinks to point to the right place. This should be something I can do in our backend.

**Comment by zjalexander** [comment]
@matt9ucci You were hitting this on 5.1 and not 5.0, right?

**Comment by matt9ucci** [comment]
@zjalexander Yes, it's 5.1, not 5.0. `$PSVersionTable.PSVersion` is 5.1.15063.502

**Comment by zjalexander** [comment]
@TaraMeyer can you please take a look? I tried editing the fwlink and it did not go well for me :\

**Comment by TaraMeyer** [comment]
@zjalexander - all of the fwlinks have been updated to point the correct pages.  Please confirm on your end.

**Comment by TaraMeyer** [comment]
@zjalexander - have you had any success in testing the fix?

**Comment by zjalexander** [comment]
@TaraMeyer yup, all fixed! thanks so much! 
@matt9ucci thanks for reporting, please give a holler if you see it come back again
