### ISSUE TITLE
Remove repeated content at -NoNewLine from Add-Content

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#1577]
Issue Details
-----------------
@grantcarthew started the fix for repeated content in **Add-Content** #1571 

In the -NoNewLine section, in @grantcarthew words "_It looks like there was a copy paste from the -Credential parameter to the -NoNewLine. I have removed the duplicate content._"

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] Version 6 was fixed in #1571

**Comment by matt9ucci** [comment]
@sdwheeler This issue can be closed thanks to your PR #1846

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
