### ISSUE TITLE
Is Find-DscResource really part of DSC? 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1579]
Issue Details
-----------------
Find-DscResource returns 2 results on Docs.microsoft.com:
1. https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/5.0/PowershellGet/Find-DscResource.md
2. https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/5.0/PSDesiredStateConfiguration/Find-DscResource.md

However, when I run 
```powershell 
get-command find-dscresource
```

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Find-DscResource                                   1.0.0.1    PowerShellGet
```
Pretty sure it's not part of PsDesiredStateConfiguration, so I propose removing item (2) and all references to it from the repo. 
cc: @grayzu @juanpablojofre @eslesar @JKeithB 

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
Yup, definitely part of PSGet. Need to move the existing docs around.

**Comment by JKeithB** [comment]
Recommendation: It's probably good to have a reference in the DSC section, just point to the PSGet docs rather than duplicating them.

**Comment by sdwheeler** [comment]
@zjalexander @JKeithB - I am not sure what this issue is about. I don't see Find-DSCResource in the DSC docset. I only see it in the PowerShellGet docset. Is this still a valid issue?

**Comment by JKeithB** [comment]
Go ahead and remove any reference in DSC. It's causing confusion.

**Comment by sdwheeler** [comment]
@JKeithB - what do you mean by "reference in DSC"? Are you talking about the related links?

**Comment by JKeithB** [comment]
@sdwheeler please read the issue that was filed originally. Mark Gray's solution is needed.

**Comment by sdwheeler** [comment]
OK, I figured out what is needed here. Part of my confusion is that Find-DSCResource.md exists in reference\5.0\PSDesiredStateConfiguration but does not show up in the published web content for DSC. So I thought this was a non-issue. I will remove the file from reference\5.0\PSDesiredStateConfiguration.
