### ISSUE TITLE
A Syntax section for PowerShell 6 commands contains InformationAction and InformationVariable parameters

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#1585]
Issue Details
-----------------
InformationAction and InformationVariable parameters are common parameters and should not be visible in the Syntax section.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by raghav710** [comment]
Yes. And the formatting is also [wrong ](https://github.com/raghav710/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Out-File.md)(see the -InformationAction formatting impacting the -InformationVariable section) and there's a weird @{Text=}. Is that a placeholder?

**Comment by zjalexander** [comment]
We should file a PlatyPS bug on this as well.

**Comment by sdwheeler** [comment]
@zjalexander See issue https://github.com/PowerShell/platyPS/issues/55
