### ISSUE TITLE
No direct link to WMF documentation from any hub or TOC

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#1610]
When the PowerShell docs were migrated to docs.microsoft.com the structure of the Hub pages and TOCs changed. 

The new [Hub page](https://docs.microsoft.com/en-us/powershell/#pivot=main&panel=getstarted) has a card to "Download WMF" but no link to the reference docs for WMF. The [Features Hub](https://docs.microsoft.com/en-us/powershell/#pivot=main&panel=features) page has cards for DSC, JEA, and PSGallery that link to the reference, but nothing for WMF reference.

We need to add a card for WMF reference to one of the Hubs or change the "Download WMF" card to link to the reference instead.

@zjalexander @joeyaiello - Do you have a preference?

**Comment by zjalexander** [comment]
I would like to have a card in "Features" that points to the WMF reference. cc @JKeithB

**Comment by JKeithB** [comment]
I noted these were missing today, was frustrated by that face. There are a couple of options. It could be in [Getting Started](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell?view=powershell-5.1), or [Setup](https://docs.microsoft.com/en-us/powershell/scripting/setup/setup-reference?view=powershell-5.1), or as a replacement to the Download WMF {make it simply Windows Management Framework (WMF)}.

**Comment by sdwheeler** [comment]
@zjalexander Link to WMF page from WMF Download tile. https://docs.microsoft.com/en-us/powershell/wmf/readme

**Comment by JKeithB** [comment]
This makes the issue easier, but doesn't actually solve it. I believe a better solution would be to link to the docs from the tile, then have a link from the docs to the download.

**Comment by sdwheeler** [comment]
@JKeithB That is exactly what we talked about in our triage meeting today.

**Comment by sdwheeler** [comment]
Fixed
