### ISSUE TITLE
Join-Path help topic is missing the new -AdditionalChildPath parameter

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#1612]
Using reflection with `Get-Command -Syntax`, v6 now shows a new parameter named `AdditionalChildPath`:

```powershell
Join-Path [-Path] <string[]> [-ChildPath] <string> [[-AdditionalChildPath] <string[]>] [-Resolve] [-Credential <pscredential>] [<CommonParameters>]
```
This new parameter has the `ValueFromRemainingArguments` property, which enables joining an indefinite number of path components like so:

```powershell
> Join-Path a b c d
a/b/c/d
```

This parameter is not currently documented in https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Join-Path.md

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell

**Comment by sdwheeler** [comment]
Closed by #2623
