### ISSUE TITLE
PowerShell intro - where does it go? 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1617]
Issue Details
-----------------
We are moving this content from microsoft.com/PowerShell into Docs ... somewhere. The question is, where? 

![image](https://user-images.githubusercontent.com/6953993/29639153-9ca8ea3c-880e-11e7-902b-7e785416f559.png)

https://docs.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell?view=powershell-5.1 ? 
@juanpablojofre

**Comment by sdwheeler** [comment]
This information is not needed anymore in the new docs structure.
