### ISSUE TITLE
Provider help should be cleaned up

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1629]
Related to #1544, #1562 

Issue Details
-----------------
Provider help needs some work. PlatyPS can't currently process it. Might want to consider bringing provider-related content into reference content directly. 
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bobbytreed** [comment]
This is closed by #3191
