### ISSUE TITLE
about_Split - description of RegexMatch options 'Multiline' and 'Singleline' is incorrect

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell-Docs#1631]
Issue Details
-----------------

In [/reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/PowerShell/PowerShell-Docs/blob/b9282305775d00f28ce71c6475e23408dccce7de/reference/6/Microsoft.PowerShell.Core/About/about_Split.md#L206
) the following description appears:

 - **Multiline**: Multiline mode recognizes the start and end of lines and strings. Valid only with RegexMatch. Singleline is the default.
 - **Singleline**: Singleline mode recognizes only the start and end of strings. Valid only with RegexMatch. Singleline is the default.

Referencing [PowerShell language issue 4712](https://github.com/PowerShell/PowerShell/issues/4712), this is incorrect because:

 - it suggests there is only one option and it is switched between 'single' or 'multi', but there are two options which can be independently switched on/off. Singleline is not the opposite of Multiline.
 - it suggests they both do the same thing - what they do is not clearly described. I have put an explanation of what they do in the linked issue above.
 - it says 'Singleline' is the default, but both options are off by default.

Possible alternative text might reference:

 - https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions.multiline
 - https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions.singleline

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

NB. that any older versions of PowerShell will still forbid using them together, even if the documentation is updated and the linked issue is fixed in future releases.

**Comment by zjalexander** [comment]
See also #1640
