### ISSUE TITLE
'Get-WmiObject' is displayed on Docs site for PowerShell Core 6.0

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell-Docs#1645]
Issue Details
-----------------
Get-WmiObject is deprecated in PowerShell Core 6.0 but we still see it on [docs.microsoft.com](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/getting-wmi-objects--get-wmiobject-?view=powershell-6)

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
We have a whole doc scrub planned for PS6 in the leadup to release that includes this work item. Thanks for calling it out!

**Comment by sdwheeler** [comment]
This topic is no longer appearing in the v6 docset.

**Comment by mikemaccana** [comment]
Still appears at https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/getting-wmi-objects--get-wmiobject-?view=powershell-6 (as per the link). There's no 'this is deprecated' or 'this example doesn't wpork on powershell 6'.
