### ISSUE TITLE
Update PowerShell-Docs/dsc/overview.md to reflect updated DSC roadmap

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell-Docs#1653]
Issue Details
-----------------
DSC as described in the article has moved on a it. See: https://blogs.msdn.microsoft.com/powershell/2017/09/12/dsc-future-direction-update/ for the details of what I mean.

I think this article could be updated to reflect the multiple DSC Platforms (WIndows, Linux and the upcoming DSC Core.  

The documentation on the Pull server probably needs to change too - but that's an isuse for another issue. :-)

Thoughts??
 

Version(s) of document impacted
------------------------------
- [ x] Impacts 6 document
- [ x] Impacts 5.1 document
- [ x] Impacts 5.0 document
- [ x] Impacts 4.0 document
- [ x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bobbytreed** [comment]
Thank you for your input.  I am looping in @mgreenegit for his thoughts on this.

**Comment by mgreenegit** [comment]
I would prefer to keep roadmap information on the PowerShell Blog and have docs be reference material for each version.  Roadmap is more "planning information at a point in time" and documentation is "source of truth for how things function".

Just FYI, the next version of the DSC codebase is already in production and documented as part of Azure Policy.  We will be expanding scenarios in the future.  That will be the crux of a new blog post this month.

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration
