### ISSUE TITLE
V6 & V 5.1: Links to schemas are 404 ing or returing error message "resource has moved"

### ISSUE THREAD

**Issue by TaraMeyer** [PowerShell/PowerShell-Docs#1693]
Issue Details
Reported via Shanghai team:

Schema examples in reference docs for version 6 have issues.  Are these supposed to be "dummy" links or actual live links?  Also is there no related text to be added for these links if indeed they are supposed to be working?

Links supplied are for:  zh-cn, but behavior exists across all.

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [X] Impacts 5.1 document

Steps to reproduce:
1. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/get-cimassociatedinstance?view=powershell-6

no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk
 
text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

2. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/get-ciminstance?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

3. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/invoke-cimmethod?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

4. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/new-ciminstance?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

5. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/new-cimsessionoption?view=powershell-6
  
404 link, href: http://technet.microsoft.com/library/hh847761.aspx, text: 

http://technet.microsoft.com/library/hh847761.aspx

6. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/remove-ciminstance?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

7. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/set-ciminstance?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk
  
no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, 

text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

8. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/connect-pssession?view=powershell-6

no title link, href: http://schemas.microsoft.com/powershell, text: 

http://schemas.microsoft.com/powershell

9. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/powershell, text: 

http://schemas.microsoft.com/powershell

10.  On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/get-pssession?view=powershell-6
  
no title link, href: http://localhost:5985/WSMAN, text: http://localhost:5985/WSMAN
  
no title link, href: http://schemas.microsoft.com/powershell, 

text:http://schemas.microsoft.com/powershell

11. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/PowerShell, 

text: http://schemas.microsoft.com/PowerShell

12. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-6
  
no title link, href: http://schemas.microsoft.com/PowerShell, 

text: http://schemas.microsoft.com/PowerShell

13.  On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/receive-pssession?view=powershell-6
 
no title link, href: http://schemas.microsoft.com/powershell, 

text: http://schemas.microsoft.com/powershell

14. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.security/?view=powershell-6

404 link, href: https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.security/et-ChildItem-for-Certificate?view=powershell-6, 

text: et-ChildItem-for-Certificate

15. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6

  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx

16. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6

  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/login.aspx, text: http://website.com/login.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx
  no title link, href: http://website.com/service.aspx, text: http://website.com/service.aspx

17. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/providers/new-item-for-clientcertificate?view=powershell-6

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

  404 link, href: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor, text: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor

18. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/providers/new-item-for-plugin?view=powershell-6

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

  404 link, href: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor, text: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor

19. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/providers/new-item-for-resources?view=powershell-6

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

  404 link, href: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor, text: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor

20. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/providers/wsman-provider?view=powershell-6

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

  404 link, href: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor, text: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk, text: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_LogicalDisk

  404 link, href: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor, text: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_NumericSensor

21. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/get-wsmaninstance?view=powershell-6 

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/WQL, text: http://schemas.microsoft.com/wbem/wsman/1/WQL

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wsman/SelectorFilter, text: http://schemas.microsoft.com/wbem/wsman/1/wsman/SelectorFilter

  404 link, href: http://schemas.dmtf.org/wbem/wsman/1/cimbinding/associationFilter, text: http://schemas.dmtf.org/wbem/wsman/1/cimbinding/associationFilter

22. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/microsoft.wsman.management/set-wsmaninstance?view=powershell-6

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/WQL, text: http://schemas.microsoft.com/wbem/wsman/1/WQL

  no title link, href: http://schemas.microsoft.com/wbem/wsman/1/wsman/SelectorFilter, text: http://schemas.microsoft.com/wbem/wsman/1/wsman/SelectorFilter

  404 link, href: http://schemas.dmtf.org/wbem/wsman/1/cimbinding/associationFilter, text: http://schemas.dmtf.org/wbem/wsman/1/cimbinding/associationFilter

23. On page:https://review.docs.microsoft.com/zh-cn/powershell/module/packagemanagement/import-packageprovider?view=powershell-6

  no title link, href: https://github.com/oneget/onegethttps://oneget.org, text: https://github.com/oneget/onegethttps://oneget.org

**Comment by sdwheeler** [comment]
@TaraMeyer @zjalexander - All of these topics belong to the Windows docset not to the PowerShell docset. Also, most of the 404 links are for schemas which, I believe, are dummy links for namespaces.

**Comment by TaraMeyer** [comment]
@sdwheeler are you then saying the schema's used for examples in the topics are not supposed to be valid links, but are just there to give the user an idea of what it should look like?

Take from 2. above:

https://review.docs.microsoft.com/zh-cn/powershell/module/cimcmdlets/get-ciminstance?view=win10-ps&branch=master&viewFallbackFrom=powershell-6


![image](https://user-images.githubusercontent.com/14112499/32674574-add871f0-c608-11e7-8136-777dddb94f7e.png)

**Comment by sdwheeler** [comment]
As I understand it, schema URIs are just namespace names. See: https://en.wikipedia.org/wiki/XML_namespace#Namespace_names


The use of URIs taking the form of URLs in the http scheme (such as http://www.w3.org/1999/xhtml) is common, despite the absence of any formal relationship with the HTTP protocol. The Namespaces specification does not say what should happen if such a URL is dereferenced (that is, if software attempts to retrieve a document from this location). One convention adopted by some users is to place an RDDL<https://en.wikipedia.org/wiki/RDDL> document at the location.[5]<https://en.wikipedia.org/wiki/XML_namespace#cite_note-5> In general, however, users should assume that the namespace URI is simply a name, not the address of a document on the Web.





Thanks.


Sean D. Wheeler

Content Developer | Azure PowerShell

Azure Platform, Ecosystem & Experiences (APEX)  | Microsoft G+E

Office: 425-538-9279[cid:c58c20f6-9ad8-4074-b489-b1721ecc8545]  | Mobile: 425-979-8626[cid:d2df7630-0164-41c7-87b9-ea1d3cf72b45]


________________________________

**Comment by TaraMeyer** [comment]
@sdwheeler - thank you, kindly, I'm closing this issue and the related bug.
