### ISSUE TITLE
HelpUri for New-SmbShare forwards to invalid URL

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell-Docs#1712]
get-help new-smbshare -online

The HelpUri="http://go.microsoft.com/fwlink/?LinkID=241957"

It forwards to `http://technet.microsoft.comlibrary/jj635722(v=wps.620).aspx`

Notice the missing slash between `com` and `library`

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by davefoxtrin** [comment]
Thanks Steve. Most appreciated

**Comment by adityapatwardhan** [comment]
Updated the fwlink redirection. This should be fixed now.

**Comment by davefoxtrin** [comment]
Thanks Aditya

I can confirm all working now.
