### ISSUE TITLE
-SkipCertificateCheck not documented in get-help Invoke-RestMethod and Invoke-WebRequest

### ISSUE THREAD

**Issue by sbourdeaud** [PowerShell/PowerShell-Docs#1716]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by thezim** [comment]
I added these recently 6a5350c4fb416e9df01e33c8e500b46b263d0d63. 

Try running `Update Help`.

**Comment by sbourdeaud** [comment]
Just did, no dice.

**Comment by sdwheeler** [comment]
This change is live now.
