### ISSUE TITLE
links to different doc versions are broken

### ISSUE THREAD

**Issue by raghav710** [PowerShell/PowerShell-Docs#1737]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

All the links in this [page](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/README.md) seem to be broken (I get a 404 when accessing them)

**Comment by markroloff** [comment]
Searching through the repo, it looks like the version specific README files no longer exist. 

@juanpablojofre, should the links on the page referenced above be removed altogether?

**Comment by sdwheeler** [comment]
@zjalexander @JKeithB - I am not sure what this issue is about. I don't see Find-DSCResource in the DSC docset. I only see it in the PowerShellGet docset. Is this still a valid issue?
