### ISSUE TITLE
"See Also" Links

### ISSUE THREAD

**Issue by DanSchatz** [PowerShell/PowerShell-Docs#1765]
Just a tiny UX suggestion:

If "See Also" items in the docs.microsoft.com versions of the help files were links to that page, it would make navigation and learning about particular issues a little smoother and easier.

(I see that some are, but e.g., about_PackageManagement)

**Comment by juanpablojofre** [comment]
@DanSchatz, you're right about_it !! (pun intended).

The beauty of being an open sourced community is that everyone can make suggestions; but, most important **everyone can make contributions**.

Please, add your contributions next time you find something; I'll do my best to update the see also sections when I'm touching those topics.

Best regards,

-- JP

**Comment by juanpablojofre** [comment]
Closing the issue as there's no specific place to fix and/or take action.
