### ISSUE TITLE
$HOME variable content

### ISSUE THREAD

**Issue by gbrag-ms** [PowerShell/PowerShell-Docs#1816]
Issue Details
-----------------
In PowerShell 4 and earlier the $HOME variable was populated by combining the environment variable homedrive + homepath
Starting from Windows 10 / PowerShell 5 the $HOME variable is populated from the environment variable USERPROFILE

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Need to update about_Automatic_Variables.md

**Comment by sdwheeler** [comment]
see also #2138

**Comment by sdwheeler** [comment]
The result is the same.
