### ISSUE TITLE
About_* links broken

### ISSUE THREAD

**Issue by pascalberger** [PowerShell/PowerShell-Docs#1835]
Issue Details
-----------------
A lot of `about_*` links seem to be broken, like eg links to `about_Providers` [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-6). 

Is there some kind of automation which should transform them into links or should they be normal markdown links (in this case I can submit a PR)?

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
hey @sdwheeler, will the work for #1806 fix links as well?

**Comment by sdwheeler** [comment]
Use of Pandoc for rendering Markdown into plain text will remove hyperlinks and leave the text portion of the link. 

For example:

```
For more information, see [about_topic](link_to_about_topic).
```

Becomes:
> For more information, see about_topic.

**Comment by sdwheeler** [comment]
@zjalexander @pascalberger - We are in the process of scrubbing all about_* topics. The links will be fixed/populated as we work through the content update.
