### ISSUE TITLE
Update Contributor and Style guides

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#1864]
The current guidance does not reflect the latest changes to GFM, which is now based on the CommonMark spec. See: https://github.github.com/gfm/.

Recommended additions or changes:
- Do not use hard tabs--the number of spaces is significant in Markdown
- Single space after list item markers
- Single space after all periods.
- No blank spaces at line ends.
- Remove extra blank lines between paragraphs (one blank line only).
- Link Style Guide/Contributor Guide
- Document new About_* formatting guidance
- TOC files are now yaml--document the schema required by OPS

**Comment by zjalexander** [comment]
Do we need to list all of the markdown practices in our repo? Can we just have a pointer to best practices elsewhere? 

Also, can we add some documentation around the metadata like date/author? those seem to generate the most confusion.

**Comment by sdwheeler** [comment]
We can certainly add some info about metadata. However, we are currently managing metadata at the repo folder level. We should also talk about how to manage content written by non-MSFT contributors. We have expectations around freshness, updates, etc. How does that work for non-MSFT writers? 

As for markdown practices, I don't know of a common document we can point to. The guidance has changed in the last 6 months as OPS and GitHub have adopted the CommonMark standard (with extensions). And there are some OPS specific guidance. We should talk more about this in our next meeting.

**Comment by sdwheeler** [comment]
@zjalexander - Did you take a look at my refactor? https://github.com/sdwheeler/PowerShell-Docs/tree/sdw-guides/contributing

**Comment by zjalexander** [comment]
yup, it's the WRITING.md that I think can be mostly eliminated with a link to the markdown / GFM guide.

**Comment by sdwheeler** [comment]
@zjalexander - We can probably trim a lot but the GFM guide does not have the OPS-specific guidance.
