### ISSUE TITLE
update for WMF 5.0 is needed in feedback_fileinfo.md 

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#187]
feedback_fileinfo.md mentions Production Preview. Also, version numbers in output should be updated to WMF 5.0 RTM.

**Comment by DonGill** [comment]
Not sure if this issue was resolved. Capturing in OneView TFS ([46628](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=46628&fullScreen=false&_a=edit)) item.

**Comment by eslesar** [comment]
Addressed with #306
