### ISSUE TITLE
EXAMPLES separators missing in latest help update

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell-Docs#1882]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document
- [x] I only tested this in PoweShell Core 6 RC in a WSL console

This is what I see after running Update-Help:
```
NOTES


        You can also refer to Set-Content by its built-in alias, "sc". For more information, see about_Aliases (../Micro
soft.PowerShell.Core/About/about_Aliases.md).

        Set-Content is designed for string processing. If you pipe non-string objects to Set-Content, it converts the ob
ject to a string before writing it. To write objects to files, use Out-File.

        The Set-Content cmdlet is designed to work with the data exposed by any provider. To list the providers availabl
e in your session, type `Get-PsProvider`. For more information, see about_Providers.

    Example 1: Replace the contents of multiple files in a folder

    PS C:\> Set-Content -Path "C:\Test1\test*.txt" -Value "Hello, World"
```
I expected this (from Win PS 5.1):
```
NOTES


        You can also refer to Set-Content by its built-in alias, sc *. For more information, see about_Aliases.
        Set-Content is designed for string processing. If you pipe non-string objects to this cmdlet, it converts the
        object to a string before writing it. To write objects to files, use Out-File. Set-Content cmdlet is designed
        to work with the data exposed by any provider. To list the providers available in your session, type
        `Get-PsProvider`. For more information, see about_Providers.

        *



    -------------------------- EXAMPLE 1 --------------------------

    C:\PS>Set-Content -Path C:\Test1\test*.txt -Value "Hello, World"
```
I think you can see from looking at these two examples, it makes it hard to locate the examples in a sea of text without having those visual markers (example separators).

**Comment by zjalexander** [comment]
Yup. There's a step we're working on to have the new format consumed by PanDoc to make it nicely-formatted in both plaintext and markdown. #1488 will resolve this - let me check on status for that.

**Comment by zjalexander** [comment]
Oops, missed this wasn't an about_ topic. 

This is a consequence of switching to MarkDown-based formatting, which we convert to MAML via PlatyPS. Looks like our "examples" headers are getting rendered differently. 

If you think this should be changed, we're open to it - please open a bug in the PlatyPs repo.

**Comment by joeyaiello** [comment]
This issue was moved to PowerShell/platyPS#320
