### ISSUE TITLE
[Get-FormatData] The parameter 'Powershellversion' is not documented.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell-Docs#1895]
Issue Details
-----------------
The parameter 'Powershellversion' is not documented and the use scenario either

[See](https://github.com/PowerShell/PowerShell/issues/4237#issuecomment-314954093)

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by MSAdministrator** [comment]
In Progress

**Comment by LaurentDardenne** [comment]
Thanks.
The [exemple 5](https://github.com/PowerShell/PowerShell-Docs/blob/12dceada70280f96eaeab9714d72957d1a7f7468/reference/6/Microsoft.PowerShell.Utility/Get-FormatData.md):
```powershell
Get-FormatData -TypeName 'Microsoft.Powershell.Utility.FileHash' -PowerShellVersion 6.0
```
Return nothing in Powershell 6.0.0 :
```powershell
Get-FormatData -TypeName 'Microsoft.Powershell.Commands.FileHashInfo' -PowerShellVersion 6.0
```
And for this text :
> This example shows how to use Get-FormatData to get format data for a specified TypeName and a specified PowerShell version.

I dont understand when and why I must use the -PowerShellVersion parameter.
What is the difference between a call with this parameter and a call without this parameter?
