### ISSUE TITLE
Sharp character '#' does not render properly

### ISSUE THREAD

**Issue by eslesar** [PowerShell/PowerShell-Docs#19]
In a title, attempting to use the name of the C# programming language renders as only "C"...parser appears to treat the '#' as the end of a heading.

**Comment by Windos** [comment]
You should be able to escape that hash symbol with a backslash, e.g. `## C\# Parser` becomes:

## C\# Parser

**Comment by eslesar** [comment]
Sorry, I should have mentioned in the issue that I tried using the backslash escape character.

**Comment by eslesar** [comment]
Markdown limitation. Addressed by styling as inline code.
