### ISSUE TITLE
Selecting "contribute" on MSDN published documents should go to MASTER and NOT LIVE branch

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#191]
@joeyaiello  ... It should go to "master" branch instead.
For example: Clicking contribute on https://msdn.microsoft.com/en-us/powershell/wmf/releasenotes takes to https://github.com/PowerShell/PowerShell-Docs/blob/live/wmf/releasenotes.md .. it should take the contributor to https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/releasenotes.md

**Comment by joeyaiello** [comment]
We're following up with the OPS tooling folks. I'll update here with a timeline if/when I have more info.

**Comment by DonGill** [comment]
We should talk @joeyaiello. @HemantMahawar is spot on. Who is pushing back from the OPs team? Sanketh?

**Comment by sankethka** [comment]
I wasn't aware of this. I will check with Sandra as well.

**Comment by saldana** [comment]
@DonGill, nobody in our team pushed back. This is in our radar and we are working on it. Expected delivery date is April 27. Thanks.

**Comment by DonGill** [comment]
@saldana Awesome. I read that the wrong way then. Sry. 

So, what needs to be done to get this fixed?

**Comment by saldana** [comment]
@DonGill, NP. Our engineering team will be adding a setting to make the contribution branch configurable. We will deliver in next sprint, April 27. We will provide @joeyaiello the instructions.

**Comment by DonGill** [comment]
@saldana tyvm.

**Comment by HemantMahawar** [comment]
@saldana Any update on this? cc @DonGill

**Comment by saldana** [comment]
I am following up with the PM, as I do not see the feature completed in our system. @joeyaiello is in the loop.

**Comment by sankethka** [comment]
@saldana - Just bumped into Eric in the hallway and he mentioned it was done today. If its done, what configuration needs to be changed to make utilize this?

**Comment by saldana** [comment]
@sankethka sankethka The PM confirmed it is done, but we do not have documentation ready. She will get it this week.

**Comment by HemantMahawar** [comment]
@sankethka This issue is now fixed with #346 .. cc @saldana @DonGill @joeyaiello @eslesar
