### ISSUE TITLE
[question] Handling of PowerShell examples for non-Windows platforms

### ISSUE THREAD

**Issue by BernieWhite** [PowerShell/PowerShell-Docs#1941]
This is more of a discussion topic then an issue.

Working from the platyPS side looking at PowerShell/platyPS#294 (related to #1511). We are discussing the `PS C:\>` convention in relation to other platforms outside of Windows.

Based on the information in #1511 and the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/STYLE.md) there is direction not to include the prefix `PS C:\>` within PowerShell code examples for online help.

- Is this the direction or intent for examples within the PowerShell help system?
- Is there a reliance on the PowerShell help system to automatically add  `PS C:\>`  to examples when invoked?
- How are other platforms represented? or is the `PS C:\>` prefix used regardless of operating system?

Thanks :)

**Comment by BernieWhite** [comment]
@zjalexander Thoughts?

**Comment by markekraus** [comment]
not that this justifies the continued use of `PS C:\>` in the documentation, but, it is possible to have a `C:` PSDrive on non-windows platorms:

```powershell
New-PSDrive -Name c -PSProvider FileSystem -Root ~/
Set-Location c:\
```

It will display as `PS c:/>`.

**Comment by sdwheeler** [comment]
@BernieWhite @markekraus - We just published a new addendum to the style guide https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/FORMATTING-CODE.md

Please read this.

**Comment by Greg-Smulko** [comment]
It was renamed to https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/contributing/5-FORMATTING-CODE.md

**Comment by sdwheeler** [comment]
@Greg-Smulko The contributor guide is moving to https://docs.microsoft.com/en-us/contribute/powershell/powershell-contribute
