### ISSUE TITLE
Add documentation for RetryCount and RetryIntervalSec

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell-Docs#1991]
Issue Details
-----------------
New parameters have been added by PR: https://github.com/PowerShell/PowerShell/pull/5760 for `Invoke-WebRequest` and `Invoke-RestMethod` cmdlets. Documentation should be added for those. 

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by markekraus** [comment]
When documenting this on `Invoke-RestMethod`, please indicated that when `-FollowRelLink` is used, the `-RetryCount` applies to each link and not total failures.
