### ISSUE TITLE
Error in example 3

### ISSUE THREAD

**Issue by ThierryBT** [PowerShell/PowerShell-Docs#2001]
Hi and sorry for my Funny English,
The example 3 is bad. 
Configuration SecureTigerTeamSrouce 
{
  Import-DscResource -ModuleName 'PSDesiredStateConfiguration'
    Node TigerTeamSource.Contoso.Com {
  Group TigerTeamAdmins
    {
       GroupName        = 'TigerTeamAdmins'   
       Ensure           = 'Absent'             
       MembersToInclude = "Contoso\JerryG"
    }}}

To delete user, you must write

Configuration SecureTigerTeamSrouce 
{
  Import-DscResource -ModuleName 'PSDesiredStateConfiguration'
  
  Node TigerTeamSource.Contoso.Com {
  Group TigerTeamAdmins
    {
       GroupName        = 'TigerTeamAdmins'   
       Ensure           = 'Present'             
       MembersToExclude = "Contoso\JerryG"
    }
  }
}

The current example delete the group.

Regards
Thierry

**Comment by sdwheeler** [comment]
@ThierryBT - what document is this from? Please provide the URL to the file.

**Comment by ThierryBT** [comment]
@sdwheeler Sorry ...This link, https://docs.microsoft.com/en-us/powershell/dsc/groupresource.
Regards

**Comment by sdwheeler** [comment]
@mgreenegit Does this make sense to you?

**Comment by SwarfegaGit** [comment]
Without testing I think @ThierryBT is correct.  The example is removing the whole group rather than a specific user.  I think the following should be the correct syntax (again... without testing):

`Configuration SecureTigerTeamSrouce 
{
  Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

  Node TigerTeamSource.Contoso.Com {
  Group TigerTeamAdmins
    {
       GroupName        = 'TigerTeamAdmins'   
       Ensure           = 'Present'             
       MembersToExclude = "Contoso\JerryG"
    }
  }
}`

**Comment by sdwheeler** [comment]
Submitted an update in https://github.com/PowerShell/PowerShell-Docs/pull/2015.

**Comment by sdwheeler** [comment]
Fixed

**Comment by ThierryBT** [comment]
Thank you very much !
Regards
Thierry
