### ISSUE TITLE
Question about Process{} block in a function

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2028]
The question came from a customer via a LiveFyre comment on the about_Functions_Advanced_Methods.md topic.

The About_ topics states: "If there is no pipeline input, the Process block is not used."  However testing this using your sample cmdlet and adding Write-Verbose statements shows this doesn't appear to be accurate.

```powershell
Function Test-ScriptCmdlet {
  [CmdletBinding()]
    param ($parameter1)
    begin { Write-Verbose "Begin block" }
    process { Write-Verbose "Process block" }
    end { Write-Verbose "End block" }
}
```

Invoked by:

```powershell
Test-ScriptCmdlet -parameter1 "Test" -Verbose
```

Yields the results:

```
PS C:\> Test-ScriptCmdlet -parameter1 "Test" -Verbose
VERBOSE: Begin block
VERBOSE: Process block
VERBOSE: End block
```

Which shows that:
1) There is no pipeline input
2) The Process block executed

Is there more detail around this?

**Comment by exchange12rocks** [comment]
I think the documentation is incorrect. Pipeline won't work without the process block, but its existence does not prevent the code inside the block from executing when running a function w/o passing input through pipeline to it.

**Comment by strawgate** [comment]
The documentation is definitely confusing but I think i know the use-case they are referring to. If you pass an empty array over the pipeline the begin and end blocks are used but the process block is not.

```
@() | Test-ScriptCmdlet
VERBOSE: Begin block
VERBOSE: End block
```

The effect of this is that if Test-ScriptCmdlet was at the end of a pipeline that filters out all of the objects before they get to Test-ScriptCmdlet, process would not run but begin and end would.

```
get-item . | where-object {$_ -eq $null} | Test-ScriptCmdlet
VERBOSE: Begin block
VERBOSE: End block
```

The language should be updated to indicate that the process block is not used when the function is used in a pipeline but no pipeline input makes it to the function.

**Comment by sdwheeler** [comment]
I am not sure how much clearer we can say it. The article states this:

> For example, if the function is the first command in the pipeline, the Process block will be used one time.

In the example provided, they are calling the function as the first (and only) command on the pipeline. So the process block is executed.

**Comment by exchange12rocks** [comment]
We might make it clear by reformatting it with lists:

This block is used to provide record-by-record processing for the function.
This block might be used any number of times, or not at all, depending on the input to the function:
- If the function is the first command in the pipeline:
  - The `Process` block will be used one time.
- If the function is not the first command in the pipeline:
  - The `Process` block will be used one time for every input that the function receives from the pipeline
  - If there is no pipeline input, the `Process` block is not used, only `Begin` and `End` blocks will be executed, if presented.

**Comment by BrucePay** [comment]
Perhaps it would be better to say "if there is no pipeline input, the `process` block will be executed once. If there is input and it is non-empty, the `process` block will be executed once for each input object. If there is  input but it is empty, then the `process` block will not be executed."
