### ISSUE TITLE
Use utf8-noBOM for help

### ISSUE THREAD

**Issue by dsolodow** [PowerShell/PowerShell-Docs#2036]
From: https://github.com/PowerShell/vscode-powershell/issues/1104

VSCode on Windows, PSCore on Ubuntu.
Get-Help shows fine. but running say:
```powershell
help get-command
```
Shows a BOM character at the start of the help data.
![image](https://user-images.githubusercontent.com/7574074/34805978-94f6800c-f64e-11e7-9593-be96ad993373.png)

**Comment by timkite** [comment]
Also seeing this on PowerShell 6.0 (release) on Mac (and have for several previous releases).

**Comment by joeyaiello** [comment]
This issue was moved to PowerShell/PowerShell#6277

**Comment by joeyaiello** [comment]
This is a bug in PowerShell itself, so I copied it over to that repo.
