### ISSUE TITLE
Make documentation accessible via DevDocs and Dash/Zeal

### ISSUE THREAD

**Issue by thorstenkampe** [PowerShell/PowerShell-Docs#2054]
[DevDocs](https://devdocs.io/) and [Dash](https://kapeli.com/dash)/[Zeal](https://zealdocs.org/) are API documentation browsers. They
> combine multiple API documentations in a clean and organized UI with instant search, offline support, dark theme, keyboard shortcuts, and more.

**Comment by sdwheeler** [comment]
We have noted this request. It is on our internal backlog. You can also submit feedback via https://aka.ms/sitefeedback
