### ISSUE TITLE
Wrong url into https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell-Docs#2080]
Into this [page](https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features), the links in paragraph '_Learn more about using PowerShell Editions_' referencing the current page.

**Comment by bobbytreed** [comment]
This was fixed along side #2322 which referenced the same links

**Comment by LaurentDardenne** [comment]
Thanks.
