### ISSUE TITLE
Update telemetry Opt-out for 6.1

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2088]
Issue Details
-----------------
you can now opt-out of telemetry by setting `POWERSHELL_TELEMETRY_OPTOUT` to `yes`
https://github.com/PowerShell/PowerShell/pull/6063/files#diff-187b8dbd25c60f08c04f26576d85249aR57

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by alexandair** [comment]
@sdwheeler 
Please, close it. It's fixed by #2111.
