### ISSUE TITLE
Update-Help fails for PrintManagement module

### ISSUE THREAD

**Issue by dsolodow** [PowerShell/PowerShell-Docs#2115]
update-help : Failed to update Help for the module(s) 'PrintManagement' with UI culture(s) {en-US} : Unable to connect
to Help content. The server on which Help content is stored might not be available. Verify that the server is
available, or wait until the server is back online, and then try the command again.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by joeyaiello** [comment]
This issue was moved to MicrosoftDocs/windows-powershell-docs#137

**Comment by joeyaiello** [comment]
These modules are all owned and tracked in the repo I moved them to above. Feel free to subscribe to them, but I do know the right people are aware of this and following up.
