### ISSUE TITLE
Update-Help fails for WindowsUpdateProvider

### ISSUE THREAD

**Issue by dsolodow** [PowerShell/PowerShell-Docs#2117]
update-help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI
culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property
in the module manifest is valid or check your network connection and then try the command again.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by joeyaiello** [comment]
This issue was moved to MicrosoftDocs/windows-powershell-docs#139
