### ISSUE TITLE
Get-Hotfix docs have incorrect statement about input

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2131]
Issue Details
-----------------

The help for get-hotfix states it does not accept pipeline input, yet the -computername parameter accepts pipeline input byPropertyName.

```
Inputs
    None
       You cannot pipe input to this cmdlet.
```

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by ruinedmylife** [comment]
Thank you

**Comment by sdwheeler** [comment]
Fixed

**Comment by jszabo98** [comment]
Computername Pipeline input actually doesn't currently work with get-hotfix in PS 5.1:  https://github.com/PowerShell/PowerShell/issues/7640
