### ISSUE TITLE
Set-LocalUser doc has incorrect parameter description

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2142]
Issue Details
-----------------
In the description of the Password parameter, the parameter of Read-Host is incorrect. The command is: Read-Host -AsSecureString 

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by bobbytreed** [comment]
Example 2 currently uses -AsSecureString with Read-Host

**Comment by bobbytreed** [comment]
@sdwheeler  The source seems to list Syntax as a hidden anchor

<h2 class="hiddenAnchor" id="syntax">Syntax</h2>
