### ISSUE TITLE
Document -Path aliases added to several cmdlets

### ISSUE THREAD

**Issue by KevinMarquette** [PowerShell/PowerShell-Docs#2147]
Issue Details
-----------------
New aliases are getting added to help standardize the use of a path variable in https://github.com/PowerShell/PowerShell/pull/5817

These are new changes for a yet to be released version of PowerShell.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 documentation
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by alexandair** [comment]
@sdwheeler 
Please, close it.
Someone already fixed all affected cmdlet topics in release-ps61 branch.
