### ISSUE TITLE
Document -Password and -NoPromptForPassword parameters added to Get-PfxCertificate cmdlet

### ISSUE THREAD

**Issue by maybe-hello-world** [PowerShell/PowerShell-Docs#2150]
Issue Details
-----------------
Parameters -Password and -NoPromptForPassword were added to Get-PfxCertificate cmdlet at Powershell/Powershell#6113

These are new changes for a yet to be released version of PowerShell.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fixed in PR #2830
