### ISSUE TITLE
PS Core macOS installation instructions should be its own document.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell-Docs#2164]
Issue Details
-----------------
macOS an Linux installation instructions for PS core where split from Linux with https://github.com/PowerShell/PowerShell/pull/5823 but #2026 pulled them in as single document a day later. https://github.com/PowerShell/PowerShell/pull/6326 is pending which also groups them together.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Setup instructions are now split out for each OS
