### ISSUE TITLE
Installation instruction changes for powershell 6 should be reviewed by a PowerShell core team member

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2166]
Issue Details
-----------------

Powershell/PowerShell#6339 was submitted to the wrong repo

Installation instruction changes for PowerShell 6 should be reviewed by a PowerShell core team member
I suggest creating a code owners file so that someone is automatically added to the PR.

Exampl: https://github.com/PowerShell/PowerShell/blob/master/.github/CODEOWNERS

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by thezim** [comment]
#2164 is related.

**Comment by Arnavion** [comment]
>Powershell/PowerShell#6339 was submitted to the wrong repo

So did you want me to close it and port it to this repo? You didn't post this comment on the PR itself, and I only happened to come across this issue on seeing it linked from my PR. Following the breadcrumb trait I found https://github.com/PowerShell/PowerShell/pull/6326, so I assume the answer is "yes."

**Comment by TravisEz13** [comment]
This is fixed
