### ISSUE TITLE
Add documentation for Update-Help -Scope User

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell-Docs#2168]
Issue Details
-----------------

Help needs to be added for new parameter for `Update-Help`, `-Scope`

Also update the resource string `UpdatableHelpRequiresElevation` to refer to `-Scope` and cleanup 'Run as Administrator`

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by mklement0** [comment]
To summarize and add some info:

`-Scope CurrentUser` is now the default, and only explicit use of `-Scope AllUsers` requires administrative privileges.

To use `-Scope AllUsers` on Unix-like platforms, run `Update-Help` as follows:

```powershell
sudo pwsh -c Update-Help
```

(The above requires a user that is authorized to run `sudo` via the `/etc/sudoers` file.)
