### ISSUE TITLE
Global issue: Odd underscore presentation on files with spaces in title

### ISSUE THREAD

**Issue by NickCraver** [PowerShell/PowerShell-Docs#2196]
I noticed this today, in the sidebar:
![image](https://user-images.githubusercontent.com/454813/37712773-46146ad4-2ceb-11e8-98f2-927f782e6c4f.png)

It's also in the page title, so users on search engines see it as well:
![image](https://user-images.githubusercontent.com/454813/37712793-57779aee-2ceb-11e8-8c72-ba005fcd8757.png)

Here's an example link: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-6
And a link to that document: https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md

I wasn't sure how to file/fix this since it appears to be an engine issue. There's both the underscores to spaces issue and "about" should probably be capitalized (consistency issue here: https://github.com/PowerShell/PowerShell-Docs/tree/staging/reference/6/Microsoft.PowerShell.Core/About)

**Comment by sdwheeler** [comment]
This is by design. The topic names are used by Get-Help.

**Comment by NickCraver** [comment]
@sdwheeler How can this be by-design? The title of the document is `<title>about_Try_Catch_Finally | Microsoft Docs</title>`, the title *in* the document is "About Try Catch Finally", the URL is all lower-case, and the sidebar is "about_Try_Catch_Finally". There's inconsistency in the *rendering* of the topic, regardless of what's needed for Get-Help and URLs. Neither of those are strictly necessary changes to fix the UI presentation issues.

**Comment by lol768** [comment]
100% agree. The `<title>` elements look awful.

Please sort it out so that the title inside the document is used in the `<title>` element.

**Comment by lol768** [comment]
These are displayed in the Google search results too, it looks dumb.
