### ISSUE TITLE
Add -Not Feature to Where-Object

### ISSUE THREAD

**Issue by SimonWahlin** [PowerShell/PowerShell-Docs#2199]
Issue Details
-----------------
Document `-Not` parameter of Where-Object added in PowerShell/PowerShell#6464

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by IISResetMe** [comment]
Should probably update the version impact description to 

- [X] Impacts 6.1 document
- [X] Impacts 6.1 document
- [X] Impacts 6.1 document
- [X] Impacts 6.1 document
