### ISSUE TITLE
troubleshooting.md contains a bunch of TODO statements

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#220]
troubleshooting.md is missing a bunch of images (represented for now with TODO statements).
xDscDiagnostics module contains 4 functions. Only two functions are mentioned in the article.

**Comment by DonGill** [comment]
Not sure if this was resolved. Capturing in OneView TFS ([46630](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=46630&fullScreen=false&_a=edit)) item.

**Comment by eslesar** [comment]
This is addressed in #448 
I removed reference type information in favor of a link to the public repo, because xDscDiagnostics is a moving target, and maintenance will be an issue.
