### ISSUE TITLE
about_profile tables don't render correctly in pwsh

### ISSUE THREAD

**Issue by vr8hub** [PowerShell/PowerShell-Docs#2228]
Issue Details
-----------------
The tables in about_profile appear to be the raw markdown text instead of rendered text. IOW, whatever rendered the XML help from markdown didn't do a very good job on the tables.

Here's the first table in pwsh 6.0.2's help, taken straight from the screen:
```powershell
  ---------------------------------------------------------------------------------------------------------------------------------
  Description                  Path
  ---------------------------- ----------------------------------------------------------------------------------------------------
  Current user, Current Host   $Home\\[My ]Documents\\WindowsPowerShell | | | \\Profile.ps1 | |Current User, All Hosts |$Home\[My
                               ]Documents\Profile.ps1

  All Users, Current Host      $PsHome\Microsoft.PowerShell_profile.ps1 | |All Users, All Hosts |$PsHome.ps1
  ---------------------------------------------------------------------------------------------------------------------------------
```

Here's that same table in 5.1's help.
```powershell
        Description                Path
        -----------                ----
        Current User, Current Host $Home\[My ]Documents\WindowsPowerShell\Profile.ps1
        Current User, All Hosts    $Home\[My ]Documents\Profile.ps1
        All Users, Current Host    $PsHome\Microsoft.PowerShell_profile.ps1
        All Users, All Hosts       $PsHome\Profile.ps1
```

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [X] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all versions of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@joeyaiello - This is a build bug not a docs issue. The version of the about_profiles topic published in updateable help has the problem. Need to investigate the build. Can you move this issue to the source repo?

**Comment by adityapatwardhan** [comment]
We are using pandoc version 2.0.6. https://github.com/PowerShell/PowerShell-Docs/blob/staging/appveyor.ps1#L11

We invoke it with the following options.

```
--to=plain+multiline_tables+inline_code_attributes, --columns=75
```

**Comment by sdwheeler** [comment]
Fixed
