### ISSUE TITLE
Document the new $Is* automatic variables and the new $PSVersionTable properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2229]
[about_automatic_Variables](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) is missing descriptions of:

* the automatic Boolean `$Is*` variables:
```powershell
$IsCoreCLR
$IsLinux
$IsMacOS
$IsWindows
```

* the new properties added to `$PSVersionTable:

```powershell
.GitCommitId  # seemingly *replaces* .BuildVersion
.OS # same as [System.Runtime.InteropServices.RuntimeInformation]::OSDescription
.Platform # same as [System.Environment]::OSVersion.Platform 
```

A **caveat re `.Platform`**:

It should be made clear that the value on _both_ Linux and macOS is `Unix` (`[System.PlatformID]::Unix`), which may be unexpected, but is [as designed](https://github.com/dotnet/platform-compat/blob/master/docs/DE0007.md).
`$IsMacOS` and `$IsLinux` allow distinguishing these two platforms.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell

**Comment by bmkaiser** [comment]
@mklement0 , I think you meant `$IsLinux` instead of `$IsUnix` in the caveat section.

**Comment by mklement0** [comment]
Thanks, @bmkaiser  - fixed.
