### ISSUE TITLE
CIM cmdlets help topics are only available for version 6, creating the mistaken impression that they were only introduced then

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2294]
CIM cmdlets were introduced in v3, yet this repo only contains v6 topics.

This also affects the published topics in that they mistakenly suggest that CIM cmdlets were only introduced in v6:

E.g., attempting to switch to the v3 topic for `Get-CimClass` redirects to https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/get-cimclass?view=powershell-6&viewFallbackFrom=powershell-3.0 which then displays the following, misleading message:

> The requested page is not available for Powershell 3.0. You have been redirected to the newest product version this page is available for.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------

The v6 topics are present, but no other versions.

**Comment by sdwheeler** [comment]
Need to investigate if the docs existed and were delete or if the docs were never published. If deleted, then we need to try to restore. If never existed then we need to recreate the old versions.

**Comment by sdwheeler** [comment]
Added CimCmdlets and PSDiagnostics to all versions.
