### ISSUE TITLE
PowerShell 6.0 docs should be updates for Fedora and Ubuntu EOLs

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2302]
Issue Details
-----------------
See
https://github.com/PowerShell/PowerShell/issues/5989

### Summary:
Fedora 25 should be replaced with Fedora 27
Ubuntu 17.04 should be replaced with Ubuntu 17.10

### additional details
fedora 25 is EOL
ubuntu 17.04 is EOL

@anmenaga brought up 17.04
PowerShell/PowerShell#5984 brought up fedora 25

from @anmenaga 
>FYI: Ubuntu 17.04 reached End of Life on January 13, 2018.
The repositories have been moved to a different location and must be accessed differently.
This is the reason why I was getting apt-get update errors on 17.04 during package validation.
The supported upgrade path from Ubuntu 17.04 is via Ubuntu 17.10.
http://fridge.ubuntu.com/2018/01/17/ubuntu-17-04-zesty-zapus-reached-end-of-life-on-january-13-2018/

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@joeyaiello @SteveL-MSFT This is really a reference problem. Can you get this assigned to the right owner?

**Comment by SteveL-MSFT** [comment]
@TravisEz13 can you submit PR with proposed changes?  Engineering team owns updates to reference docs.

**Comment by TravisEz13** [comment]
@SteveL-MSFT We need to do the engineering work first.    17.10 has only been tested with 6.1.  I don't think Fedora has been tested and the packages haven't been renamed.
