### ISSUE TITLE
Parameter Sets and Accepted Values for parameters are messed up

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#2306]
This is just an example. You can find this bug not just for PowerShell cmdlets owned by the PowerShell team, but also for modules owned by other product groups.

This is a source for the -For parameter in Restart-Computer (https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Restart-Computer.md#-for)

```
Type: WaitForServiceTypes
Parameter Sets: DefaultSet
Aliases:
Accepted values: PowerShell, WinRM, Wmi

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
``` 

This is a rendered version (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-computer?view=powershell-6):

```
Type: WaitForServiceTypes
Parameter Sets: PowerShell, WinRM, Wmi
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

"Accepted values" entry is missing. Accepted values are now under "Parameter Sets".

**Comment by vors** [comment]
Oh interesting.
The `Accepted values` is not currently in the platyPS [schema](https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md).
Parameter serialization class: https://github.com/PowerShell/platyPS/blob/b89efd83ef3340588ef66f72d167950a87351f82/src/Markdown.MAML/Model/YAML/YamlParameter.cs#L8

And the yaml metadata for parameters is not flexible to accomodate any key-value pairs, it's a pre-defined list of things. Namely, if you try to create MAML help out of such markdown it should fail with an error. So I'm not sure how the `Accepted values` appered in the help at the first place...

Not the rendered version of the help at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-computer?view=powershell-6 is a seprate story: it's created purely from markdown, but apperently there is some transofrmation that takes place (I think it's called opendocs).
So there are 2 parts:

1. The bug that @alexandair points at is really the open-docs thing.
2. Using non-standart parameter metadata is a problem - you cannot create maml xml out of it.

**Comment by sdwheeler** [comment]
This is an OPS Bug. I will file a bug for this.

**Comment by sdwheeler** [comment]
This was fixed in the latest OPS build.
