### ISSUE TITLE
Document the v4+ .ForEach() and .Where() methods ("collection operators")

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2307]
<sup>Follow-up from a discussion with @BrucePay 
 at https://github.com/PowerShell/PowerShell/issues/6576.</sup>

The effectively undocumented `.Where()` and `.ForEach` _methods_ - available on _any_ object exposed by PowerShell - were introduced in the context of DSC in v4 and provide functionality similar to the `Where-Object` and `ForEach-Object` cmdlets, but (a) in a more performant way (albeit in an all-in-memory way)  and (b) with more features. 

The most comprehensive documentation that I'm aware of is [this third-party blog post by @KirkMunro](http://www.powershellmagazine.com/2014/10/22/foreach-and-where-magic-methods/).

* These methods need to be documented as part of the regular user documentation,
* with the DSC documentation referring to it.

I suggest doing so in the context of the `ForEach-Object` and `Where-Object` cmdlets to introduce them as in-memory, expression-mode, preexisting-collection operator-like alternatives to these cmdlets.

---

The **inadequate existing references** to these methods ("operators"):

Regular documentation:

* https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Where-Object.md:

> Starting in Windows PowerShell 4.0, Where() operator behavior has changed.  ...

Note only is `.Where()` not documented itself, the whole paragraph is confusing, because `.Where()` didn't even _exist_ prior to v4.

* https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Methods.md:
> "Beginning in PowerShell 4.0, collection filtering by using a method syntax is supported."

DSC documentation:

* [Using configuration data in DSC](https://docs.microsoft.com/en-us/powershell/dsc/configdata) 
makes isolated, passing references to `.Where()` and `.ForEach()`.

* [Separating configuration and environment data](https://docs.microsoft.com/en-us/powershell/dsc/separatingenvdata) contains examples (only) of  `.Where()` use.

* (don't know where the sources for these documents are).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell

**Comment by TheIncorrigible1** [comment]
@sdwheeler I found excellent articles by Boe Prox about these methods:

https://mcpmag.com/articles/2015/12/10/foreach-method-in-powershell.aspx

https://mcpmag.com/articles/2015/12/02/where-method-in-powershell.aspx
