### ISSUE TITLE
Faulty Links on https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features

### ISSUE THREAD

**Issue by edbakermct** [PowerShell/PowerShell-Docs#2322]
Issue Details
-----------------
https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features

this page has a list  as below

Learn more about using PowerShell Editions

Determine running edition of PowerShell
Declare a module's compatibility to specific PowerShell versions
Filter Get-Module results by CompatiblePSEditions
Prevent script execution unless run on a compatible edition of PowerShell

all links to the above point straight back to the same page.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document
![image](https://user-images.githubusercontent.com/23341813/38553689-e4b61dbe-3cb7-11e8-9e69-e7586484acd1.png)

**Comment by bobbytreed** [comment]
This has been fixed in PR 2357
