### ISSUE TITLE
Document ad-hoc script-block arguments for end users

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2338]
<sup>See #2427 for the cmdlet _author_ perspective.</sup>

Ad-hoc script-block arguments are widely used, but not documented, which makes it hard to infer when and how to use them.

A widely used pattern is to pass a script block to `Rename-Item -NewName` in order to derive the new name from the input file:

```powershell
Get-Item *.txt | Rename-Item -NewName { $_.BaseName + '.rtf' } -WhatIf
```

Specifically, this technique should be explained / mentioned in:

* [about_Parameters](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md)
* [about_Script_Blocks](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Script_Blocks.md)

The only existing information I could find is:

* A comment by @dlwyatt on a Boe Prox blog post at https://learn-powershell.net/2014/10/11/using-a-scriptblock-parameter-with-a-powershell-function/

* A blog post by Jeffrey Snover from 2006, which, however,  is partly obsolete, because it claims that the feature works specifically and only with parameters that are NOT designed to take pipeline input: https://blogs.msdn.microsoft.com/powershell/2006/06/23/flexible-pipelining-with-scriptblock-parameters/ - however, since (at least) PSv2 it works only for parameters that ARE designed for pipeline input.

Based on my own findings, **script-block parameters work as follows**:

**_Ad-hoc Script-Block Arguments_** are an **_implicit_ feature** that:
* **[only] works with parameters that are designed to take pipeline input**
    * as long as those parameters are NOT typed as one of the following, in which case REGULAR parameter binding happens:
        * `[scriptblock]` 
        * `[object]`             # `[psobject]`, however, DOES work
        * (no type specified)  # effectively the same as `[object]`
* **enables  per-input-object transformations via a script block** (to which the current pipeline object is passed as `$_`, as usual)
    * Since such ad-hoc script blocks by definition do not match the type of the parameter you're targeting, you **must always use the parameter name explicitly**.
    * ScriptBlock Parameters provide unconditional access to the pipeline input object, even if the parameter would ordinarily NOT be bound by a given pipeline object in the absence of the designated property.
    * This enables techniques such as the following call to `Rename-Item`, where the pipeline input from `Get-Item` is - as usual - bound to the `-LiteralPath` parameter, but passing a script block to `-NewName` - which would ordinarily only bind to input objects with a `.NewName` property - enables access to the same pipeline object and thus to derive the destination filename from the input filename:
        * `Get-Item file | Rename-Item -NewName { $_.Name + '1' }  # renames 'file' to 'file1'`; input binds to _both_ `-LiteralPath` (implicitly) _and_ the `-NewName` script block.
    * The script blocks run in a _child_ variable scope, which means that you cannot directly modify the caller's variables, such as incrementing a counter; as a workaround, use `Get-Variable` and reference a variable _object's_ `.Value` property inside the script block - see [this SO answer](https://stackoverflow.com/a/49890409/45375) for an example.
    * Error condition: If you pass a script block but do not also provide pipeline input, you'll get the following error:
        * `Cannot evaluate parameter 'NewName' because its argument is specified as a script block and there is no input. A script block cannot be evaluated without input.`

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by bobbytreed** [comment]
Closed by #2612
