### ISSUE TITLE
Add database documentation to conformance endpoint

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell-Docs#236]
The conformance endpoint documentation doesn't talk about the reporting database, except to mention that it exists, and the web service reads / writes data to it.

* Where the database runs
* What alternative database services are supported
* What the database schema looks like
* How to connect to the database directly and query it

https://github.com/PowerShell/PowerShell-Docs/issues/40

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ArieHein** [comment]
- The Report Server is a Pull Server that is just not serving configurations and modules.
  so its basically the same mdb file (used to be edb prior to 5.0 RTM, but i think thats a big as well)
  Its mainly used for Push mode, or if you really really dont like the resporting of the nodes done on the
  same db the configuration is being served from.

- None what so ever, this is internal structure that will probaby only be available if DSC and LCM go open source.

- You cant tell but you can query it same as you could in v4 via REST API.

- See previous point

**Comment by eslesar** [comment]
Accessing the database directly is not supported, and won't be documented. Please let us know what functionality you would like to see the reporting REST API support.
