### ISSUE TITLE
Add documentation for scenario where pull server is also the reporting server

### ISSUE THREAD

**Issue by murrahjm** [PowerShell/PowerShell-Docs#237]
Current documentation around v5 pull server uses the example of a report server separate from the pull server.  Given the changes from v4 it would be beneficial to have an example of how to configure a pull server to also be the report server and resource server.

Also, if the pull server URI is the same for the report server, then I suppose there should be something documented for the reporting code. i.e. if you're using a single server you use http://pullserver:8080/PSDSCPullServer.svc, if you're using 2 servers use http://reportserver:8080/PSDSCReportServer.svc.

**Comment by ArieHein** [comment]
Per our conversation with Eric on powershell.org, it depends if a report server block is needed at all on a "single server" model. It if does, then every sample that has a pull server requires all three blocks to start with. I still think, as I commented on the forum, that if you set a configuration web site only, then it also has the mini-role of resource and reporting, else its a waste of "space" and "duplication" in the pull server and the lcm script. If that's not the logic, think it should be reviewed.

As per the example, you don't have to call it PSDSCReportServer.svc, that's basically comes from the endpoint value, so you can name it whatever you want. Its far better, documentation wise to have consistency in the names between examples.

**Comment by murrahjm** [comment]
The current iteration of xDSCWebService makes no connection between the endpoint parameter and the service name in the URI.  But it looks like that whole module needs to be updated for all the v5 changes so it's hard to base any assumptions on that code.

Regardless, if the URI used for the client reporting connection is correct as documented: "http://reportserver:8080/PSDSCReportServer.svc", then the pull server needs to have PSDSCReportServer.svc as a published service.  That means two distinct web services as viewed in IIS.  If that means one configuration block or two, that's up to the implementation of xDSCWebService I suppose.  Kind of a chicken and egg thing between the dsc documentation and that module, but someone needs to go first and outline how it is supposed to work.

**Comment by ArieHein** [comment]
Theres alot of logic you will not find in the documentation as its inside the implementation of the DSCResource code. I had similar issues with xPSSql resource that allows you to configure several aspects of the SQL installation but the Test method only tests installed services and not the full configurable parameters.

Thats why i noted about consistnecy, as i have shown a link on the online documentation that shows PSDSCPullServer.svc as the entry point for the ReportServer. As its a Pull Server, nothing stops you from using PSDSCPullServer.svc  as the entry point for the second server and setting that in the Report block on the LCM/

**Comment by eslesar** [comment]
Addressed with #250
