### ISSUE TITLE
Archive DSC Resource Slow

### ISSUE THREAD

**Issue by suneetnangia** [PowerShell/PowerShell-Docs#238]
Hi Team,
Archive DSC resource seems to be very slow and impact is huge when you are deflating lots of files. Example- I was using it to deflate sitecore zip file which has around 10.5k files (that's not good either but that's a third party) and it took around 3-4 hours to unpack it. 
Is there a way to speed this up? I can imagine this resource is doing a lot more than just unzipping hence more time.

**Comment by DonGill** [comment]
Not sure if this issue was resolved. Capturing in OneView TFS ([46632](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=46632&fullScreen=false&_a=edit)) item.

**Comment by suneetnangia** [comment]
I've not tried this again, is it fixed/changed now?

**Comment by zjalexander** [comment]
@suneetnangia you will probably need to file an issue in https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues . This is the repo for docs issues, so the teams responsible for code performance will not be able to pick this up here.

**Comment by HemantMahawar** [comment]
@eslesar ... Can you explain why this is closed?

**Comment by eslesar** [comment]
As Zack pointed out, this isn't a doc issue.

**Comment by HemantMahawar** [comment]
@suneetnangia  Please open an UserVoice issue https://windowsserver.uservoice.com/forums/301869-powershell
