### ISSUE TITLE
Document ad-hoc script-block arguments for cmdlet / advanced-function authors

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2427]
#2338 asks for the ad-hoc script-block argument feature to be documented for _end users_.

Since cmdlets / advanced functions must be designed with the feature in mind in order to support it, it must be documented from the perspective of cmdlet / advanced-function authors as well.

In short: for a given parameter to support an ad-hoc script-block argument, it must be _pipeline-binding_, which requires decorating it with either the `ValueFromPipeline` or the `ValueFromPipelineByPropertyName` attribute - even if neither functionality is meant to be used _directly_ (if only by-script-block binding is intended).

<sup>Note that introducing a purpose-built `ValueFromPipelineByScriptBlock` attribute was considered but decided against; see https://github.com/PowerShell/PowerShell/issues/6861#issuecomment-388980990
</sup>

Not sure where such documentation is currently maintained.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by bobbytreed** [comment]
Closed by #2612
