### ISSUE TITLE
Unable to send a file on power shell while same is working on postman

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [PowerShell/PowerShell-Docs#2437]
I have a script where I am uploading a excel file and it is giving me error while trying the same on Postman it worked fine for me. Please refer the details below:

Method Type : POST Header : (key)authorization : Value: 09368290_458115d711a30e23 Body : form-data filename : C:\Desktop\Test_Template.xlsx Content-Type : application/vnd.openxmlformats-officedocument.spreadsheetml.sheet Content-Disposition : form-data

The above part is working fine on Postman but while using the following code it is not working

$validatorheaders = New-Object "System.Collections.Generic.Dictionary[[String],[String]]" $validatorheaders.Add("authorization", "09368290_7bdaad3b3761a654") 
$bodyLines = 
   ( 'Content-Disposition: form-data; filename=C:\Desktop\Test_Template.xlsx', 
    'Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' )

$Response=Invoke-Restmethod -Method POST -Uri $ValidatorAPI -Headers $validatorheaders -ContentType "multipart/form-data" -Body $bodyLines -verbose

Please refer the screenshot attached
![body](https://user-images.githubusercontent.com/6301012/40185170-a32f22c6-5a0f-11e8-82fb-a95dc4292a35.PNG)
![header](https://user-images.githubusercontent.com/6301012/40185171-a35956b8-5a0f-11e8-9128-3e8622e7e699.PNG)

**Comment by sdwheeler** [comment]
@SteveL-MSFT @joeyaiello Need help deciding how to handle "support" type questions. Should this be moved to the source repo?

**Comment by doctordns** [comment]
This is a tough call. We ALL want the customers/users to have great experiences and want to help where things don't work as hoped.  But this repo is NOT the place for support issues. If (the royal) we have not explained something well enough or if our explanations do not cover valid use cases, then let's fix that! But where users can't make things work, whether from their own incompetence, due to a bug or otherwise  - well there are other support channels open.

**Comment by SteveL-MSFT** [comment]
This issue should definitely not be in the Docs repo.  If it's an issue with PSCore6, it should be opened on the [PowerShell](https://github.com/powershell/powershell) repo.  If it's an issue with Windows PowerShell, it should be opened on [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell).  @JyotiPrakashMallick can you open this issue in the appropriate place?
