### ISSUE TITLE
Enter-PSSession docs have bad demo link

### ISSUE THREAD

**Issue by JKeithB** [PowerShell/PowerShell-Docs#2439]
Issue Details
-----------------
Enter-PSSession.Md doc contains reference to demo that does not exist

In the Description there is a link to how to set up PowerShell SSH remoting (https://github.com/PowerShell/PowerShell/tree/master/demos/SSHRemoting). This link is currently invalid. 

Version(s) of document impacted
------------------------------
- [X ] Impacts 6.1 document
- [X ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [X ] This issue only shows up in selected version of the document

**Comment by DCtheGeek** [comment]
Closing since #2446 was merged to address.
