### ISSUE TITLE
[6.0] Add-Type does not support the flags given in documentation

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell-Docs#2442]
Issue Details
-----------------

The [Add-Type documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-6) claims that `Add-Type` supports flags like `-CompilerParameters`.

This flag doesn't exist in 6.0 and is replaced with `-CompilerOptions` in 6.1.

There are other parameters that don't exist in `Add-Type` anymore but are still in the documentation. Full sources are:
- [6.0.2 release](https://github.com/PowerShell/PowerShell/blob/36b71ba39e36be3b86854b3551ef9f8e2a1de5cc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs)

The doc also talks about .NET Framework and Windows PowerShell, but should probably refer to .NET Core and PowerShell Core.

Version(s) of document impacted
------------------------------
- [] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@rjmholt Can you create separate issues to fix the v6 content and one to fix the v6.1 changes?

**Comment by alexandair** [comment]
@sdwheeler 
Fixed via #2791. Please, close it.
