### ISSUE TITLE
Where are the (most) up-to-date, complete, and/or correct PowerShell SDK documents?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell-Docs#2510]
Issue Details
-----------------

I discovered in PowerShell/PowerShell#6973 that I have been referring to what seems to be either out-of-date documents or documents that are works in progress.  In particular, [the method reference document for InitialSessionState.Create at docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.initialsessionstate.create?view=pscore-6.0.0) omits the statement

> Overloaded. Creates an InitialSessionState object. The variants of this method can create an InitialSessionState object that is empty, that specifies a snap-in or snap-in collection, and that specifies a snap-in collection and warning exception. This method is introduced in Windows PowerShell 2.0.

found on [msdn.microsoft.com](https://msdn.microsoft.com/en-us/library/system.management.automation.runspaces.initialsessionstate_members(v=vs.85).aspx) and replaces it with

>Creates an empty InitialSessionState object...

The description for Create(String) seems more like a TODO comment:

>Want to get away from SnapIn and console file. Have modules and assemblies instead. Specify the registered SnapIn name or name collection

I was under the impression that docs.microsoft.com had superceded msdn.microsoft.com for such documents.  Indeed the link for the Create() method on msdn.microsoft.com points to docs.microsoft.com.  I'm wondering where to find the most up-to-date, complete, and correct PowerShell SDK documents, respectively.  

I'm fine with digging around in unusual or multiple places to get the information I need, but I'm a bit puzzled by what, exactly, I'm looking at.  Pages at msdn.microsoft.com surfaced by search engines seem to be a good snapshot of something, but with the links mostly pointing to docs.microsoft.com.  docs.microsoft.com seems to contain works in progress.
 

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
We are actively working on the SDK content. Should be published to docs.microsoft.com in July 2018.

Current docs can be found at: 
https://msdn.microsoft.com/en-us/library/dd835506(v=vs.85).aspx(d=robot)

**Comment by wisemoth** [comment]
The example in the OP is still [present](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.initialsessionstate?view=powershellsdk-7.0.0) ...

**Comment by sdwheeler** [comment]
The documentation for the PowerShell .NET API surface is embedded in the source code behind triple-slash (`///`) comments. If documentation needs to be changed, it must be changed there: https://github.com/PowerShell/PowerShell/blob/fd4117e14552b6a8fa0bef6cc3c34bc67d4f8f0e/src/System.Management.Automation/engine/InitialSessionState.cs#L1461-L1466

Please file an issue at https://aka.ms/psfeedback

Eventually, the changes in the source code will flow into the docs website.

**Comment by wisemoth** [comment]
> Eventually, the changes in the source code will flow into the docs website.

I'm confused.  The URI you gave redirects to https://github.com/PowerShell/PowerShell/issues/new/choose

There it seems reasonable to select the item described as "Please open issues on documentation for PowerShell here.".  But that redirects back to this repo.

**Comment by sdwheeler** [comment]
The .NET API documentation does not live in this repository. For the API documentation to be updated it must be changed in the source code first. That is why I linked you to the source repository.
