### ISSUE TITLE
ConvertTo/From-CliXML cmdlet help added to v6 but cmdlets don't exist

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2533]
Issue Details
-----------------
PR #2022 was merged, but the linked PR https://github.com/PowerShell/PowerShell/pull/5815 was never merged and actually closed because of inactivity.
These cmdlets are in the official docs now https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-clixml?view=powershell-6 but don't actually exist:
```
$ ConvertFrom-Clixml
ConvertFrom-Clixml : The term 'ConvertFrom-Clixml' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ConvertFrom-Clixml
+ ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (ConvertFrom-Clixml:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
This is very misleading.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by github-account1111** [comment]
Same with PowerShell 5.1. It's listed in the docs but doesn't exist in the actual language. Gave me false hope.
