### ISSUE TITLE
#Requires -Module or #Requires -Modules

### ISSUE THREAD

**Issue by TheIncorrigible1** [PowerShell/PowerShell-Docs#2542]
Issue Details
-----------------
Tested on Win10 Pro 1803 / PowerShell 5.1.17134.48

The documentation refers to use of `#Requires -Module` in a singular way, but the plural form also works:

    #Requires -Modules ActiveDirectory, BitLocker

I can't confirm it works this way on other versions or platforms, but I was looking for clarification in the documentation on this.  Both forms work whether it's a single module or multiple.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@TheIncorrigible1 Which doc are you referring to? The actual parameter is `-Modules`. As with any parameter you can get away with using only the number of letters required to uniquely identify the parameter. Therefore `-Module` works.

**Comment by sdwheeler** [comment]
@bobbytreed Please fix these files:
- New-ScriptFileInfo
- about_Requires
- PSGet_ScriptCmdlets
