### ISSUE TITLE
Manage RDS certificates using powershell fails after WMF 5.1

### ISSUE THREAD

**Issue by diriver63** [PowerShell/PowerShell-Docs#2552]
Trying to manage Remote Desktop certificates using powershell after installing WMF 5.1 on Windows Server 2012 fails with the following error message:

```powershell

PS C:\Users\MyUser> Import-Module RemoteDesktop
PS C:\Users\MyUser> Set-RDCertificate -Role RDWebAccess


Get-Server : The term 'Get-Server' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RemoteDesktop\Certificate.psm1:304 char:22
+         $webaccess = Get-Server -ConnectionBroker $ConnectionBroker - ...
+                      ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Server:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by sdwheeler** [comment]
You want to use Get-RDServer. See https://docs.microsoft.com/en-us/powershell/module/remotedesktop/Get-RDServer?view=win10-ps

**Comment by sdwheeler** [comment]
@diriver63 This looks like it could be a bug in the RemoteDesktop module. However, you need to make sure you have properly installed the latest version of the module. Also, we don't support that module here. You need to contact the support channels for Windows.

**Comment by diriver63** [comment]
@sdwheeler Thanks for looking into it anyway. I'll make sure to contact the proper channel.
