### ISSUE TITLE
Installing powershell preview builds for mac and linux has changed

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2573]
Issue Details
-----------------

For linux, the change is only for preview build the package name has changed to `powershell-preview`

For mac, the change is to install a preview build you should do the following:

```sh
brew tap caskroom/versions
brew cask install powershell-preview
```

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fix merged

**Comment by sdwheeler** [comment]
@TravisEz13 oops, sorry
