### ISSUE TITLE
Documentation page about_PSReadline incorrectly documents the SelfInsert function

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [PowerShell/PowerShell-Docs#2611]
Issue Details
-----------------
The SelfInsert function documented in [about_PSReadline — Basic Editing](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_psreadline.md#basic-editing) seems to make everything that follow it bold due to some problematic markdown:
```
- SelfInsert  (Cmd: <a>, <b>, ...  Emacs: <a>, <b>, ...)

  Insert the key entered.
```
It is also unsure of what keybindings the function is assigned on both Cmd and Emacs
It renders like this on GitHub:
![selfinsert problematic markdown](https://user-images.githubusercontent.com/32375681/41823608-5cca2ae0-77b7-11e8-8943-a06d072ee43f.PNG)

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fixed
