### ISSUE TITLE
How do I create a PowerShell Core module?

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell-Docs#2633]
I want to create a module (using C#) to offer my users some new PowerShell commands. How do I do this? Please add this information to the documentation.

My searching only found me something from 2013, latest - obviously for non-Core PowerShell, so not applicable in 2018.

**Comment by doctordns** [comment]
You create a PowerShell Core module the same way you create a WIndows PowerShell Module. 

For the basics start here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-6

As for C# - two points.
First, if it were me, I'd try to build things using PowerShell (ie a script module + module manifest). It's faster and easier. If/when you find something that performs badly, _then_ consider using C#. Converting a script module into one using a DLL is pretty easy. Here is one example of C# https://docs.microsoft.com/en-us/powershell/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system

**Comment by sandersaares** [comment]
This wasn't so much a question as a request to actually get some of this documented at https://docs.microsoft.com/en-us/powershell/

I can figure out how to do it but the documentation is very unhelpful and it certainly is not as simple as "the same as PowerShell 5" because even such things as 6.0.1 versus 6.0.2 can cause very unexplainable errors.
