### ISSUE TITLE
Menu items on different pages are not consistent.

### ISSUE THREAD

**Issue by LisandroSu** [PowerShell/PowerShell-Docs#2665]
@sethvs commented on [Wed Apr 18 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14)

When on the 'Удаленное взаимодействие с PowerShell через SSH' page, the left-side menus are identical.

https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6
https://docs.microsoft.com/ru-ru/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6

![01](https://user-images.githubusercontent.com/26186700/38918947-e0c48100-42f7-11e8-8873-314f593c17b3.jpg)

But, for example, on the 'Основные сведения о важных концепциях Windows PowerShell' page, the menus are different.

https://docs.microsoft.com/en-us/powershell/scripting/getting-started/fundamental/understanding-important-windows-powershell-concepts?view=powershell-6
https://docs.microsoft.com/ru-ru/powershell/scripting/getting-started/fundamental/understanding-important-windows-powershell-concepts?view=powershell-6

![02](https://user-images.githubusercontent.com/26186700/38918999-055a52d8-42f8-11e8-8298-a16427e56529.jpg)

Also, in this case, the order of articles in the menus is different.

![03](https://user-images.githubusercontent.com/26186700/38919038-1fabfe7a-42f8-11e8-9dea-f509df7f4db0.jpg)

If you tell me, where in the repo it can be fixed, I would like to contribute to this one.

---

@gosali commented on [Fri Apr 27 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14#issuecomment-385099464)

Hello, @sethvs ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.
 
Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Thu May 03 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14#issuecomment-386430120)

Hi @ishasahni1 
There and inconsistence with the menu in the localized and the en-us version of the page.
Please check this issue.

@Sara-Nicolini

---

@ishasahni1 commented on [Thu May 03 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14#issuecomment-386434046)

Thank you so much @CeciAc for triaging this issue. I am adding @swgupt to loop as she is the PM for this project.

@Sara-Nicolini

---

@CeciAc commented on [Wed May 23 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14#issuecomment-391487105)

Hi @swgupt ,
Did you have the chance to check this?

---

@ishasahni1 commented on [Wed May 23 2018](https://github.com/PowerShell/powerShell-Docs.ru-ru/issues/14#issuecomment-391499965)

@joeyaiello we have received some customer feedback can you kindly look into this.

Thank you for all your help in advance.

@CeciAc FYI

**Comment by LisandroSu** [comment]
Moving this issue from locale repo to ENU repo since it's a source issue.

Thanks

**Comment by DCtheGeek** [comment]
@LisandroSu Can you clarify how it is a source issue if it is rendering correctly on the en-us version?  I'm not 100% sure, but the ru-ru version of the [TOC](https://github.com/PowerShell/powerShell-Docs.ru-ru/blob/live/reference/docs-conceptual/toc.yml) has several lines that the `name:` value has quotes, backslashes, and underscores (such as Line 23, 32, 160, 162, 164, 231).  I'm not sure if that will break the TOC as we are seeing, but worth a look since it isn't consistent.

**Comment by DCtheGeek** [comment]
@LisandroSu Did you get a chance to look at the ru-ru TOC to see if the extra characters are causing the odd rendering of the ru-ru TOC?

**Comment by DCtheGeek** [comment]
Closing due to lack of response and since this is not a source issue (source is rendering correctly).

**Comment by sethvs** [comment]
I think too, that the problem is in ru-ru repo.
Should we reopen PowerShell/PowerShell-Docs.ru-ru#14?

**Comment by DCtheGeek** [comment]
@sethvs I concur, but don't own that repo or explicitly know the process there.  I've now also commented there to re-look at the ru-ru version of the doc per your original issue there.  cc @LisandroSu
