### ISSUE TITLE
PowerShell-Docs/reference/5.1/PSReadline/Set-PSReadlineOption.md incorrect with module version 2.0

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell-Docs#2688]
Issue Details
-----------------

PSReadline V2 makes a breaking change to setting syntax item colors. Thus the document ata https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSReadline/Set-PSReadlineOption.md is no longer correct although the V2 documentation at https://github.com/lzybkr/PSReadLine/blob/master/docs/Set-PSReadLineOption.md IS correct 

I think the only versions that this issue relates to is 5.0 and beyond - but please feel free to correct me on this.

I'm not sure what the best resolution is for this since this issue only arises when you move to PSReadline 2.0.x.x..

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
I think this is only relevant to PS 5 going forward. 
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SteveL-MSFT How are doc updates for PSReadline being managed?

**Comment by doctordns** [comment]
This issue bit me again tonight and I have a specific case where others might have issues. This IS a breaking change.

I am in the Windows Insiders programme and updated to the latest RS5 build (1803-17728.1000). The earlier build was much earlier. With the old OS, I'd successfully updated $Profile to display on the projector better (the grey parameter colour is hard to see on the crap projectors I get lumbered with :-)). The updated OS now uses PSReadLine V 2.0. 

There are not many folks doing this kind of upgrade, and probably even less that customise their PSReadline. But with that said, some folks are going to get bitten.

I am unclear how to version the documentation of this command since it's not actually PS Version related (I'm still using PS V5.1).

**Comment by sdwheeler** [comment]
@doctordns RS5 and PSReadline v2.0 are not officially supported yet. Be sure you leave feedback for PSReadline at https://github.com/lzybkr/PSReadLine/issues.

**Comment by SteveL-MSFT** [comment]
@doctordns as @sdwheeler mentioned, if this is an impactful change, you should open an issue in the PSReadLine repo.  However, we had to take in PSReadLine 2.0 to latest Windows 10 to address an accessibility issue.  So older Windows with Windows PowerShell 5.1 will still have 1.2, but new Win 10 will have 2.0.  Not sure how to doc that other than perhaps have separate docs for PSReadLine independent of the PowerShell version.

**Comment by doctordns** [comment]
Thanks @sdwheeler - I have filed an issue on PSReadLine: https://github.com/lzybkr/PSReadLine/issues/738

@SteveL-MSFT - I have NO problem with the change happening. But it is breaking and is not in the OS release notes. Also, the fix is not easy to discover since bing/google send you to a now-updated page that does not document the right version. As a fast ring pioneer I expect issue like this, but there needs to be some resolution preferably before RS5 release preview hits the slow ring. And I'm not sure how to resolve it either.

It might be nice, in the longer term to enable the platform at docs.microsoft.com to show documentation based both on pwsh versions, but also module version (so in this case the cmdlet at PowerShell 5.1 and PsReadline 1.2, vs Powershell 5.1 and PS Readline 2.0. Given what might be the longevity of Windows PowerShell 5.1 this likely to come up again.

**Comment by SteveL-MSFT** [comment]
@doctordns agree that it would be best to say that PSReadLine was updated to 2.0 in latest Windows and link to the PSReadLine repo rather than duplicate it here

**Comment by doctordns** [comment]
So how about a small note at the top of the page:

Note: this page documents the Set-PSReadLineOption cmdlet that ships with Version 1.2 of the PSReadLine module and was shipped in Powerhell V5, 5.1. In later versions of Windows, for example 5.1.17723, Microsoft ships an updated version of the module. This new versin, version 2.0.0, makes breaking changes in the cmdlet's parameters. For information on the version 2.0 of this cmdlet, see the:  [PSReadLine repo](https://github.com/lzybkr/PSReadLine/blob/master/docs/Set-PSReadLineOption.md)
