### ISSUE TITLE
Expand the `Start-Process` topic to clarify the limitations and use cases on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2690]
On Unix-like platforms (Linux, macOS), `Start-Process` supports only a subset of the features available on Windows, and therefore only a few uses cases make sense.

This information - summarized at https://github.com/PowerShell/PowerShell/issues/4521#issuecomment-324931106 - should be added to the `Start-Process` help topic.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell

**Comment by 1RedOne** [comment]
Created this PR to resolve the issue.

https://github.com/PowerShell/PowerShell-Docs/pull/2989

**Comment by joeyaiello** [comment]
Sweet!

**Comment by mklement0** [comment]
@joeyaiello, can you please reopen this?

Unfortunately, the addition needs amending, as explained [here](https://github.com/PowerShell/PowerShell-Docs/pull/2989#discussion_r222787504).

**Comment by mklement0** [comment]
Never mind: To help this along, I've opened #3013

**Comment by joeyaiello** [comment]
Thanks, sorry about the premature close. Been swinging with a big axe on this doc triage.
