### ISSUE TITLE
Docs should be updated for Ubuntu 17.10 EOL

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell-Docs#2704]
Ubuntu 17.10 reached End of Life.
The supported upgrade path from Ubuntu 17.10 is via Ubuntu 18.04 LTS.

[Related packaging issue](https://github.com/PowerShell/PowerShell/issues/7310).

Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [X] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Need to update both the supportability article and the setup article to reflect the new version.

**Comment by sdwheeler** [comment]
@TravisEz13 Can you update this information?
