### ISSUE TITLE
There really should be an overview topic about installing powershell core

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2706]
There really should be an overview topic about installing PowerShell core.

Having 4 topics without an overview makes it really difficult to link to the setup docs in a generic way.

**Comment by doctordns** [comment]
I agree with the idea of a distro-agnostic overview explaining the basics, without going into distro-specific commands. 

As a Windows guy, that overview would be useful to help me understand better what is needed to get Pwsh working.

**Comment by TravisEz13** [comment]
My idea was a document that linked to the specific platform/distros, but a brief overview I agree would be useful

**Comment by sdwheeler** [comment]
@TravisEz13 @doctordns I am not sure what is being asked for here. Our information architecture discourages landing pages. It seems to me that the information you want here already exists. Copying it to another page just adds another copy that must be maintained.

Can you provide a draft of what you would like to see?

**Comment by TravisEz13** [comment]
basically, I want a landing page or TOC I can point to with just the install pages.

**Comment by TravisEz13** [comment]
@zjalexander @sdwheeler We should discuss where this requirement is coming from offline.
