### ISSUE TITLE
Can we clarify what syntax should be used for variables in paragraphs?

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell-Docs#2711]
[3-STYLE-GUIDE.md](../blob/staging/contributing/3-STYLE-GUIDE.md#formatting-syntax-elements) describes the syntax to use with **cmdlets**, **properties** and **parameters**, but it doesn't clarify what syntax should be used with **variables** in paragraphs.

Now there are several variants in use:
($var)
"$var"
\`$var\`

I believe, for consistency we should choose one of them and use later on.
Which one should we use?

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
The safest option for consistent markdown parsing and rendering is: \`$var\`

**Comment by sdwheeler** [comment]
@sethvs I updated the guide.

**Comment by sethvs** [comment]
Thanks.
