### ISSUE TITLE
Typo in pullServer.md

### ISSUE THREAD

**Issue by tbiles** [PowerShell/PowerShell-Docs#275]
https://github.com/PowerShell/PowerShell-Docs/blob/master/dsc/pullServer.md

Conversely, the **presents** of a ConfigurationID means that the V1 version of the pull server protocol is used and there is no registration processing.

Should read:

Conversely, the **presence** of a ConfigurationID means that the V1 version of the pull server protocol is used and there is no registration processing.

**Comment by HemantMahawar** [comment]
@tbiles Thanks for pointing out. Fixed by @DonGill in #276
