### ISSUE TITLE
Get-ChildItem help topic is missing the FollowSymlink parameter

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#2766]
Issue Details
-----------------
`Get-ChildItem` help topic is missing the **FollowSymlink** parameter.
Also, the **UseTransaction** parameter should be removed. It's not supported in PowerShell Core.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SteveL-MSFT Who can provide a description to Aleksandar for the -FollowSymlink parameter?

**Comment by SteveL-MSFT** [comment]
Basically, if you have a structure like:

```
a
  - b
    - bb1
    - bb2 => c
  - c
    - cc
```

Where bb2 is a symlink to c, then just doing `Get-ChildItem -Recurse b`, it will show bb2 as an item, but not follow it.

However, if you do `Get-ChildItem -Recurse -FollowSymlink b`, it will follow bb2 to c and show the cc item.
