### ISSUE TITLE
New-FileCatalog help is missing

### ISSUE THREAD

**Issue by peetrike** [PowerShell/PowerShell-Docs#2842]
Issue Details
-----------------
The help of New-FileCatalog cmdlet is just a empty generated template.  All the details are missing.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
Closing as a dupe of #652
