### ISSUE TITLE
I need help with powershell script to deploy and install windows patched on remote machin from my standalone machine.

### ISSUE THREAD

**Issue by harsharajsalvi** [PowerShell/PowerShell-Docs#2855]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
This is not the right forum for these kind of questions. Try posting your problem in a community support forum. For a list of community forums see: https://docs.microsoft.com/en-us/powershell/#pivot=main&panel=community
