### ISSUE TITLE
Update about_Classes to talk about class interfaces

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2872]
Issue Details
-----------------
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes

> INTERFACES
> There is no syntax to declare interfaces in PowerShell.

Syntax to declare interfaces was added in PS5. See https://docs.microsoft.com/en-us/powershell/wmf/5.0/class_interface

Need to update this document for v5, v5.1, and v6.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by DCtheGeek** [comment]
Closed by referenced commit.
