### ISSUE TITLE
Add-Content -Force description is not precise

### ISSUE THREAD

**Issue by robdy** [PowerShell/PowerShell-Docs#2877]
Regarding #2864 - I found that description of `-Force` should be improved with the example of when it can be useful (as overwriting read-only parameter of file).

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fixed

**Comment by robdy** [comment]
@sdwheeler - is it? I referenced it as PR was *related* but not even attempting to fix. Unless I'm missing something...

**Comment by sdwheeler** [comment]
@robdy Sorry, I thought your PR was addressing this issue.

**Comment by robdy** [comment]
Looks like that one is already resolved in #2968
