### ISSUE TITLE
Send-MailMessage cmdlet: Delivery Notification parameter return address is From and not To

### ISSUE THREAD

**Issue by ThreeFive-O** [PowerShell/PowerShell-Docs#2880]
Issue Details
-----------------
See comment by Chaitu_a in https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Send-MailMessage?view=powershell-5.1

The delivery notification should be returned to the sender and not the original addressee. Therefore the current explanation of the Delivery Notification parameter in Send-MailMessage cmdlet is explained wrong.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document (No documentation yet)
- [ ] Impacts 6.0 document (No documentation yet)
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by ThreeFive-O** [comment]
@sdwheeler Is it up-for-grabs? I would fix it if you allow.

**Comment by sdwheeler** [comment]
@ThreeFive-O Yes, go for it.
