### ISSUE TITLE
Broken Online Help links

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell-Docs#2900]
I'm not even sure what is the best way to report this but for many of the Microsoft.PowerShell.Utility cmdlets, the links that leads to their web-based help is broken.

Take [Measure-Command](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-command?view=powershell-6) for instance. Issuing a `Get-Help Measure-Command -Online` in PowerShell results in the browser trying to open [http://go.microsoft.com/fwlink/?LinkId=821828](http://go.microsoft.com/fwlink/?LinkId=821828). But this link redirects to a 404 error page. This link is listed in the "online version" field of the following pages:
- https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Measure-Command.md
- https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md
- https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Utility/Measure-Command.md
- https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md

The same problem can also be seen in the case of `Trace-Command`, `Measure-Object`, `Invoke-WebRequest`, `Invoke-Expression`, `Select-Object`, `New-Variable`, and probably a lot more stuff that I didn't test.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [X] Impacts 6.0 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by matt9ucci** [comment]
#2647 is the similar case of `Get-ChildItem` cmdlet.

**Comment by skycommand** [comment]
Uh-oh! I can reproduce that too, on Windows PowerShell 5.1.

And actually, whatever cmdlet I am trying right now, has a broken help link. Including `Get-Help` itself! 😱 (Try `Get-Help Get-Help -Online`.) I tried updating the help system too. But it didn't change anything. (Also `Get-Help Update-Help -Online` leads to a 404.)

Looks like the whole online help system is broken.

**Comment by skycommand** [comment]
... with the "slightly different" part being the "/en-gb/" part.

**Comment by sdwheeler** [comment]
@skycommand Thanks for the report. We are aware of the issues with the Online help links and are working on a massive clean up effort.

**Comment by mklement0** [comment]
To add some more detail on _how_ the links are broken: the _placement of the version component_ is incorrect:

E.g., for `Get-Command` from v5.1:

http://go.microsoft.com/fwlink/?LinkId=821482

redirects to 

https://docs.microsoft.com/en-us/powershell/module/5.1/Microsoft.PowerShell.Core/Get-Command

whereas it _should_ be:

https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Get-Command?view=powershell-5.1

That is, removing `/5.1` from the target URL and appending `?view=powershell-5.1` yields the correct link.

**Comment by sdwheeler** [comment]
We are well aware of how these are broken. There are several layers of redirects that add to the complexity. There are about 43,000 fwlinks to manage. I am working on this.

**Comment by mklement0** [comment]
Good to know that _you_ are aware, @sdwheeler.

Now _others_ are too, which may help them work around the issue while it is being fixed.

**Comment by sdwheeler** [comment]
404 fixed
