### ISSUE TITLE
Install instructions for Kali Linux don't work

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2901]
Issue Details
-----------------
Feedback from LiveFyre on 9/11/2018:

>So "wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb" returns a 404
>
>wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/powershell-6.0.2-x86_64.AppImage returns a 404
>
>Kali 2018-08-21 cant find an installation candidate for libicu55.
>
>The appimage would have been awesome but I cant find that on GitHub any more.
Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
Fixed and merged
