### ISSUE TITLE
Update links in More PowerShell Learning article

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell-Docs#2902]
https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/getting-started/more-powershell-learning.md

Some links are stale or have been redirected to a different location. Need to remove link to Connect (retired) and Script Center. Update stale links.

**Comment by DCtheGeek** [comment]
@sdwheeler 'fix issue #' won't work for the automation, just FYI.  Closing manually. :)
