### ISSUE TITLE
FWLink 135170 points to 404 page

### ISSUE THREAD

**Issue by EdisonDa** [PowerShell/PowerShell-Docs#2925]
Issue Details
-----------------
This is from the customer feedback: https://github.com/MicrosoftDocs/feedback/issues/683

1. In PowerShell Windows, execute "set-executionpolicy -scope CurrentUser" 

2. Copy the link http://go.microsoft.com/fwlink/?LinkID=135170 from the PS window to browser.

It goes to https://docs.microsoft.com/en-us/powershell/module/5.1/Microsoft.PowerShell.Core/about/about_Execution_Policies, 404 page. It should go to  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies. However, if we set the language preference as zh-cn, the FWLink will go to  https://technet.microsoft.com/zh-CN/library/hh847748.aspx.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by iUnknwn** [comment]
The Set-Execution policy documentation page (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6) also has this issue - links to `about_Execution_Policies` will 404.

**Comment by sdwheeler** [comment]
Fixed
