### ISSUE TITLE
PowerShell Cmdlets link on about_Functions_Advanced 404s

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell-Docs#2935]
Looked at the [about_Functions_Advanced page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced?view=powershell-6) and noticed that the link at the bottom called "PowerShell Cmdlets" [is a 404](go.microsoft.com/fwlink/?LinkID=135279)

**Comment by matt9ucci** [comment]
@sdwheeler The link was removed by #3319
