### ISSUE TITLE
SDK docs: incorrect PowerShell.Create() example

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2938]
`Powershell.Create("get-process").Invoke();` 

should be 

`Powershell.Create().AddScript("get-process").Invoke();`

at https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell?view=powershellsdk-1.1.0

As an aside: Clicking `Edit` on the linked page results in a `404`, pointing to nonexistent path underneath `https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet` -  perhaps these links can be disabled while the SDK doc sources aren't yet maintained on GitHub.

**Comment by 1RedOne** [comment]
Believe I found the correct place to update this in the source, which will hopefully update the docs as well.

**Comment by joeyaiello** [comment]
This will get fixed with the next reflection of the docs. Sorry for closing pre-emptive, but we need to clean this up (and it will get reflected)
