### ISSUE TITLE
SecureMof.md needs to be update with  -HashAlgorithm SHA256 in example to create cert

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#298]
New-SelfSignedCertificate -Type DocumentEncryptionCertLegacyCsp -DnsName 'DscEncryptionCert' -HashAlgorithm SHA256

The change is required to be FIPS compliant, not for compatibility with DSC

**Comment by PlagueHO** [comment]
Sure - good point. Are you submitting a PR for this one?

**Comment by eslesar** [comment]
I'll take care of it.

**Comment by eslesar** [comment]
Fixed with #303
