### ISSUE TITLE
Add new Offset and Count parameters to Format-Hex

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell-Docs#2986]
Issue Details
-----------------

Need document new parameters added in https://github.com/PowerShell/PowerShell/pull/7877 

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
Looks like this has already been done.

**Comment by joeyaiello** [comment]
OOF, this is a vNext doc and I can't reflect on the cmdlet with PlatyPS yet because it's not in 6.2.-preview, going to leave it alone for now.
