### ISSUE TITLE
Secure MOF script doesn't work on WIN2012R2

### ISSUE THREAD

**Issue by gigi81** [PowerShell/PowerShell-Docs#300]
Hi,
I was going through the documentation on this page:
https://github.com/PowerShell/PowerShell-Docs/blob/live/dsc/secureMOF.md

I found out that the very first script to generate the certificate does not work unless you use windows 10 or server 2016.

According to this page:
https://technet.microsoft.com/en-us/library/hh848633(v=wps.640).aspx
The -Type parameter is not valid when using the command in WIN2012R2.
I also had to specify the -CertStoreLocation parameter to make the command work. 
This is what I have so far:

```
function CreateDscCertificate
{
    param(
        $pwd,
        $folder
    )

    if(!(Test-Path $folder))
    {
	    New-Item -Path $folder -ItemType Directory
    }

    # note: These steps need to be performed in an Administrator PowerShell session
    $cert = New-SelfSignedCertificate -DnsName 'DscEncryptionCert' -CertStoreLocation cert:\LocalMachine\My

    # export the private key certificate
    $securePwd = ConvertTo-SecureString -String $pwd -Force -AsPlainText
    Export-PfxCertificate -Cert $cert -FilePath "$folder\DscPrivateKey.pfx" -Password $securePwd -Force

    # remove the private key certificate from the node but keep the public key certificate
    Export-Certificate -Cert $cert -FilePath "$folder\DscPublicKey.cer" -Force
    Remove-Item "$folder\DscPrivateKey.pfx" -Force

    Import-Certificate -FilePath "$folder\DscPublicKey.cer" -CertStoreLocation Cert:\LocalMachine\My
}
```
I wonder if the certificate will be valid without specifing the -type parameter...

**Comment by megamorf** [comment]
Your certificate needs both the data and key encipherment  key usage attributes (required for DSC v2). makecert.exe or certreq.exe with a template can be used to generate an encryption certificate as well so you don't have to rely on New-SelfSignedCertificate (see here: https://megamorf.wordpress.com/2016/03/03/using-self-signed-certificates-for-encryption/)

**Comment by PlagueHO** [comment]
@gigi81 - @megamorf is right. The certificate generation needs to have specific EKU's defined, which unfortunately isn't supported on the New-SelfSignedCertificate cmdlet in Windows Server 2012 R2 and Windows 8.1.

MakeCert.exe and CertReq.exe can be used to generate these certificates on that OS. Alternately you can use the New-SelfSignedCertificateEx.ps1 on MS Script Gallery ([here](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6)). I used to use this cmdlet myself (but since Windows 10 have not needed to):
```powershell
    New-SelfsignedCertificateEx `
        -Subject 'CN=SERVER01' `
        -EKU 'Document Encryption','Server Authentication','Client Authentication' `
        -KeyUsage 'DigitalSignature, KeyEncipherment, DataEncipherment' `
        -SAN 'SERVER01' `
        -FriendlyName 'DSC Credential Encryption certificate' `
        -Exportable `
        -StoreLocation 'LocalMachine' `
        -StoreName 'My' `
        -KeyLength 2048 `
        -ProviderName 'Microsoft Enhanced Cryptographic Provider v1.0' `
        -AlgorithmName 'RSA' `
        -SignatureAlgorithm 'SHA256' `
        -ErrorAction Stop
```

I think the documentation does need to at least mention the fact that the older New-SelfSignedCertificate cmdlet does not support DSC v2 credential encryption.

**Comment by PlagueHO** [comment]
@megamorf, I'll submit a PR for an update to this and tag you if you wouldn't mind looking over it as well?

**Comment by megamorf** [comment]
@PlagueHO Sure, sounds good :-)

**Comment by PlagueHO** [comment]
@megamorf  - I submitted the PR already and tagged you in it - but it already got merged! :frowning: Are you able to take a look at the changes? https://github.com/PowerShell/PowerShell-Docs/pull/302

**Comment by megamorf** [comment]
@PlagueHO I just looked at #302 

There are actually too many attributes specified for the encryption procedure and since the certificate's purpose is solely to encrypt credentials we can change KU and EKU from this:

    EKU 'Document Encryption','Server Authentication','Client Authentication' 
    KeyUsage 'DigitalSignature, KeyEncipherment, DataEncipherment' 

to this:

    EKU 'Document Encryption'
    KeyUsage 'KeyEncipherment, DataEncipherment'

**Comment by PlagueHO** [comment]
Excellent work sir. I'll get that changed! I wrote a blog post 8 or 9 months ago bemoaning the lack of documentation on exactly which EKU/KU's were required for DSC v2 - and here you are providing the answer :+1:

**Comment by megamorf** [comment]
Since DSC v2 uses Protect-CmdMessage internally to encrypt the credentials it's bound to have the same requirements as that Cmdlet. My blog article is based on the official MS documentation for Protect-CmsMessage which can be found here: https://technet.microsoft.com/en-us/library/dn807171.aspx

**Comment by PlagueHO** [comment]
@megamorf - ah right. I think I ran into the Protect-CmsMessage info stuff recently. I remember noticing the change to Protect-CmsMessage in one of the early pre-releases of WMF 5.0 but didn't delve to deeply into the certificate requirements - that is some good information to know.

Taking that a step further - should SecureMOF.md actually link to this document and mention that under the covers this is what is being used for credential encryption?
