### ISSUE TITLE
Write-Progress example is incorrect.

### ISSUE THREAD

**Issue by korygill** [PowerShell/PowerShell-Docs#3007]
Issue Details
-----------------
Write-Progress example is incorrect.
Example shows entering a new command, but rather it should be a continuation using backtick/enter.
I have a fix and will submit a PR.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [?] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by robdy** [comment]
Related: #3008
