### ISSUE TITLE
Docs needed for 'Add support for Byte Literals'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3018]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7901

**Comment by matt9ucci** [comment]
@sdwheeler This issue and #2965 are duplicates.

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
