### ISSUE TITLE
Docs needed for 'Add EscapeHandling parameter in ConvertTo-Json cmdlet'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3023]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7775

**Comment by matt9ucci** [comment]
@sdwheeler This issue and #2941 are duplicates.

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
