### ISSUE TITLE
Docs needed for 'Allow numeric Ids and name of registered code pages in '-Encoding' parameters'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3027]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7636

**Comment by sdwheeler** [comment]
This is a duplicate of or related to the following issues:

- #2937
- #2000
