### ISSUE TITLE
Docs needed for 'Get the default PSModulePath at runtime?'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3033]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/7082

**Comment by joeyaiello** [comment]
PSModulePath is crazy, let's build an `about_PSModulePath`

**Comment by fsackur** [comment]
I arrived from https://github.com/PowerShell/PowerShell/issues/7082. I make no assertion of whether or not we should have a separate `about_PSModulePath`, but even if we do, I thought that adding default locations for *Nix to the existing docs was of value.

I'd like to offer https://github.com/PowerShell/PowerShell-Docs/pull/3214
