### ISSUE TITLE
Docs needed for 'Disallow Basic Auth over HTTP on Unix'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3035]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/6787

**Comment by matt9ucci** [comment]
@sdwheeler The issue and #2394 are duplicates and already fixed.
