### ISSUE TITLE
Docs needed for 'Add Password parameter to Get-PfxCertificate cmdlet'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3043]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/6113

**Comment by matt9ucci** [comment]
@sdwheeler The issue is already resolved by #2150 and #2830

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
