### ISSUE TITLE
Docs needed for 'Add Path alias to -FilePath parameters and others for several commands'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3053]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5817

**Comment by matt9ucci** [comment]
@sdwheeler The issue is already resolved by #2148

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
