### ISSUE TITLE
Docs needed for 'Make Travis CI use libcurl+openssl+gssapi for macOS'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3059]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5629

**Comment by TravisEz13** [comment]
dup of #3222
