### ISSUE TITLE
Docs needed for 'Remove DCOM support from *-Computer cmdlets'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3072]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5152

**Comment by sdwheeler** [comment]
PR was closed unmerged. Closing this issue.
