### ISSUE TITLE
Docs needed for 'Remove '-ComputerName' from 'Get/Set/Remove-Service''

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3075]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5094

**Comment by matt9ucci** [comment]
@sdwheeler The issue is already resolved by #1805, #1822, and #2556

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
