### ISSUE TITLE
Docs needed for 'Add NoNewLine switch for Out-String cmdlet'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3077]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5056

**Comment by matt9ucci** [comment]
@sdwheeler The issue is already resolved by #1764

**Comment by sdwheeler** [comment]
@matt9ucci Thanks
