### ISSUE TITLE
Docs needed for 'Add location history for Set-Location to enable 'cd -' scenario (issue #2188)'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3078]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5051

**Comment by matt9ucci** [comment]
@sdwheeler The issue and #2476 are duplicates.
