### ISSUE TITLE
Typo + Suggestions

### ISSUE THREAD

**Issue by FooBartn** [PowerShell/PowerShell-Docs#308]
https://msdn.microsoft.com/en-us/powershell/dsc/pullServer

You use this:
    configuration Sample_xDscWebService

But in the next section you tell the user to call this:
    Sample_xDSCService

Might suggest adding in the option to use "AllowUnencryptedTraffic". Although not recommended, it is a valid configuration.

You also don't specify to run a Start-DscConfiguration command after creating the MOF. Someone creating a pull server for the first time might get confused with the lack of that step.

**Comment by HemantMahawar** [comment]
Thank you @FooBartn for reporting this issue. Fixed with #335
