### ISSUE TITLE
Docs needed for 'Enable tab complete for '-Format' parameter of Get-Date'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3084]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/4835

**Comment by matt9ucci** [comment]
@sdwheeler I think it is meaningless to explain tab completion. The new format (`FileDate`, `FileDateUniversal`, `FileDateTime`, `FileDateTimeUniversal`) and ordinary format like `yyyyMMdd` are fully documented in [Get-Date help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-6)

**Comment by joeyaiello** [comment]
@matt9ucci agreed, closing this.
