### ISSUE TITLE
Out of range configuration

### ISSUE THREAD

**Issue by FooBartn** [PowerShell/PowerShell-Docs#309]
https://msdn.microsoft.com/en-us/powershell/dsc/pullclientconfigid4

The configuration suggests:
RefreshFrequencyMins = 15;

But using that with the latest cmdlets and resources gives you an out of range error. Minimum is 30.

**Comment by DonGill** [comment]
Captured in OneView[ #49190](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=49190&fullScreen=false&_a=edit)

**Comment by eslesar** [comment]
Addressed in #364
