### ISSUE TITLE
Docs needed for 'Added Addtional Validation Attributes'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3096]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/4084

**Comment by joeyaiello** [comment]
These need to be added to [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6)

**Comment by SteveL-MSFT** [comment]
Fixed by https://github.com/PowerShell/PowerShell-Docs/pull/3239
