### ISSUE TITLE
Docs needed for 'Remove BuildVersion from  $PSVersionTable'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3099]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/3877

**Comment by matt9ucci** [comment]
@sdwheeler It would be better to merge the issue and #2229. Both are related to GitCommitId and BuildVersion.

**Comment by sdwheeler** [comment]
Duplicate of #2229
