### ISSUE TITLE
Docs needed for 'Characters taking more than one cell space on buffer, with overlapping text. [Since Creator's Update]'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3103]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/3601

**Comment by matt9ucci** [comment]
@sdwheeler It is not clear why docs are needed. In the [issue comment](https://github.com/PowerShell/PowerShell/issues/3601#issuecomment-295895515), it is said that the issue has nothing to do with PowerShell as follows:
> Based on the repro, I would say this issue has nothing to do with PowerShell.
