### ISSUE TITLE
Docs needed for 'WIP - Implement Get-Hash cmdlet'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3106]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/3395

**Comment by matt9ucci** [comment]
@sdwheeler PowerShell/PowerShell#3395 is already closed and `Get-Hash` cmdlet does not exist in the latest version [v6.2.0-preview.1](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.0-preview.1)
