### ISSUE TITLE
not all TOC top-level items are clickable.

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#311]
https://msdn.microsoft.com/en-us/powershell/dsc/metaconfig - this a top level item with content, that also has content underneath it. if you click Configuring the Local Configuration Manager (LCM) in the TOC, you will go to that page

in contrast, if you try clicking The DSC pull model in the TOC, it will only expand the topic. 

Other TOC items that are clickable without content:
DSC on Linux
DSC MOF Reference
More Resources

semi-related to #21

**Comment by DonGill** [comment]
Captured in OneView [#49189](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=49189&fullScreen=false&_a=edit)

**Comment by eslesar** [comment]
This is by design. We can discuss the merits of this.
