### ISSUE TITLE
enactingconfigurations needs some help

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#312]
1) as reported by MVPs, DSC extension should not be a relevant example for pull mode.
2) I need to tweak the graphics a bit to be more inline with what we use for presentations.

**Comment by DonGill** [comment]
Captured in OneView [#491188](https://github.com/PowerShell/PowerShell-Docs/issues/312)

**Comment by eslesar** [comment]
Addressed in #364
