### ISSUE TITLE
Error 404 in links in README

### ISSUE THREAD

**Issue by CeciAc** [PowerShell/PowerShell-Docs#3149]
@IgorRozani commented on [Fri Oct 19 2018](https://github.com/PowerShell/powerShell-Docs.pt-br/issues/2)

In the section [Contribuindo](https://github.com/PowerShell/powerShell-Docs.pt-br#contribuindo), in the README.md has two links that are not working, they are linking two files that doesn't exist in the project.

![image](https://user-images.githubusercontent.com/802968/47239407-9b246980-d3bb-11e8-8f02-9ca5547f9668.png)

The first link is "guia de contribuições", that refers to a CONTRIBUTING.md that doesn't exist.
The second is "guia de estilo", that refers to a STYLE.md that doesn't exist.

---

@CeciAc commented on [Fri Oct 19 2018](https://github.com/PowerShell/powerShell-Docs.pt-br/issues/2#issuecomment-431507338)

Hello, @IgorRozani

Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by sdwheeler** [comment]
This issue was moved to PowerShell/powerShell-Docs.pt-br#3

**Comment by sdwheeler** [comment]
@CeciAc This issue belongs in the localized repo. The files are missing from the that repo. If you are not going to localize them then then URLs need to point to the files in this repo.
