### ISSUE TITLE
log directory doesn't exist in target VM

### ISSUE THREAD

**Issue by sebastus** [PowerShell/PowerShell-Docs#315]
document: https://github.com/PowerShell/PowerShell-Docs/blob/live/dsc/lnxGettingStarted.md

at the bottom of the page it says a couple of log files are in:

/opt/omi/var/log/

but /opt/omi/var doesn't exist on a Ubuntu system with the extension installed.

**Comment by DonGill** [comment]
Captured in OneView #[49187](Log directory doesn't exist in target VM)

**Comment by juanpablojofre** [comment]
Per OneView #49187 this item is fixed and verified.
