### ISSUE TITLE
Escape Char with Powershell ISE

### ISSUE THREAD

**Issue by rbabruce** [PowerShell/PowerShell-Docs#3151]
Hi Sean,

I am attempting to use the following escape strings in PowerShell ISE to either clear a line or backspace in a White-Host command in PS 5.1 on server 2016

    `r and `b

I have found that these two commands both work when used in the non-ISE version of PowerShell but are totally ignored in ISE.

Any guidance would be appreciated

Robert

**Comment by doctordns** [comment]
It is not clear what you are trying to achieve. That syntax appears not to be PowerShell related. 

Also, r is an alias for invoke-history in PWSH and the ISE 5.1. Not sure if that is the issue.

Can you provide some code as an example of what you are not managing to do?

**Comment by rbabruce** [comment]
Hi Thomas, Thanks for the quick reply.

 

I am attempting to use the `b or `r sequence as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-6

 

if I use the example in that page and issue the command write-host “backup`b`b out” in Powershell (non ISE) you get “back out” as the output as per the example however if you do this in ISE you get “backup out” instead.

 

It would appear that ISE cannot handle these two special characters. From what I can tell all the others such as `t and `n work fine.

 

Thanks

Robert

**Comment by doctordns** [comment]
I see!
Having done more testing - this appears to work fine (as you report) in Windows PowerShell 5.1 as well as PowerShell 6.1, but it does fail in Windows PowerShell ISE 5.1.  It also works great in VSCode with both Windowss PowerShell 5.1 and PowerSHell 6.1.

**Comment by sdwheeler** [comment]
@rbabruce This is not a documentation issue, per se. This is an issue with the implementation of the console host in the ISE. Please open an issue for this at https://github.com/powershell/powershell/issues.
