### ISSUE TITLE
Class based DSC resource

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell-Docs#318]
In New language features in PowerShell 5.0 
https://msdn.microsoft.com/en-us/powershell/wmf/class_newtype

It states:
Four new attributes, DscResource, DscResourceKey, DscResourceMandatory, and DscResourceOut have been added.

In Class-based DSC Resources
https://msdn.microsoft.com/en-us/powershell/wmf/dsc_classbasedresource

The example shows usage of 
DscProperty(Key), DscProperty(Mandatory) and I assume there would have been a
DSCProperty(Out) but its not implemented in the example.

On the same subject, the example also shows usage of DscProperty(NotConfigurable) but theres no mention of it on the first link.

**Comment by HemantMahawar** [comment]
Thank you @ArieHein  for reporting this issue. Fixed with #334
