### ISSUE TITLE
OPS Highlighting doesn't understand block comments

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell-Docs#319]
https://msdn.microsoft.com/en-us/powershell/wmf/dsc_classbasedresource

Line 48 of the main example has an extra ' that breaks the code

**Comment by HemantMahawar** [comment]
Thank you @ArieHein  for reporting this issue. Fixed with #334

**Comment by vors** [comment]
Extra `'` doesn't break the code, it only breaks OPS highlighting for PowerShell.
We should fix the highlighting engine that OPS uses.

**Comment by HemantMahawar** [comment]
@eslesar @DonGill ... can we get the tooling fixed?

**Comment by vors** [comment]
```powershell
<# 
this is block comment 
#>
```

**Comment by eslesar** [comment]
Sent feature request to OPS team.

**Comment by HemantMahawar** [comment]
@eslesar This should remain open till OPS team delivers this feature ... cc @joeyaiello @vors

**Comment by HemantMahawar** [comment]
@saldana Any idea when will this be fixed? ... cc @DonGill @joeyaiello

**Comment by saldana** [comment]
@HemantMahawar, I get a 404 when accessing https://msdn.microsoft.com/en-us/powershell/wmf/dsc_classbasedresource. I am not sure what the issue is or if this has been reported to our team in TFS. What is the bug number?

**Comment by HemantMahawar** [comment]
Content has been moved to https://msdn.microsoft.com/powershell/dsc/authoringresourceclass.
Look at the "complete file" section https://msdn.microsoft.com/powershell/dsc/authoringresourceclass#the-complete-file , specifically in the block comment after `[string] $SourcePath`

**Comment by saldana** [comment]
Thanks. @DonGill, can you guys enter a bug for our team to fix this problem? Thanks.

**Comment by vors** [comment]
cc @sankethka

**Comment by sdwheeler** [comment]
Now that the documentation has been migrated from MSDN to docs.microsoft.com, this is no longer an issue.
