### ISSUE TITLE
-UseCulture description in Import-Csv topic is incorrect

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#3200]
The `Import-Csv` topic currently states:

> The default is based on the culture settings of the Operating System (e.g. en-US culture will return a comma (,) by default).

(Additionally, in the v3 and v4 versions the sentence is missing a few words at the end.)

This is incorrect, as a _fixed_ delimiter is used by default, namely the comma (`,`).

In other words, the behavior is culture-_invariant_, as many other parts of PowerShell are by design.

The other CSV cmdlets already have a correct description; e.g.: `Export-Csv`:

> Indicates that this cmdlet uses the list separator for the current culture as the item delimiter. The default is a comma (,).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by davidsmatlak** [comment]
Resolved in PR #3519
