### ISSUE TITLE
Clarify behavior / docs re Get-Content -Raw -AsByteStream vs. Get-Content -ReadCount 0 -AsByteStream

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#3215]
_Updated to reflect the parameter name change from `-Encoding Byte` to `-AsByteStream` and to correct the docs link._

According to the documentation, the purpose of `Get-Content -Raw` is to [return a _string_](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-Content.md):

  > Ignores newline characters and returns the entire contents of a file in one string with the newlines preserved

By contrast, the purpose of `-AsByteStream` is to return a stream of _bytes_, without any attempt to interpret them as a _string_ (characters).

As currently documented:

* The two parameters _seem_ to be mutually exclusive, but they _can_ be combined (see below).

* The documented way to get the _entire file contents_ as a _single array of bytes_ is to use `-ReadCount 0` with `-AsByteStream`:

> When reading from and writing to binary files, use a value of Byte for the Encoding dynamic parameter and a value of 0 for the ReadCount parameter. A ReadCount value of 0 reads the entire file in a single read operation and converts it into a single object (PSObject).

As an aside: note that `PSObject` is somewhat misleading, because it is an `[System.Object[]]` array that is output as a single object (behind the scenes, that array may be wrapped in `[psobject]`, but that is of no relevance to the end user).

In practice, as of PowerShell Core 6.2.0-preview.1

* `Get-Content -Raw -AsByteStream` - note the _combination_ of `-Raw` and `-AsByteStream` returns a `[System.Byte[]]` array as a _single_ object.

* `Get-Content -ReadCount 0 -AsByteStream` returns a `[System.Object[]]` array as a _single_ object.

Note that `[System.Byte[]]` is actually the more efficient way to return the bytes of the file as a single object, so, arguably, that's what `Get-Content -ReadCount 0 -Encoding Byte` should output too.

Steps to reproduce
------------------

```powershell
'hi' > t.txt

# Based on the current docs, -Raw combined with -Encoding Byte makes no sense.
# Yet, it works, and returns an efficient, strongly typed [System.Byte[]] array.
Get-Content t.txt -Raw -AsByteStream | Measure-Object | % Count
(Get-Content t.txt -Raw -AsByteStream).GetType().Name

'---'

# Based on the current docs, using -ReadCount 0 with -Encoding Byte is the way
# to return all bytes at once, as a single array.
# Returns a [System.Object[]] array.
Get-Content t.txt -ReadCount 0 -AsByteStream | Measure-Object | % Count
(Get-Content t.txt -ReadCount 0 -AsByteStream).GetType().Name
```

Actual behavior
---------------

```powershell
1
Byte[]
---
1
Object[]
```

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1
```

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT , but I had already created https://github.com/PowerShell/PowerShell-Docs/issues/3213

**Comment by SteveL-MSFT** [comment]
In that case, let's close this as dupe.
