### ISSUE TITLE
GUAI Cloud

### ISSUE THREAD

**Issue by Authai2** [PowerShell/PowerShell-Docs#3287]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67036431-e7b3-c919-2c4a-8cff4417b76c
* Version Independent ID: 71f6096f-c636-a668-9278-043c7834e2b4
* Content: [README](https://docs.microsoft.com/en-us/powershell/gallery/readme)
* Content Source: [gallery/readme.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/readme.md)
* Product: **powershell**
* GitHub Login: @sysmith
* Microsoft Alias: [**SydneyhSmith**[](url)]( @UsernameFail )

**Comment by Authai2** [comment]
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <title>Page not found</title>
    
<meta charset='utf-8' />
<meta http-equiv='X-UA-Compatible' content='IE=edge' />
<meta name='msapplication-config' content='none' />
<link rel='icon' type='image/x-icon' href='/Error/favicon.ico' />
<link rel='shortcut icon' type='image/x-icon' href='/Error/favicon.ico' />
<meta name='robots' content='noindex, nofollow' />

    <link rel="stylesheet" property="stylesheet" type="text/css" href="//shell-s2-portal.azurecomcdn.net/Error/Content/Dynamic/HzJ4T04Y25G2.css" />
    
    <link rel="stylesheet" property="stylesheet" type="text/css" href="//shell-s2-portal.azurecomcdn.net/Error/Content/Dynamic/Qb2gODJsDxc5.css" />
</head>
<body class="error-page-wrapper">
    <div class="error-page">
        <div class="error-page-content">
            <h1>Page not found</h1>


                <ul>
                        <li><a class="error-page-content-tryagain" id="error-page-content-tryagain" href="https://portal.azure.com/"><span>Try again</span><img src="//shell-s2-portal.azurecomcdn.net/Error/Content/5.0.302.7501901764.181105-2229/min/Images/MsPortalFx/chevron.svg" alt="" /></a></li>



                    
                        <li><a class="error-page-content-support" href="https://go.microsoft.com/fwLink/?LinkID=733312&amp;clcid=0x9"><span>Contact support</span><img src="//shell-s2-portal.azurecomcdn.net/Error/Content/5.0.302.7501901764.181105-2229/min/Images/MsPortalFx/chevron.svg" alt="" /></a></li>
                </ul>
        </div>
        <img class="error-page-cloud1" src="//shell-s2-portal.azurecomcdn.net/Error/Content/5.0.302.7501901764.181105-2229/min/Images/MsPortalFx/cloud_drop.svg" />
        <img class="error-page-cloud2" src="//shell-s2-portal.azurecomcdn.net/Error/Content/5.0.302.7501901764.181105-2229/min/Images/MsPortalFx/cloud_drop.svg" />
        <img class="error-page-cloud3" src="//shell-s2-portal.azurecomcdn.net/Error/Content/5.0.302.7501901764.181105-2229/min/Images/MsPortalFx/cloud_drop.svg" />
    </div>

**Comment by sdwheeler** [comment]
@Authai2 Is there some problem you are trying report? I don't understand this issue.

**Comment by sdwheeler** [comment]
Fixed redirection. Closing for no response.
