### ISSUE TITLE
-DestinationPath is not a valid parameter

### ISSUE THREAD

**Issue by elexisvenator** [PowerShell/PowerShell-Docs#3303]
The documentation has many references to `-DestinationPath` however this is not an available parameter for this method. I think it should be `-Path` instead.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285e23f9-0c9b-e132-7869-884bf40a54f6
* Version Independent ID: f38114a3-bfc3-733d-acdd-2d98cf0a7721
* Content: [Save-Package (PackageManagement)](https://docs.microsoft.com/en-gb/powershell/module/packagemanagement/save-package?view=powershell-5.0)
* Content Source: [reference/5.0/PackageManagement/Save-Package.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PackageManagement/Save-Package.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixed by #3308
