### ISSUE TITLE
Additional Options

### ISSUE THREAD

**Issue by MaxFun** [PowerShell/PowerShell-Docs#3311]
[Enter feedback here]
It would be nice to have an option(s) to get more information with Get-Service.
For example another column to show startup type (Automatic, Manual, Disabled,..etc) or the first column to show Disable if it is not Running or Stopped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275ee2a1-17e2-9410-eaf8-c330cdb3d31f
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The following works in PSv6: 
```powershell
Get-Service | Select-Object Status,StartType,DelayedAutoStart,Name
```

This example will work in PSv6 or PSv5.1
```powershell
Get-CimInstance win32_service -Filter 'Name = "WSearch"' | Select-Object Name,State,DelayedAutoStart,StartMode
```

**Comment by MaxFun** [comment]
I tried this in version PSVersion 5.1.17134.407 and does not work. All I get is ;

PS C:\Windows\system32> Get-Service | Select-Object Status,StartType,DelayedAutoStart,Name

 Status StartType DelayedAutoStart Name
 ------ --------- ---------------- ----
Stopped  Disabled                  AdobeARMservice
Stopped  Disabled                  AJRouter
Stopped    Manual                  ALG
Stopped    Manual                  AppIDSvc

**Comment by sdwheeler** [comment]
As I said above, DelayedAutoStart is only available in PSv6. You can use the Get-CimInstance example on PSv5.1.

**Comment by MaxFun** [comment]
Sorry, miss read examples
