### ISSUE TITLE
Start-Trace Cmdlet needs documentation

### ISSUE THREAD

**Issue by TimMangan** [PowerShell/PowerShell-Docs#3325]
There is no documentation of this cmdlet, other than to list the parameters.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3ebcca-ffe2-0e5c-266f-51bca8175768
* Version Independent ID: c900267b-97cb-bdd8-10e9-c94e81e71992
* Content: [Start-Trace (PSDiagnostics)](https://docs.microsoft.com/en-us/powershell/module/psdiagnostics/start-trace?view=powershell-6)
* Content Source: [reference/6/PSDiagnostics/Start-Trace.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PSDiagnostics/Start-Trace.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
V6x of PSDiagnostics does not have this cmdlet. Need to remove invalid documents.

```powershell
PS > gcm -Module PSDiagnostics

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Disable-PSTrace                                    6.1.0.0    PSDiagnostics
Function        Enable-PSTrace                                     6.1.0.0    PSDiagnostics
Function        Get-LogProperties                                  6.1.0.0    PSDiagnostics
Function        Set-LogProperties                                  6.1.0.0    PSDiagnostics
```

**Comment by sdwheeler** [comment]
PR #3333 removes the cmdlet help files that do not apply to V6. Still need to fill in descriptions for remaining cmdlets.

**Comment by sdwheeler** [comment]
Filed bug https://github.com/PowerShell/PowerShell/issues/8339 for issue of missing cmdlets.
