### ISSUE TITLE
Link is broken - (How to: Work with release definitions)

### ISSUE THREAD

**Issue by dcuomo** [PowerShell/PowerShell-Docs#3326]
The link pointing to "(How to: Work with release definitions)" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf8bc8d-7efc-bf3a-74b1-5ea1645d799f
* Version Independent ID: 4e0562e4-91c9-f600-b09e-1bc60152bb43
* Content: [Building a Continuous Integration and Continuous Deployment pipeline with DSC](https://docs.microsoft.com/en-us/powershell/dsc/dsccicd#define-the-build)
* Content Source: [dsc/dscCiCd.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dscCiCd.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by bobbytreed** [comment]
Closed by #3545
