### ISSUE TITLE
Incorrect powershell.powerShellExePath in documentation for Windows?

### ISSUE THREAD

**Issue by ronbok** [PowerShell/PowerShell-Docs#3330]
// On Windows:
"powershell.powerShellExePath": "c:/Program Files/PowerShell/&lt;version&gt;/pwsh.exe"

Shouldn't this be:
// On Windows:
"powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\&lt;version&gt;\\pwsh.exe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fced7981-ed27-88e0-6793-cb15636594ff
* Version Independent ID: af2beddd-a57e-fd2b-fd4c-74adf0bd7bf3
* Content: [Using Visual Studio Code for PowerShell Development](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/vscode/using-vscode?view=powershell-6)
* Content Source: [reference/docs-conceptual/core-powershell/vscode/using-vscode.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/vscode/using-vscode.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by ronbok** [comment]
I see GitHub didn't help with the actual syntax here.  Should be double backslashes between each folder.

"powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\6\\pwsh.exe"

**Comment by sdwheeler** [comment]
Both of these work
- "powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\<version>\\pwsh.exe"
- "powershell.powerShellExePath": "c:/Program Files/PowerShell/<version>/pwsh.exe"
