### ISSUE TITLE
More information bad link

### ISSUE THREAD

**Issue by nickbeagley** [PowerShell/PowerShell-Docs#3336]
For more information link in "Running in-process" section is dead. It points to this http://go.microsoft.com/fwlink/?LinkId=261983 which goes to this https://technet.microsoft.com/en-us/library/bb978525 which is not found. A quick google using that subject "How to Run Windows PowerShell Commands in a Workflow" didn't bring up a page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c54c7898-70d7-4655-6820-9147f5ddd7a1
* Version Independent ID: f6e66ff9-eed3-55a6-0597-68fc4194d4a9
* Content: [about_InlineScript](https://docs.microsoft.com/en-us/powershell/module/psworkflow/about/about_inlinescript?view=powershell-5.1&viewFallbackFrom=powershell-6)
* Content Source: [reference/5.1/PSWorkflow/About/about_InlineScript.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSWorkflow/About/about_InlineScript.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by joeyaiello** [comment]
That topic might've been lost to the redirection/migration gods....I also can't seem to find it anywhere. 

Not sure there's much more there there, though.

**Comment by sdwheeler** [comment]
We just need to remove the link.
