### ISSUE TITLE
Minor formatting error

### ISSUE THREAD

**Issue by klang-uofi** [PowerShell/PowerShell-Docs#3338]
In the "Notes" section, there is a stray bullet point which should be attached to the paragraph 

>If the "Turn on Script Execution" group policy is enabled for the computer or user, the user preference is saved, but it is not effective, and PowerShell displays a message explaining the conflict. You cannot use Set-ExecutionPolicy to override a Group Policy, even if the user preference is more restrictive than the policy. 

Instead, it comes after the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff70cc60-7128-d1a8-6fc1-c5a4e7d79a25
* Version Independent ID: 55d48d73-6fc4-29de-4cc1-c02bcb6a13d8
* Content: [Set-ExecutionPolicy (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by klang-uofi** [comment]
Related pull request: #3339

**Comment by sdwheeler** [comment]
Fixed
