### ISSUE TITLE
English choice of words

### ISSUE THREAD

**Issue by compumaster** [PowerShell/PowerShell-Docs#3341]
DSC is a platform that provides declarative and idempotent (repeatable) deployment, configuration and conformance.

Are you preparing for SAT? First known use of conformance: 1606
Also why use: word "idempotent"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62672b65-4257-a3a8-9666-db6c2125cd17
* Version Independent ID: 3a67103e-29cd-35c6-5aca-5a2576472d98
* Content: [Desired State Configuration Overview for Engineers](https://docs.microsoft.com/en-us/powershell/dsc/dscforengineers)
* Content Source: [dsc/DscForEngineers.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/DscForEngineers.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by joeyaiello** [comment]
Idempotent means a very specific thing: that the process is repeatable in a way that does not depend on pre-existing state. It's also a mathematical term, and one that I would expect to be understood (or at least understandable) by the audience for a doc called "DSC for Engineers". 

Unless you're specifically asking us to change "conformance" to "conformity"? It might sound a *little* weird, but again, I think the meaning is pretty clear. 

In the future, feel free to submit PRs without issues for quick fixes like this. Thanks!
