### ISSUE TITLE
PSrepository

### ISSUE THREAD

**Issue by Tarjei99** [PowerShell/PowerShell-Docs#3346]
Hi,

It looks like there is no easy way of finding out how to configure the PSrepository setting for the PowerShell gallery.

This have suddenly become of interest for me since the "update-Module" and "Update-module *" commands give the error message below.

```
PackageManagement\Install-Package : Unable to find repository 'https://www.powershellgallery.com/api/v2'. Use
Get-PSRepository to see all available repositories.
At C:\Program Files\WindowsPowerShell\Modules\powershellget\2.0.3\PSModule.psm1:13024 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27629d2-7baa-8f66-369d-d597d53bb842
* Version Independent ID: 9523376f-b953-a7ec-aa21-3e580c5a4034
* Content: [Get Started with the PowerShell Gallery](https://docs.microsoft.com/en-us/powershell/gallery/getting-started)
* Content Source: [gallery/getting-started.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/getting-started.md)
* Product: **powershell**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by doctordns** [comment]
PowerShell configures the PS gallery as an untrusted repository, by default. Thus you should always be able to get stuff from there, Of course, since it is untrusted, you get a prompt if you try but that's not the issue with the OP.

From the OP's message, it looks like PowerShell is able to use the PSGallery, but with as error says it is unable to find it. That URL should be reachable in order for the PowerShell cmdlets to work against the PowerShell Gallery. I tried it in a browser here and it works fine. 

Given the error message, this issue sounds like a networking problem not a documentation issue.

**Comment by Tarjei99** [comment]
I have checked that there are no spaces. BTW install-module Azure works
fine. The problem occurs when I'm not specifying any module.

PS C:\Windows\system32> Get-PSRepository



Name                      InstallationPolicy   SourceLocation

----                      ------------------   --------------

PSGallery                 Trusted
https://www.powershellgallery.com/api/v2/





PS C:\Windows\system32>

**Comment by doctordns** [comment]
See my earlier comment - the issue is NOT the repository settings - you have the Gallery as trusted so the PowerShell get cmdlets should work fine.

Try doing a tracert to powershellgallery.com.

**Comment by Tarjei99** [comment]
Hi,

When the difference between working and non-working is the presence or
absence of a wildcards, it is not a matter of network connectivity.

And there are a few problems to using traceroute.
     1. Ping does not work. Pinging www.google.com works.
     2. Traceroute go into never-never land.  After hop 15 out of 30 it is
not getting any reply.
      3. Traceroute to www.google.com works. 15 hops.
      4. Browsing the site from the server with the problem works fine.

So, there is no connectivity problem.

Greetings,

**Comment by sdwheeler** [comment]
@Tarjei99 Have you run Update-Help with the -Verbose parameter? It may be failing on a specific module.

If you continue to have problems you should open a support case or try posting your problem in a community support forum.  For a list of community forums see: https://docs.microsoft.com/en-us/powershell/#pivot=main&panel=community
