### ISSUE TITLE
Find the $Env:PSModulePath

### ISSUE THREAD

**Issue by ddkserv** [PowerShell/PowerShell-Docs#3351]
Viewing the PSModulePath variable

If you want to view the PSModulePath variable, you can type the following command:

`echo $Env:PSModulePath`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167cce58-9f50-ff4a-b6d2-72ffef1e506d
* Version Independent ID: 28feb0c7-54f8-1dab-c714-15ad6a8c1192
* Content: [Manual Package Download](https://docs.microsoft.com/en-us/powershell/gallery/how-to/working-with-packages/manual-download)
* Content Source: [gallery/how-to/working-with-packages/manual-download.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/how-to/working-with-packages/manual-download.md)
* Product: **powershell**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by doctordns** [comment]
$env:PSModulePath is not a single path, but a semi-colon delimited set of path strings, only one of which should be the target for the move operation mentioned in the article. To discover the individual paths, you could do this:

```powershell
$env:PSModulePath.Split(''')
```
I have done an update to tis poage, referenced in PR #3354

**Comment by sdwheeler** [comment]
Fixed in #3354
