### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by anilkugupta** [PowerShell/PowerShell-Docs#3353]
Duplicate line: "This section provides a tutorial for creating the Select-Str cmdlet, which is very similar to the Select-String cmdlet provided by Windows PowerShell. This tutorial provides fragments of code that illustrate how cmdlets are implemented, and an explanation of the code."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3071592a-079d-50be-d509-23afe3aa01ca
* Version Independent ID: 01db9471-cf47-4568-0cf4-f0f759d6a73f
* Content: [SelectStr Tutorial](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/selectstr-tutorial)
* Content Source: [developer/cmdlet/selectstr-tutorial.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/developer/cmdlet/selectstr-tutorial.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixed in #3361
