### ISSUE TITLE
Expand-Archive doc errors and missing content

### ISSUE THREAD

**Issue by joel0** [PowerShell/PowerShell-Docs#3369]
-DestinationPath is in the "Optional Parameters" section, but says 'This parameter is required."

-PassThru's description is "{{Fill PassThru Description}}".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b551b9cd-f608-082f-7cbd-a98e417f2c9a
* Version Independent ID: 0a5e7f63-6363-af13-a2ca-79190f459d40
* Content: [Expand-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixing the missing content for `-PassThru`. The `-DestinationPath` issue is a bit strange. By definition, it is not a mandatory parameter but is it not allowed to be empty or null. So that is a code bug.

```powershell
 (mandatory=$false,
  Position=1,
 ValueFromPipeline=$false,
 ValueFromPipelineByPropertyName=$false)]
 [ValidateNotNullOrEmpty()]
 [string] $DestinationPath,
```

**Comment by sdwheeler** [comment]
See related https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/67
