### ISSUE TITLE
version 6 docs are the default

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell-Docs#3395]
I would make version 5.1 docs the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912d2353-a0a9-49e7-d750-639d0fa757bb
* Version Independent ID: dff1f69c-82c5-68dc-663d-f459f7c79cf3
* Content: [Where-Object (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/Where-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Where-Object.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Thanks for your input. The PowerShell team specifically chose to display the most current version of the documentation when no version selector is included in the URL. You can specifically choose the version you want by adding `?view=powershell-5.1` to the end of the URL.

**Comment by jszabo98** [comment]
I disagree.  Powershell 6 has a lot less cmdlets, and does not come with Windows 10.  It is unlikely that a user would be using PS 6.

**Comment by sdwheeler** [comment]
@jszabo98 I don't disagree with your point but that is the decision of the product team. If we get enough upvotes on this issue they may consider changing.

**Comment by doctordns** [comment]
PowerShell 6.x has, TODAY, fewer cmdlets, but the velocity on that is quite amazing. The cmdlet gap is not going to last long. So I think that a policy of always show the latest version by default is the right approach long term.
