### ISSUE TITLE
ModuleName in example 3 is not valid parameter

### ISSUE THREAD

**Issue by ashishrajsrivastava** [PowerShell/PowerShell-Docs#3397]
When i am trying to create manifest including this parameter in hashtable, it fails with fowllowing error.

New-ModuleManifest : A parameter cannot be found that matches parameter name 'ModuleName'.
At line:8 char:20
+ New-ModuleManifest @manifest
+                    ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ModuleManifest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.NewModuleManifestCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bd790b-bf5c-d32d-7832-948a60fe7384
* Version Independent ID: 8a82c347-8653-4cbd-232f-d5018bf76de9
* Content: [New-ModuleManifest (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
This is to be expected since ModuleName is _not_ a parameter on the cmdlet.

You can use `Get-Help` to view the actual parameters.

This is not a product or documentation bug.

**Comment by ashishrajsrivastava** [comment]
got it, its been created for required module in the example.
