### ISSUE TITLE
ConvertFrom-Csv Discards Headerless Column Data

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell-Docs#3401]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document
- [x] Those were the only PowerShell versions that were tested against

# Documentation Issue

The [PowerShell documentation for `ConvertFrom-Csv`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-csv?view=powershell-6) for the optional parameter `-Header` states:

"_If you enter fewer column headers than there are columns, the remaining columns will have no headers_"

Since the `ConvertFrom-Csv` function appears to convert csv rows to `PSCustomObjects`, this implies that the data is available via some function. However, the data appears to have been discarded. In other words, the documentation should state:

"_If you enter fewer column headers than there are columns, the data for the remaining columns is discarded_".

# Steps to reproduce

```powershell
$csv = $(Write-Output "a,b,c`nd,e,f`ng,h,i" | ConvertFrom-Csv -Header 1)

# The additional columns do not appear to be accessible because only the identified columns are displayed
$csv
$csv.''
$csv | Get-Member
$csv | Select-Object '*'
```

If headerless columns can be accessed, then the following code should not produce an error:

```powershell

Write-Output "a,b,c`nd,e,f`ng,h,i" | ConvertFrom-Csv -Header @()
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Linux 4.14.83-1-MANJARO #1 SMP PREEMPT Fri No...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value                                                                                 
----                           -----                                                                                 
PSVersion                      5.1.17763.134                                                                         
PSEdition                      Desktop                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                               
BuildVersion                   10.0.17763.134                                                                        
CLRVersion                     4.0.30319.42000                                                                       
WSManStackVersion              3.0                                                                                   
PSRemotingProtocolVersion      2.3                                                                                   
SerializationVersion           1.1.0.1
```

**Comment by daxian-dbw** [comment]
Closed via #3430
