### ISSUE TITLE
Update while module is running

### ISSUE THREAD

**Issue by c-don** [PowerShell/PowerShell-Docs#3419]
What would happen if the module that I am trying to update is currently running?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6914d3a1-a1d6-11e9-04a0-f40e1bc61194
* Version Independent ID: da21d631-936e-8754-a4ba-6932276efd8f
* Content: [Update-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Update-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Update-Module.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Update-Module does not overwrite the existing module. It installs a new version (side-by-side). It may complain that existing cmdlets already exist. You may need to add the -AllowClobber and -Force parameters.
