### ISSUE TITLE
Where is the documentation for the DSC resources?

### ISSUE THREAD

**Issue by ethanbergstrom** [PowerShell/PowerShell-Docs#3441]
Where did the documentation for the individual resources go? All the Google searches lead be back to this page, which is not helpful when I'm looking for documentation for a specific resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29763d17-3360-db3f-47a8-784b8867e8c3
* Version Independent ID: d111af80-8688-5f20-461b-1c08c87db291
* Content: [DSC Resources](https://docs.microsoft.com/en-us/powershell/dsc/resources/resources#feedback)
* Content Source: [dsc/resources/resources.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/resources/resources.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by GuillaumeCR** [comment]
#3453

**Comment by thetrav** [comment]
https://www.powershellgallery.com/packages?q=Tags%3A%22DSCResourceKit%22 ?

**Comment by bobbytreed** [comment]
I removed the documentation pages for individual resources. Resource documentation is contained in the supporting module, in this case PSDesiredStateConfiguration. Each page had only the schema and an example.  The referenced page: https://docs.microsoft.com/en-us/powershell/dsc/resources/resources shows how to retrieve the schema using Get-DSCResource.

Please let me know if you need further assistance

**Comment by migrande** [comment]
I don't feel like this is an adequate replacement.  The previously included pages had descriptions of each option within the resource.  However, the Get-DscResource -Syntax command does not include these.  This makes it considerably more difficult to understand how to use resources that you aren't familiar with.

Additionally, the main PowerShell cmdlets (not just DSC - PowerShell in general) have full help available both online and through the Get-Help command locally.  I think it would make sense to have the same approach for official DSC resources as well.

**Comment by doctordns** [comment]
while I am not sure docs.microsoft.com should document ALL DSC resources, the ones shipped in the box really should be documented here.

**Comment by sdwheeler** [comment]
@ethanbergstrom These have been restored. They are in the reference section of the TOC.

**Comment by ethanbergstrom** [comment]
Great news! Thanks for considering this, guys!

**Comment by doctordns** [comment]
Thanks @sdwheeler !!

**Comment by jsmartbnl** [comment]
Thanks!
