### ISSUE TITLE
What about exit codes?

### ISSUE THREAD

**Issue by dasjestyr** [PowerShell/PowerShell-Docs#3444]
Is it possible to trap a non-zero exit code? This seems to be more like a `finally` block in a try/catch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7dea14-ae5b-68c5-9a11-9dc4c2d7d174
* Version Independent ID: 780bf958-3add-6a30-d5b9-ea2ed719e0b5
* Content: [about_Trap](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Trap.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Trap.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Exit codes are not terminating errors so Trap will not work in this case. You could have your script check for the exit code and then use `Throw` to cause a custom error condition that gets trapped.
