### ISSUE TITLE
PS script files in PSModulePath

### ISSUE THREAD

**Issue by c-don** [PowerShell/PowerShell-Docs#3447]
What would happen if I were to save PowerShell script in this folder path instead of modules. Would I be able to call the scripts just like the modules. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf80b2e9-5397-5b7c-6ac2-0549365ecdfe
* Version Independent ID: e1370dd6-40fd-7c99-e145-b687d0b381f1
* Content: [Modifying the PSModulePath Installation Path](https://docs.microsoft.com/en-us/powershell/developer/module/modifying-the-psmodulepath-installation-path)
* Content Source: [developer/module/modifying-the-psmodulepath-installation-path.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/developer/module/modifying-the-psmodulepath-installation-path.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
PSModulePath is a collection of paths that PowerShell searches to find modules to load. This is not an execution path variable. The PATH environment variable is the collection of paths that will be searched for any executable file (exe, cmd, ps1, etc.).

**Comment by doctordns** [comment]
To answer the OP's question, you can save and explicitly import a module from pretty much anywhere. But PowerShell's module auto-load feature only works if you put the modules below one of the paths in $Env:PSModulePath.
