### ISSUE TITLE
Broken format: DisplayError and ShowError parameter

### ISSUE THREAD

**Issue by matt9ucci** [PowerShell/PowerShell-Docs#3451]
Issue Details
-----------------
The following cmdlets' **DisplayError** and **ShowError** parameter formatting are broken:
* [Format-Custom](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-custom)
* [Format-List](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-list)
* [Format-Table](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-table)
* [Format-Wide](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-wide)

The cause of this issue may be not manual editing but automatic editing by `Update-MarkdownHelp` cmdlet of platyPS (see the commit ["ran Update-MarkdownHelp on v5.1 and v6 cmdlets"](https://github.com/PowerShell/PowerShell-Docs/commit/670ec6edf4532e10fc199f46e188cc76f2348165))

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@matt9ucci I fixed the markdown errors but there is still a problem in rendering to the web page. I have filed a bug with our engineering team to address the rendering issue.
