### ISSUE TITLE
Additional example comparing Flags would be useful

### ISSUE THREAD

**Issue by zew1me** [PowerShell/PowerShell-Docs#3455]
I am confused on the syntax for checking if a Flag value is present in an enum variable instance. There seems to be no documentation for this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc90069-8eba-1028-424f-faa66ac3bd88
* Version Independent ID: 9a97eb4f-290b-8f89-3638-a7efe36bf1ed
* Content: [about_Enum](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_enum?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Enum.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Enum.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Use the binary comparison operator `-band` to test if a specific flag is set. For example:

PS > ($file2 -band [FileAttributes]::Device) -eq [FileAttributes]::Device
True

PS > ($file2 -band [FileAttributes]::Archive) -eq [FileAttributes]::Archive
False
