### ISSUE TITLE
Document new `UseMinimalHeader` switch parameter for `Start-Transcript`

### ISSUE THREAD

**Issue by lukexjeremy** [PowerShell/PowerShell-Docs#3457]
Issue Details
-----------------
https://github.com/PowerShell/PowerShell/pull/8402 adds the new `UseMinimalHeader` switch parameter to `Start-Transcript`.

I'd like to update the [Start-Transcript docs](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Host/Start-Transcript.md) accordingly.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@lukexjeremy Feel free to submit updates to the docs. Target the PR at the release-62 branch.
