### ISSUE TITLE
Size limits?

### ISSUE THREAD

**Issue by vuzzlevuzz** [PowerShell/PowerShell-Docs#3461]
Is there a hard limit on the size of content that can be decrypted?
I have it working fine with smaller files but during testing with a 400MB file I get an error message:

```
Unprotect-CmsMessage : ASN1 value too large.
+ ... ******** | Unprotect-CmsMessage -To cn=********
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Unprotect-CmsMessage], CryptographicException
    + FullyQualifiedErrorId : System.Security.Cryptography.CryptographicException,Microsoft.PowerShell.Commands.UnprotectCmsMessageCommand
```
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8332b19-7b93-5820-5b0a-37f274a6c3eb
* Version Independent ID: 74ad2f8c-515a-11bd-4420-c19536bd6e85
* Content: [Unprotect-CmsMessage (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.security/unprotect-cmsmessage?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Can you answer this or move this to the PowerShell repo?

**Comment by vuzzlevuzz** [comment]
@SteveL-MSFT thanks.  So, realistically I need to split the files into no more than 60MB chunks before encrypting (to allow for the size increase from BASE64 encoding)

Are there any plans to update to support the streaming option in the crypto API?

**Comment by SteveL-MSFT** [comment]
@vuzzlevuzz no immediate plans, there's too much other work happening right now
