### ISSUE TITLE
Ubuntu 18.04 installation by package repository instructions don't work

### ISSUE THREAD

**Issue by byroniac** [PowerShell/PowerShell-Docs#3466]
Long story short, I decided to reinstall Ubuntu 18.04. The installation by package repository instructions don't work for me. It might be because I had already done the setup for Visual Studio Code and Insiders version, and the one for DotNet. I had to add a microsoft.list file to my /etc/apt/sources.list.d/ with the contents below before I could find and install the "powershell" package:
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e6e46-1221-3123-d750-0803e2f08195
* Version Independent ID: 94bd5a5b-a984-7edf-50bd-9f4dc1a020ef
* Content: [Installing PowerShell Core on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by joeyaiello** [comment]
```sh
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
```

These lines from the install instructions should be putting that line in your `/etc/apt/sources.list.d` via package install. I just cracked it open and it's exactly the same as you what you pasted.

Is it possible you picked up the wrong repo package? 

Either way, if you're still hitting issues on a clean build, file an issue at https://github.com/powershell/powershell that install is broken (because the instructions are accurate).

**Comment by byroniac** [comment]
Thank you. Yes, it's very possible. And now that I look back on it, that may be what happened, is that I picked up the wrong package. I had already used wget for another Microsoft package, named the exact same thing, and when I ran wget again, it most likely downloaded the new package of the same name and appended a numeric suffix to it. However, wget didn't tell me that this happened, and apparently doesn't because of the -q (quiet) flag. So then I just tried to install the same package I had before. Another long story as I'm not on 18.04 any more, but decided to upgrade to 18.10, and was doing multiple wget commands that produced the scenario I described above. Speaking of which, I'm going to try wget https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb because that actually worked for a wget pull.

**Comment by byroniac** [comment]
And for whatever it's worth, I'm having the same problem on 18.10 now, after having installed visual studio code and code-insiders, and dotnet, that the package I download does not add the Microsoft repository to my apt sources, so I have to add it manually. No biggie, but I wonder why it is failing? The only thing I can figure is that packages-microsoft-prod is already registered in the apt system, so it essentially doesn't do anything. I'm just guessing. Or there is something on my system causing this fluke, which unfortunately, I seem to have a history of doing.
