### ISSUE TITLE
Documentation on Format-Hex needs to state the system requirements: Windows PowerShell 5.0

### ISSUE THREAD

**Issue by electrosonics** [PowerShell/PowerShell-Docs#3467]
The documentation on Format-Hex [https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-6](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-6) needs to state the system requirements: Windows PowerShell 5.0

**Comment by doctordns** [comment]
The actual requirement is Windows PowerShell 5.0 and later and PowerShell 6 and later.

At present, this cmdlet is (correctly) documented only in the 5.0, 6.1 and 6.x docs tree. 

I suppose you could put a note into the three relevant branches to the effect of 'this cmdlet added at Windows PowerShell 5 and is included, with some improvements, in PowerShell 6 and later.

**Comment by sdwheeler** [comment]
Note that the documentation for Format-Hex only exists for v5.0/v5.1/v6.
