### ISSUE TITLE
-Name parameter accepts wildcard characters

### ISSUE THREAD

**Issue by angrrybird** [PowerShell/PowerShell-Docs#3468]
According to the documentation, the -Name parameter does not accept wildcard characters. This is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29679244-4e08-c943-63cb-5d1d4c65e527
* Version Independent ID: 1e7502af-2936-848d-dd88-a4a593eddd80
* Content: [Restart-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Restart-Service?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Restart-Service.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Restart-Service.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
I think the PR #3469 should fix this issue.
