### ISSUE TITLE
Where is the download pdf button for the documentation?

### ISSUE THREAD

**Issue by user135711** [PowerShell/PowerShell-Docs#3476]
I want to convert all the documentation for powershell to a pdf for offline viewing like other [Ms docs sites](https://docs.microsoft.com/en-us/aspnet/core/opbuildpdf/group1-dest/toc.pdf?view=aspnetcore-2.2&branch=live). How do I do that?

**Comment by doctordns** [comment]
This feature (docs to PDF) would be most useful across the entire documentation corpus. 

To do this properly might require some platform improvements. For example, if I update a document, the platform needs to ensure that any related PDFs should be updated.  That could involve a longer build process but it would be nice.

**Comment by sdwheeler** [comment]
This is a configuration setting. PDF generation is not enabled for this docset. This is by design. We may consider enabling it in the future.

**Comment by bmsrrb** [comment]
> This is a configuration setting. PDF generation is not enabled for this docset. This is by design. We may consider enabling it in the future.

It would be really nice if you consider this by now.

**Comment by sdwheeler** [comment]
@bmsrrb The `Download PDF` button has been on the bottom of the left-nav column for a couple of years.

**Comment by bmsrrb** [comment]
> [@bmsrrb](https://github.com/bmsrrb) The `Download PDF` button has been on the bottom of the left-nav column for a couple of years.

oh my bad. I was on mobile browser, and the the TOC is inside a menu.
