### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by crg91** [PowerShell/PowerShell-Docs#3479]
Windows PowerShell Desired State Configuration Overview redirects to https://docs.microsoft.com/en-us/powershell/module/PSDesiredStateConfiguration/Remove-DscConfigurationDocument?view=powershell-4.0 which is not what one would expect. Instead it should redirect to https://docs.microsoft.com/en-us/powershell/dsc/overview/overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce403961-c2f1-329c-81de-4cd512d08eb9
* Version Independent ID: 3f6c29ba-cced-2fd0-d34a-380b03dfb635
* Content: [Start-DscConfiguration (PSDesiredStateConfiguration)](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration?view=powershell-5.1)
* Content Source: [reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
I've no updated all three documents, and fixed another issue on the page. 
Thanks for the prod!
