### ISSUE TITLE
Splitting Classes into Multiple Files

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell-Docs#3482]
The following additional content should be added:

It is possible to define class-based resources outside the default .psm1 file, if you want to separate out the organization.

Make a new folder (e.g. DSCResources) and define each new class as a separate .psm1 file. Then, in your root .psd1 file, add the path to the files to the NestedModules parameter.

For example:
MyNewDSCResource.psm1
MyNewDSCResource.psd1
DSCResources\MyNewDSCResource2.psm1

In MyNewDSCResource.psd1:
NestedModules = @('DSCResources\MyNewDSCResource2.psm1')

Note that the additional nestedmodules files can also be .ps1 files, they don't have to be .psm1, though that is typical convention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80f32ca-1b29-029a-65ec-cf929a8e0dbe
* Version Independent ID: 5b1916fa-7d45-f28c-c735-ecfe3743b3a1
* Content: [Writing a custom DSC resource with PowerShell classes](https://docs.microsoft.com/en-us/powershell/dsc/resources/authoringresourceclass)
* Content Source: [dsc/resources/authoringResourceClass.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/resources/authoringResourceClass.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by bobbytreed** [comment]
Closed by #3544

**Comment by shep1987** [comment]
The PR Doesn't mention

NestedModules = @('DSCResources\MyNewDSCResource2.psm1')

So you setup the folder structure then it doesn't work...

**Comment by bobbytreed** [comment]
The multiple class example was not meant to apply to the walkthrough example.  I moved it to the bottom and added a note about the NestedModules. The order that the content was in could have confused someone trying to follow it step by step. 

Thanks
