### ISSUE TITLE
Invalid certificate for "Learn it now before it's an emergency" links

### ISSUE THREAD

**Issue by alexliew** [PowerShell/PowerShell-Docs#3484]
The links in the section "Learn it now before it's an emergency" (https://docs.microsoft.com/en-us/powershell/scripting/learn/more-powershell-learning?view=powershell-6#learn-it-now-before-its-an-emergency) are raising NET::ERR_CERT_COMMON_NAME_INVALID errors in Chrome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c74737d3-06fb-ab7f-9bea-4188e64631fe
* Version Independent ID: 1cf2d970-2d8d-1651-63a3-134217178c15
* Content: [More PowerShell learning](https://docs.microsoft.com/en-us/powershell/scripting/learn/more-powershell-learning?view=powershell-6#learn-it-now-before-its-an-emergency)
* Content Source: [reference/docs-conceptual/learn/more-powershell-learning.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/more-powershell-learning.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by Speertje** [comment]
If you continue anyway, there is nothing there (anymore).

**Comment by sdwheeler** [comment]
I am not able to reproduce the problem. Can you provide a screenshot of the certificate that Chrome is erroring on?

**Comment by doctordns** [comment]
I can repo this issue from Europe.
See: https://pasteboard.co/HUM6nrO.png

**Comment by sdwheeler** [comment]
Looks like these videos are no longer available.
