### ISSUE TITLE
add anchors in doc text

### ISSUE THREAD

**Issue by qt3m45su0najc7** [PowerShell/PowerShell-Docs#3486]
This doc doesn't follow the usual format of having anchors to sections in the doc (usually Examples is an anchor).  Would be nice to have them.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9135e0f5-b31e-081d-c1b9-cb9a8f6f86b0
* Version Independent ID: d91abfb0-b3b9-39e7-5e48-9cb00cdf286c
* Content: [about_Classes](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/about/about_classes_and_dsc?view=powershell-6)
* Content Source: [reference/6/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The whole article is in a code block. The markdown needs reformatting.

**Comment by sdwheeler** [comment]
fixed in #3533
