### ISSUE TITLE
Create PowerShell-Docs room for this repo on gitter.im

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell-Docs#3504]
Create a chat room for PowerShell-Docs community on https://gitter.im for this repository.

**Comment by doctordns** [comment]
An interesting idea. For the OP: What would the purpose of such a room be?  What value does Gitter.Im bring to the table that is not already here (in terms of issue tracking and conversation, etc).   

As a contributor here, I am not sure what added value such a chat room would bring - but I can see some value. I am just not sure I see a big enough hole in the current offerings.

Perhaps the OP should explain what he believes is lacking here that a chat room is the answer to?

**Comment by joeyaiello** [comment]
Also curious about the purpose. I think ideally most of that should be happening in the [existing Gitter channel and PowerShell Slack channel for PowerShell/PowerShell](https://github.com/powershell/powershell#chat-room).

Creating too many rooms just splits hairs and leaves people unsatisfied when they don't get a response.
