### ISSUE TITLE
Explain that the $Matches Automatic Variable is an Array

### ISSUE THREAD

**Issue by JediSQL** [PowerShell/PowerShell-Docs#3509]
For "The match operators (-match and -notmatch)," the description should explain that the $Matches automatic variable is an array and how RegEx "Grouping Constructs" (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#grouping-constructs) add elements to the $Matches array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41417680-da77-6c19-bbd0-522e694e7ff0
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
I just checked, $matches, following a Regex -MATCH updates $Matches, however it is NOT an array that is returned, but a hashtable. As follows:

```powershell
PS [C:\foo> ]> $matches = 1
PS [C:\foo> ]> $matches.gettype().fullname
System.Int32
PS [C:\foo> ]> "xxx" -match'x
True
PS [C:\foo> ]> $matches.gettype().fullname                                                                              System.Collections.Hashtable
```
As you can see, although I set $matches to be an Int32, a successful -match returns a System.Collections.Hashtable, not an array.

**Comment by mklement0** [comment]
Indeed, @doctordns.

Specifically, it's a hashtable rather than an array is in order to also support _named_ capture groups.

**Comment by JediSQL** [comment]
OK, hashtable-vs-array point taken. Please update the documentation to explain that the $Matches automatic variable is an **_hashtable_** and how RegEx "Grouping Constructs" add elements to the $Matches **_hashtable_**.
