### ISSUE TITLE
Should Include a "Grouping Constructs" Topic.

### ISSUE THREAD

**Issue by JediSQL** [PowerShell/PowerShell-Docs#3510]
The match operators (-match and -notmatch) (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6) make use of "Grouping Constructs" (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#grouping-constructs) add elements to the $Matches array. This page should describe grouping constructs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1473a9-d19e-26f6-6a90-13d802f0ed35
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@joeyaiello @SteveL-MSFT How far do we want to go documenting regex behavior? There would be a lot of duplication from the .NET docs.

**Comment by JediSQL** [comment]
I don't think a lot is necessary. Just some basic stuff about how they are implicitly numbered and the relationship to -match. Put a "more details" cross reference link to the .NET docs. Without some reference to grouping, the $Matches array is not properly documented.

**Comment by joeyaiello** [comment]
Yeah, I think a very thin explanation with a link out to .NET docs is probably the right approach here.

**Comment by JediSQL** [comment]
Looks good. Very helpful.

Just one thing, at the end, in "For more information, see Grouping Constructs in Regular Expressions." the link is broken.

**Comment by JediSQL** [comment]
Hi. I was cleaning up some old email and found the link to this topic. I just checked the "About Comparison Operators" page [https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1&viewFallbackFrom=powershell-6](url) It still uses the term "capture groups" without explanation or a link to an explanation (other than a not particularly obvious "See Also... about_Regular_Expressions" link.
