### ISSUE TITLE
Credential description

### ISSUE THREAD

**Issue by NicolaiH** [PowerShell/PowerShell-Docs#3521]
The description 'Specifies a user account that has permission to perform this action' for the credential parameter could be better. In my opinion it has nothing to do with permissions. It is for specifying the 'run as'-credentials for the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6224289-4f97-c150-853a-e015074bbfd7
* Version Independent ID: 4c55287b-3830-69b1-3eb7-33824b6181db
* Content: [New-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/New-Service.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/New-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@NicolaiH Thanks, you are correct.
