### ISSUE TITLE
Microsoft.Powershell.Scheduledjob link broken

### ISSUE THREAD

**Issue by bladeoflight16** [PowerShell/PowerShell-Docs#3534]
On this page ("Scheduling Jobs with the Windows PowerShell API"), there's a link to a `Microsoft.Powershell.Scheduledjob` namespace, but the link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbbe17d4-acdb-ff44-f467-e69d6eecb25a
* Version Independent ID: 522593d2-0871-0b06-0884-57905a419775
* Content: [Scheduling Jobs with the Windows PowerShell API](https://docs.microsoft.com/en-us/powershell/developer/workflow/scheduling-jobs-with-the-windows-powershell-api)
* Content Source: [developer/workflow/scheduling-jobs-with-the-windows-powershell-api.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/developer/workflow/scheduling-jobs-with-the-windows-powershell-api.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by davidsmatlak** [comment]
Thanks for the information about the broken links. At this time those documents are not available. The broken links were removed in PR #3576.
