### ISSUE TITLE
No info about the actual syntax of powershell

### ISSUE THREAD

**Issue by staffanf** [PowerShell/PowerShell-Docs#3542]
We have some info here about that powershell syntax is similar to C# but where is the links to some reference of powershells syntax?
I used to work in PS1.0 and C#/.Net but have been away from windows for a while and I have a hard time finding useful syntax info on do simple powerhell stuff like loops, pipes etc. Stuff you want in cmdlets or simple scripts.
There surely is a better definitions somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4384575-6e45-e6dc-583e-1b77237710bd
* Version Independent ID: eb5a526a-1b4e-9c28-f7ee-f6625191c551
* Content: [Understanding important PowerShell concepts](https://docs.microsoft.com/en-us/powershell/scripting/learn/understanding-important-powershell-concepts?view=powershell-6)
* Content Source: [reference/docs-conceptual/learn/Understanding-Important-PowerShell-Concepts.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/Understanding-Important-PowerShell-Concepts.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The information is there but not organized well. The syntax information you want is in the About_* topics. Start with [About language keywords](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-6). There are links to the other About_* topics.

**Comment by sdwheeler** [comment]
@staffanf We are working on getting this content reorganized. There is a lot of work to do and not enough people to do it. But we will get there.

**Comment by LarryWeiss** [comment]
Is there a way for the PowerShell community to help with the content reorganization ?
