### ISSUE TITLE
-Not not working

### ISSUE THREAD

**Issue by shayki5** [PowerShell/PowerShell-Docs#3554]
> -Not
> Indicates that this cmdlet gets objects if the property does not exist or has a value of null or false.
> For example: Get-Service | where -Not "DependentServices"

I tried it in PowerShell and I got an error:

> Where-Object : Parameter cannot be processed because the parameter name 'Not' is ambiguous. Possible matches include: -NotLi
> ke -NotMatch -NotContains -NotIn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03498b5f-8895-f9f0-1371-1a42c245d0c3
* Version Independent ID: dff1f69c-82c5-68dc-663d-f459f7c79cf3
* Content: [Where-Object (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Where-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Where-Object.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
This is a simple syntax error. 

In the simplified Where-Object, the basic syntax is **Where-object <property> <operator> <value>, 

```powershell
Get-Service | Where-Object name -eq 'myservice'
```

If you want to do boolean, you need the advanced syntax:
```powershell
Get-Service | Where-Object {-not $_.dependentservices}
```

This is a user issue not a docs/product problem.

**Comment by shayki5** [comment]
Thanks.
But in the docs written `Get-Service | where -Not "DependentServices"`

And not `Get-Service | Where-Object {-not $_.dependentservices}`

**Comment by sdwheeler** [comment]
@shayki5 This works for me in v6.1.1. What version of PowerShell are you using?

**Comment by shayki5** [comment]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  820

**Comment by sdwheeler** [comment]
@shayki5 Support for `-Not` in the simplified syntax for `Where-Object` was added in PowerShell v6.1. See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-61?view=powershell-6#goodies.
