### ISSUE TITLE
Enviroment variables are referenced in CMD style when they should be in PowerShell style

### ISSUE THREAD

**Issue by ocalvo** [PowerShell/PowerShell-Docs#3559]
Issue Details
-----------------
When referencing an environment variable, DO NOT use the %VarName% format, use $env:VarName format.
Specially for pages that are PowerShell specific.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@ocalvo Can you provide example articles where this occurs?

**Comment by ocalvo** [comment]
In https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6

Here:
Edit the sshd_config file located at %ProgramData%\ssh.

It should read:
Edit the sshd_config file located at $env:ProgramData\ssh.
