### ISSUE TITLE
-Bottom is not a required parameter

### ISSUE THREAD

**Issue by PedrosBrown** [PowerShell/PowerShell-Docs#3561]
-Bottom should be listed as an optional parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9d9d61-86d7-ecd8-efc1-67c66083e184
* Version Independent ID: 4d53643b-68f8-5bd9-1552-d5cea633f284
* Content: [Sort-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Sort-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Sort-Object.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@PedrosBrown There are two parameter sets: Default and Bottom

`-Bottom` is a required parameter for the "Bottom" parameter set.
