### ISSUE TITLE
Example 1 has an error on Line 2

### ISSUE THREAD

**Issue by gavsto** [PowerShell/PowerShell-Docs#3566]
There should be a space between the NoteProperty and Name and Value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e17fc3-bf10-f09d-8102-da5fe518838b
* Version Independent ID: 6441c722-b93a-1746-e38a-29a6722fc0a3
* Content: [Add-Member (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Add-Member.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Add-Member.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by Nacimota** [comment]
Are you talking about this line?

```powershell
$A | Add-Member -NotePropertyName Status -NotePropertyValue Done
```

Because that looks correct to me. `NotePropertyName` and `NotePropertyValue` are legitimate parameters and appropriate in context. I'm not having any problem running the command in 5.1 or 6.1.

**Comment by sdwheeler** [comment]
@gavsto The example is correct.
