### ISSUE TITLE
DateTime sorting doesn't work

### ISSUE THREAD

**Issue by gigi81** [PowerShell/PowerShell-Docs#360]
On this page:
https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/reportServer.md

This code doesn't work as expected:
$reportsByStartTime = $reports | Sort-Object -Property StartTime -Descending

The property StartTime is of type string, not a datetime, so the sorting will not work as expected.

**Comment by eslesar** [comment]
@gigi81 Thank you for pointing this out. I have updated the line in question to the following:
$reportsByStartTime = $reports | Sort-Object {$_."StartTime" -as [DateTime] } -Descending

Addressed in #400
