### ISSUE TITLE
Debugging DSC resources MSDN topic should also mention how to disable debugging

### ISSUE THREAD

**Issue by NarineM** [PowerShell/PowerShell-Docs#362]
Debugging DSC resources topic on MSDN ( https://msdn.microsoft.com/en-us/powershell/dsc/debugresource ) should also mention how to disable debugging (by running Disable-DSCDebug cmdlet). Once in the debugging mode, any subsequent Start-DSCConfiguration requests will break into the debugger. LCM breaks into debugger after machine reboot as well. So this is important note to capture in this topic.

**Comment by eslesar** [comment]
Addressed in #364
