### ISSUE TITLE
Need documentation for ForEach and Where operators for collections

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#369]
### CodeSample

``` PowerShell
@(1,2,3).Where{$_ -gt 1}
```
### Output

> 2
> 3
### Code Sample

``` PowerShell
@(1,2,3).Foreach{$_ + 1}
```
### output

> 2
> 3
> 4

**Comment by juanpablojofre** [comment]
Travis,
I'll be documenting this subject in the near future.
Thanks for opening the issue.
Best regards,
JP

**Comment by TravisEz13** [comment]
Thanks, tell me if you need any additional information.

**Comment by juanpablojofre** [comment]
Closing as resolved.
