### ISSUE TITLE
partialConfigs.md

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell-Docs#389]
It requires a sample not only of how to use it with ConfigurationID but also with the new v5 method of RegistrationKey / AgentID / ConfigurationNames.

The new sample commited to this page isn't using a good practice for node names.
When using either the old way or the new way of node registration, it should use localhost as the node name.
Any renames to match the ConfiguraionID or ConfiguraitoNames should be done outside the mof creation, and before the checksum of course.

The example forces viewers to use that specific ConfiguraitonID. I know theres a comment explaining, whoich in itself could use more clarity but i dont think it should us a comment to explain methodology in that way.

**Comment by eslesar** [comment]
@ArieHein, thank you for pointing this out. I added ConfigurationNames examples in #406

**Comment by ArieHein** [comment]
there's a small mistype in your corrected code in the "Configuring the LCM for pull mode configurations using configuration names" sample.

        PartialConfiguration Part1 
        {
            Description                     = "OSInstall"
            ConfigurationSource             = @("[ConfigurationRepositoryWeb]CONTOSO-PullSrv") 
        }

Should be

        PartialConfiguration OSInstall 
        {
            Description                     = "OSInstall"
            ConfigurationSource             = @("[ConfigurationRepositoryWeb]CONTOSO-PullSrv") 
        }

**Comment by ArieHein** [comment]
The last two samples or a OS and SP, need a comment under each or under both that running those samples will create a localhost.mof and that prior to creating its checksum, you need to rename the file to match the ConfigurationName or the ConfigurationID.

Either that or change the structure of the page to have the "Naming and Placing" to be after the 2 samples so theres context that's missing atm
