### ISSUE TITLE
Add docs for DSC Conformance server

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell-Docs#40]
I searched the repository for "conformance" and came up empty-handed. The Conformance Endpoint should be documented, as well its database schema, so that developers can create tooling surrounding this feature.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by mgreenegit** [comment]
To jump start this work, you could create a .md file and just bullet the minimum set of things to cover.  Usually faster to expand on ideas that start from a blank state.

In theory, a lot of this can be brought in from the whitepaper with some minor refactoring.

**Comment by eslesar** [comment]
Version 5.0 Report server was added with #162 
With 5.0 RTM available, we are not prioritizing documenting the v4 compliance server.

**Comment by ArieHein** [comment]
Ive wrote an explaination how this works with exmaples that should probably be in the official docs as the one currently in there are lacking.

This is available on powershe..org in the DSC forum (Donshould have pinned it by now but i think hes on holiday :)  )
