### ISSUE TITLE
Broken Link For Windows Server 2012 install

### ISSUE THREAD

**Issue by motowilliams** [PowerShell/PowerShell-Docs#412]
The Server 2012 link at https://github.com/PowerShell/PowerShell-Docs/blob/staging/scripting/setup/Installing-Windows-PowerShell.md#BKMK_InstallingOnWindows8andWindowsServer2012 is broken. It points to https://technet.microsoft.com/en-us/library/4fc0110a-cc0c-42a4-bbb5-3cc89a0fc968 (This topic is no longer available)

**Comment by juanpablojofre** [comment]
Fixed.
