### ISSUE TITLE
Documentation for Authoring DSC Resource in CSharp references a zip file download that does not exist.

### ISSUE THREAD

**Issue by IObsequious** [PowerShell/PowerShell-Docs#417]
Please consider editing your documentation regarding authoring DSC Resources in CSharp. The article is agonizingly difficult to read (mostly because of the strange and inconsistent formatting). Also, when one finally wades through the whole thing, it mentions that the rest of the example is in a zip file that simply does not exist in the article. A search on MSDN yields zero (0) results. Please consider providing an updated link or a complete example so that those of wanting to develop binary resources can have some sort point-of-origin for developing best practices for this technology. 

All that aside, I would like to thank you for what you do. Keep up the good work!

**Comment by eslesar** [comment]
@IObsequious Thank you for pointing this out, and helping us to improve the documentation. With #419 the formatting has been improved, the actual implementations of the ProcessRecord methods have been included, and the reference to the download has been removed.

**Comment by IObsequious** [comment]
Now THAT is what I call a well-formatted example. Thank you!
