### ISSUE TITLE
Example code will result in two different errors

### ISSUE THREAD

**Issue by krillin6** [PowerShell/PowerShell-Docs#423]
To be clear, I'm talking about this page: https://msdn.microsoft.com/en-us/powershell/dsc/scriptresource

Firstly, the return hashtable from GetString can only contain GetString, TestString, SetString, Credential and Result. Where Result is where we should pass back custom data retrieved by Get-DSCConfiguration.

"return @{ 'Version' = $currentVersion }" from example 2 will throw an error upon running a Get-DscConfiguration.  Something to the effect of - "The PowerShell DSC resource  returned results that are not valid from Get-TargetResource."

The return should instead look something like this:

return @{
                    GetScript = $GetScript
                    SetScript = $SetScript
                    TestScript = $TestScript
                    Result = 'The current version is ' + $currentVersion
                }

Source information: http://blog.cosmoskey.com/uncategorized/a-look-at-the-dsc-script-resource/

Also in example 2, I ran into another error with "$state = GetScript"

You cannot run GetScript like this, as it is not a function.  They might have been trying to do $GetScript, or something similar, because apparently there are some variables floating around at runtime for that.  I don't know what is in them, so I won't speculate.

If you run Test-DscConfiguration on the example 2 config, it will error out.

**Comment by eslesar** [comment]
@krillin6 Thank you for bringing this to our attention. This has been fixed with #622
