### ISSUE TITLE
Document not listed in TOC

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#443]
The following document is not listed in the TOC for scripting: [Removing Objects from the Pipeline (Where-Object)](https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/removing-objects-from-the-pipeline--where-object-)

**Comment by HemantMahawar** [comment]
@juanpablojofre  Looks like this issue is fixed. Can you verify, add PR # and close it?

**Comment by juanpablojofre** [comment]
Yes, it's fixed.
