### ISSUE TITLE
Documents not listed in TOC for Integrated Scripting Environment

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#444]
At: TOC for [Integrated Scripting Environment](https://msdn.microsoft.com/en-us/powershell/scripting/core-powershell/ise-guide)

-  How to Use Tab Completion in the Script Pane and Console Pane
-  The PowerShellTab Object
-  The PowerShellTabCollection Object

**Comment by juanpablojofre** [comment]
These links are under 'Console'

**Comment by Dan1el42** [comment]
PR #625 submitted to resolve this issue.
