### ISSUE TITLE
Suggestion: Documentation update regarding Partial Configurations

### ISSUE THREAD

**Issue by krillin6** [PowerShell/PowerShell-Docs#450]
Referring to here:
https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullClientConfigNames.md

I simply wanted to suggest that there be a clear mention of how to use multiple entries for "ConfigurationNames."  As it stands, it is not mentioned at all that if you have multiple entries, you must use the PartialConfiguration LCM config blocks or else your Pulls will fail on a Checksum Error.

https://powershell.org/forums/topic/checksum-failed-w-multiple-configurationnames

All it would take is maybe another paragraph, and a reference to here: https://msdn.microsoft.com/en-us/powershell/dsc/partialconfigs

**Comment by eslesar** [comment]
@krillin6 Thank you for the suggestion! I addressed this with #576 Feel free to re-open this issue if you don't think it is adequately addressed.
