### ISSUE TITLE
Limitations_dsc has incomplete sample solution code for slow registry issue

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell-Docs#453]
This item at the bottom: Some DSC resources like registry resource may start to take a long time to process the request
References $Node configuration data in the sample solution, but no configuration data with example values is included.

**Comment by HemantMahawar** [comment]
@nitinbps  ... can you take a look at it

**Comment by DCtheGeek** [comment]
This is in release notes for WMF 5.0, which is superseded by WMF 5.1.
