### ISSUE TITLE
Dashes should not be escaped in the markdown text

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell-Docs#465]
While sending https://github.com/PowerShell/PowerShell-Docs/pull/464, I noticed that all dashes are escaped with `\-`. It's incorrect. We should run a simple replacement to fix it in all docs.

**Comment by juanpablojofre** [comment]
Thanks @Vors !!
This is an unfortunate side effect from a migration tool used to bring content from TechNet.
I'm working in two fronts here:

- Scrubbing our documents, here
- Reporting back to the team that made the migration tool.

**Comment by alexandair** [comment]
Underscores and slashes are also escaped.

**Comment by juanpablojofre** [comment]
@vors, well, finally fixed.
With [Fix backslashes](https://github.com/PowerShell/PowerShell-Docs/pull/600) PR this issue was fixed to the best of my knowledge.

**Comment by juanpablojofre** [comment]
@vors, would you please close this issue.
Unless, you think there's something else to be fixed; can you point us to what needs to be fixed?

**Comment by vors** [comment]
Fixed via #600

**Comment by vors** [comment]
@juanpablojofre in PowerShell team we are usually closing issues **together with merging PR** to the main branch (in your case would be live or staging depends on the view). Usually this is done by **the person who merges the PR**. To makes it easier, it's recommended to cross-reference issues and PRs in the form `#abc`. Then github UI will insert link like
![image](https://cloud.githubusercontent.com/assets/816680/17954938/eb7e3918-6a97-11e6-8d0e-b84a8b377966.png)
For easier navigation.
