### ISSUE TITLE
an inconsistent dash character for cmdlet and parameter names

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#497]
In certain articles, different type of dash character are used for cmdlet names and parameters. You can see what I'm talking about in the following paragraph (taken from https://msdn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-windows-powershell-50) 

Get-ChildItem also has a new –Depth parameter, which you use with the –Recurse parameter to limit the recursion. For example, Get-ChildItem –Recurse –Depth 2 returns results from the current folder, all of the child folders within the current folder, and all of the folders within the child folders.

**Comment by juanpablojofre** [comment]
@alexandair , 

I fixed all inconsistent dashes I could find (17 documents fixed in #672 ).

Please close this issue as soon as you verify it.

Cheers!!

**Comment by juanpablojofre** [comment]
Closing this issue after 6 months waiting on the opener to close the issue, after the solution was published.

**Comment by alexandair** [comment]
Sorry for not closing it. I've missed your response.
