### ISSUE TITLE
Support for smart card?

### ISSUE THREAD

**Issue by jhack31** [PowerShell/PowerShell-Docs#511]
Wondering if there is a workaround for using JEA with the Get-Credential prompt if you are requiring smart cards.

**Comment by rpsqrd** [comment]
Hey @jhack31, I'd be happy to help here. Just to make sure I'm on the same page, can you elaborate a bit on your use case here? Are you trying to allow someone in a JEA session to access off-box resources with a different identity?

Also, if there is a specific way (specific commands) you are trying to request the credentials that is failing under the JEA constraints, that would be helpful to know.

Ryan

**Comment by jhack31** [comment]
Hey Ryan. I am looking to deploy JEA in an organization that sets "Smart Card required" on each Active Directory account. When you set that setting, it randomizes the AD password for that user and also only allows authentication to Windows resources using a smart card. So far, my organization has not found a work around for the Power Shell "Get-Credential" cmdlet that allows this form of smart card authentication to succeed.In the JEA examples I was reading through it was establishing the session for the non administrative user like this to start (going from memory this morning so forgive anything I may have missed):#get credentials of non admin user$nonadminuser=Get-Credential#establish the session as non admin userEnter-PSSession‎ -computername . -configuration JEAConfig -Credential $nonadminuserThe combination of those commands are what fail for me with the smart card required setting in AD. I don't recall the specific error message and am not at a computer to reproduce it right now, but in general, we haven't found a way to use Get-Credential with smart card required for any use case (not just in regards to JEA) Hope that helps understand the issue. I can send along the error Monday when I'm back in the office if you need it.Thanks for your time in looking into it.Justin                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan PufferSent: Thursday, July 14, 2016 6:44 PMTo: PowerShell/PowerShell-DocsReply To: PowerShell/PowerShell-DocsCc: jhack31; MentionSubject: Re: [PowerShell/PowerShell-Docs] Support for smart card? (#511)Hey @jhack31, I'd be happy to help here. Just to make sure I'm on the same page, can you elaborate a bit on your use case here? Are you trying to allow someone in a JEA session to access off-box resources with a different identity?

Also, if there is a specific way (specific commands) you are trying to request the credentials that is failing under the JEA constraints, that would be helpful to know.

Ryan

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jhack31** [comment]
This issue can be marked as resolved.  The issue was with using the Get-Credential command with smart card using a x509 root hint.  This doesn't work.  However, launching PowerShell using smart card with the x509 root hint does work and then you can Enter-PSSession without needing to pass in a credential.
