### ISSUE TITLE
Missing links for scenarios + features

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#544]
As reported on https://blogs.msdn.microsoft.com/powershell/2016/07/16/announcing-windows-management-framework-wmf-5-1-preview/#comments
There are missing links on:

https://msdn.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features

```
[Determine running edition of PowerShell]()
[Declare a module’s compatibility to specific PowerShell versions]()
[Filter Get-Module results by CompatiblePSEditions]()
[Prevent script execution unless run on a comaptible edition of PowerShell]()
```

**Comment by sdwheeler** [comment]
Fixed
