### ISSUE TITLE
Cleanup the WMF 5.1 Feature-Scenacrios-Cache folder 

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#550]
@jaimeo @eslesar @juanpablojofre 
Not sure what's the use of  [features-scenarios-cache](https://github.com/PowerShell/PowerShell-Docs/tree/staging/wmf/5.1/features-scenarios-cache) folder. Folks have submitted the same fixes for 2 almost identical files (such as #502 and #536). Can one of you remove the unnecessary files from the cache folder or even better - merge its content to correct files (1 level up) and remove the folder? cc @zjalexander @JKeithB

**Comment by HemantMahawar** [comment]
@eslesar @juanpablojofre @KrishnaV-MSFT @JKeithB  ... can one of you take a look at it and clarify?

**Comment by eslesar** [comment]
Addressed with #722
