### ISSUE TITLE
visible metadata in /wmf/5.1/package-management-improvements.md

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#562]
A document metadata is visible on MSDN.

Also, should OneGet be changed to PackageManagement?

**Comment by eslesar** [comment]
First item addressed with #576

**Comment by jianyunt** [comment]
@eslesar, @alexandair   we may not need the fix. OneGet is our brand too. But for consistency, possibly it's good idea to change to PackageManagement.

**Comment by eslesar** [comment]
@jianyunt is there any case in this doc where changing OneGet to PackageManagement would be technically incorrect?
