### ISSUE TITLE
Question: What's the plan for ReadMe topics?

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#593]
What is the longer-term plan for the ReadMe topics in the PowerShell\PowerShell repo? (They're terrific, BTW, e.g. [SSHRemoting/README.md](https://github.com/PowerShell/PowerShell/blob/master/demos/SSHRemoting/README.md))
- Will Get-Help (eventually) be able to get these topics?
- Are they in addition to About topics? Instead of them?
- Will they be published outside of GitHub?
- Is there a format for the topics? For example, LastRevisedDate and AppliesToVersion would be very useful.

**Comment by sdwheeler** [comment]
Docs in the PowerShell\PowerShell repo that are about how PowerShell works belong in the PowerShell\PowerShell-Docs repo. Those docs are being migrated. The PowerShell\PowerShell repo should only contain docs about how to use the repo and build the code.
