### ISSUE TITLE
Update about_Language_Keywords to describe new properties of $PSVersionTable (5.1)

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#595]

**Comment by juanpablojofre** [comment]
@juneb, what exactly do you have in mind?

I have a feeling that you wanted to say 'Update **about_Automatic_Variables** to describe new properties of $PSVersionTable (5.1)', is that right?

I'll start working under that assumption.

**Comment by juneb** [comment]
Yes, sorry about that. Two issue are confounded. About_Automatic_Variables is missing the new properties of $PSVersionTable and about_Language_Keywords is missing several keywords, especially those related to PowerShell classes (class, using, enum, hidden...). We also need to update about_Return to explain how the return keyword differs when it's used in a class.

**Comment by joeyaiello** [comment]
This was fixed by #1217
