### ISSUE TITLE
Can't use UPN Usernames for GroupManagement

### ISSUE THREAD

**Issue by paule96** [PowerShell/PowerShell-Docs#607]
Hi everyone,

for the DSC Modul "Group" I have found a bug.
In my case I have define my DSC as following:

 Group AddServiceAccountToLocalAdminGroup
        {
            GroupName='Administrators'  
            Ensure= 'Present'  
            MembersToInclude= "contoso\serviceuser"
            Credential = $domainCred  
            PsDscRunAsCredential = $domainCred
        }

And $domainCred are PSCredentials that have the credentials from the Domain Administrator. But the Username ist in this Format: [user]@[dnsdomainname]. Example: Admin@contoso.local

With this user Information the config will fail with the error: Exception calling "FindByIdentity" with "3" argument(s): "The user name or password is incorrect.

Can we fix this?

**Comment by joeyaiello** [comment]
If this is still relevant, please re-file it at: https://github.com/powershell/xpsdesiredstateconfiguration
