### ISSUE TITLE
Get-ComputerInfo is missing PowerShell version

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#609]
Get-ComputerInfo was introduced in PowerShell 5.1. Please add this to the help topic. Otherwise, users want to know why they can't find it. Thanks!

**Comment by juanpablojofre** [comment]
@juneb, Get-ComputerInfo is documented at https://technet.microsoft.com/en-us/library/mt736728.aspx.

For both 5.0 and 5.1. I know it's not part of WMF 5.0; but, Win 10 users will get updated most of the times without them knowing.

Is this the documentation you're are asking for?

**Comment by juneb** [comment]
Thanks for the response!

Actually, I'm looking for an indication, preferably near the beginning of the topic, that Get-ComputerInfo was added in 5.0. 

e.g.: Detailed Description. 
The Get-ComputerInfo cmdlet gets a consolidated object of system and operating system properties. This cmdlet was introduced in PowerShell 5.0.

This version info helps users of previous versions, who can't find it and can't run scripts that use it. It also helps authors determine which PowerShell versions their script/modules support.

While you're in there, can you please explain what a "consolidated object" is? I'm not a CS grad and google didn't help with this term. :)

**Comment by juanpablojofre** [comment]
@juneb, I don't think consolidated object is a computer science (CS) term, neither a C# (CS ;) ) term.
I think it is the topic author's idea of explaining that the results you get are a collection of pieces of information gathered from many different sources; let me see what I can do to make that explanation a bit clearer.

As for standardization, I can see that reference documentation for v3.0, v5.0 and v5.1 doesn't include reference to version availability; only, V4.0 has it. So, if I decide to update Get-ComputerInfo with version availability history, I would have to do it for all other cmdlets. And, at the moment, we don't have enough resources to do it.

We might want to wait until the documentation for all cmdlets shipped with the standard version of the produt gets ported to GitHub. Once all that documentation is in GitHub, the community is free to update the topics with what's relevant for the community.

**Comment by juanpablojofre** [comment]
Get-ComputerInfo is now documented in GitHub and shows only under 5.1 version.
Removing the ambiguity between 5.0 and 5.1.
