### ISSUE TITLE
Documentation for ConfigurationMode property dsc/metaConfig.md needs an update.

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/PowerShell-Docs#620]
Specifies how the LCM actually applies the configuration to the target nodes. Possible values are "ApplyOnly","ApplyandMonitior"(default), and "ApplyandAutoCorrect".
ApplyOnly: DSC applies the configuration and does nothing further unless a new configuration is pushed to the target node or when a new configuration is pulled from a server. After successfully applying the initial configuration, DSC does not check for drift from a previously configured state. ApplyOnly mode will come into effect only after DSC has applied the configuration successfully once. 
ApplyAndMonitor: This is the default value. The LCM applies any new configurations. After successfully applying the initial configuration, if the target node drifts from the desired state, DSC reports the discrepancy in logs. ApplyAndMonitorOnly mode will come into effect only after DSC has applied the configuration successfully once. 
ApplyAndAutoCorrect: DSC applies any new configurations. After initial application of a new configuration, if the target node drifts from the desired state, DSC reports the discrepancy in logs, and then re-applies the current configuration.

**Comment by eslesar** [comment]
@nanalakshmanan @HemantMahawar Addressed with #622
