### ISSUE TITLE
Tab Completion with JEA Configuration

### ISSUE THREAD

**Issue by jhack31** [PowerShell/PowerShell-Docs#621]
Is it possible to get tab completion working within a JEA configuration?

**Comment by Dan1el42** [comment]
@jhack31 I think it would be better to submit above on (PowerShell UserVoice)[https://windowsserver.uservoice.com/forums/301869-powershell] instead of the PowerShell documentation repository unless you want to highlight a gap in the documentation.

**Comment by eslesar** [comment]
@jhack31  This question has been forwarded to the product team. Thank you!
