### ISSUE TITLE
MISSING documentation for New-FileCatalog, Test-FileCatalog and Install-Module -SkipPublisherCheck

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell-Docs#652]
I found [this explanation of the new FileCatalog cmdlets](https://msdn.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features#catalog-cmdlets) in the (pre)release notes, but we are post-RTM here (in the sense that you shipped these in Windows 10 AU) and there is no help available in box, and the `-Online` URL is pointed at the old "Future Resources" page, and after some searching, the actual online help is precisely as uninformative as the in-box help.
## Can we get some documentation?

However, despite this **complete and utter lack of documentation**, the PowerShell Gallery team has apparently figured out how to **go back in time** and retroactively implement this functionality in the original 1.0.0.1 release of PowerShellGet and/or PackageManagement which have (supposedly) never been updated since release -- trying to install [Pester](/Pester/Pester) now results in a weird error indicating a new parameter `-SkipPublisherCheck` which may or may not exist:

``` posh
(Get-Command Install-Module).Parameters.ContainsKey("SkipPublisherCheck")
```

Would seem to indicate it _does_ exist, but

``` posh
C:\PS> Get-Help Install-Module -Param SkipPublisherCheck
Get-Help : No parameter matches criteria SkipPublisherCheck.
At line:1 char:1
+ Get-Help Install-Module -Param SkipPublisherCheck
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument:
(System.Manageme...CommandHelpInfo:ProviderCommandHelpInfo) [Get-Help], PSArgumentException
    + FullyQualifiedErrorId : NoParmsFound,Microsoft.PowerShell.Commands.GetHelpCommand 

```

Denies it's existence.

There is currently no documentation whatsoever (not even a synopsis with a "TODO" comment) for these core cmdlets ([New-FileCatalog](https://technet.microsoft.com/en-us/library/mt740490%28v=wps.650%29.aspx) and [Test-FileCatalog](https://technet.microsoft.com/en-us/library/mt740488%28v=wps.650%29.aspx) nor for this new parameter on Install-Module.  Nor is there any documentation within PowerShell of how these concepts relate to modules, nor of the fact that the PowerShellGet module install process checks for them...

**Comment by joeyaiello** [comment]
Good starting point for us to port from: https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features#catalog-cmdlets
