### ISSUE TITLE
Document how to boot-strap the system startup using DSC

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#690]
Couple of already existing content to leverage:

- [Pull Request](https://github.com/PowerShell/PowerShell-Docs/pull/670)
- [Injecting files in the system image](https://blogs.msdn.microsoft.com/powershell/2014/02/28/want-to-automatically-configure-your-machines-using-dsc-at-initial-boot-up/)
- [Using Azure DSC Extension](http://www.powershellmagazine.com/2014/08/07/bootstrapping-dsc-configuration-using-azure-vm-dsc-extension/)

**Comment by kilasuit** [comment]
Also there is the Lability module that @iainbrighton has released that also does the boot strap work just in case you weren't aware of it

**Comment by eslesar** [comment]
Addressed with #729
