### ISSUE TITLE
#Requires -Module runs first, even when it's not first line in a script (not doc'd)

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#694]
In about_Requires, we need to add a line explaining that this directive runs first in the script, even when it doesn't appear on the first line in the script.

`#Requires` is supposed to be the first line in the script (as doc'd). But, if it's not, there's no error. Instead, it runs first without warning. Therefore, code like this, in which order matters, fails unexpectedly, because the correct version of the module is imported, then removed.

```powershell
Get-Module Pester | Remove-Module   #Removes current version
#Requires -Module @{ModuleName = 'Pester'; ModuleVersion = '3.4.3'}
...
```

**Comment by joeyaiello** [comment]
I don't want to step on the incoming syntax fixes from @sdwheeler in PRs, but I've validated that this behavior is consistent down to 3.0. This should just be a one-liner.

**Comment by rjmholt** [comment]
I've opened [an RFC](https://github.com/PowerShell/PowerShell-RFC/pull/122) on updating the behaviour of `#requires`. Please feel free to comment in the PR.
