### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by concentrateddon** [PowerShell/PowerShell-Docs#695]
Please consider adding a license file to the root of the repo, so that it's clear how the content may be used by others.

**Comment by eslesar** [comment]
@joeyaiello Thoughts?

**Comment by vDrewA** [comment]
Agreed, there's mention of the Microsoft CLA at the bottom of CONTRIBUTING.md but it seems that having a LICENSE.md could help without having to move back up to the top of the repo.

**Comment by joeyaiello** [comment]
Fixed
