### ISSUE TITLE
Please remove stale or closed branch

### ISSUE THREAD

**Issue by juanpablojofre** [PowerShell/PowerShell-Docs#702]
@joeyaiello ,

Please take action about branch "styleguide"

Otherwise, within a week it will be deleted.

**Comment by joeyaiello** [comment]
@juanpablojofre Do you feel like there's any value in expanding on the content here? https://github.com/PowerShell/PowerShell-Docs/compare/styleGuide

**Comment by juanpablojofre** [comment]
@joeyaiello,
Yes, I think there is value!!
