### ISSUE TITLE
Clarify installation story

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#712]
Feedback:
1) Customers have trouble finding out how, exactly, to install the latest version of PowerShell.

2) Customers need to know that the latest version of Win10 includes PowerShell 5.0 (and in Server's case, 5.1)

3) Customers are looking for and not finding the way to determine what version of PowerShell they are already running. 

Files that should be looked at:
scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md
scripting/setup/Installing-Windows-PowerShell.md
scripting/whats-new/what-s-new-with-powershell.md

**Comment by zjalexander** [comment]
once we get #886 in here, I think this issue can be closed.

**Comment by joeyaiello** [comment]
Per @zjalexander's comment, closing.
