### ISSUE TITLE
How to use Credential param with ResourceRepositoryShare

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#717]
https://twitter.com/redoz/status/786973119873441794
"In our testing the parameter seemed to have zero effect. This env has no DC so we have to use credentials.
Procmon says access denied when DSC tries to download the resource from the share. Ended up using the web based repo in the end."

Documentation at https://msdn.microsoft.com/en-us/powershell/dsc/metaconfig should address troubleshooting steps and we should consider more verbose examples or samples somewhere as well.

**Comment by eslesar** [comment]
Addressed with #891 and #902
