### ISSUE TITLE
Clarify purpose + use of configdata

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#718]
https://msdn.microsoft.com/en-us/powershell/dsc/configdata needs two things:
1) conceptual overview of how ConfigData helps DSC be more "devops"-y. 

2) need more context to avoid sentences like, "Each hash table entry in AllNodes corresponds to configuration data to a node in the configuration".

**Comment by eslesar** [comment]
Addressed with #763
