### ISSUE TITLE
Get-FileHash -Stream is incompletely documented

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#730]
It's not clear how to use the -InputStream parameter of Get-FileHash. The parameter description is not helpful ("Specifies the input stream."). Also, it takes a System.IO.Stream object, which is an abstract class that you can't instantiate. There are no examples for using this parameter. Thanks!

**Comment by juanpablojofre** [comment]
@juneb ,
This should be fixed after PR #773 is merged into staging, for all versions of the help.

If you like the content, could you please close this issue?
If not, can you explain what you were expecting?

Best regards,

-- JP

**Comment by juanpablojofre** [comment]
Closed per #773

**Comment by SAPIENTechnologies** [comment]
After the changes, the description of the InputStream parameter is still: 
Specifies the input stream.
Can we please have a bit more information? 

https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md

P.S. The complex example is fine, but could use some description.

**Comment by juneb** [comment]
After the changes, the description of the InputStream parameter is still:
Specifies the input stream.
Can we please have a bit more information?

https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md

The complex example (Example 3) is excellent, but could use some description.
