### ISSUE TITLE
Help content for PowerShell module should be generated on GitHub

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#754]
_From @Francisco-Gamino on September 9, 2016 17:39_

## Steps to reproduce

Right now, if a cmdlets is added to PowerShell on GitHub, we do not have a way to followup and write help content for for it. We should fix this by maintaining and publishing the help content for PowerShell built-in cmdlets on GitHub. 
## Environment data

``` powershell
> $PSVersionTable

```

_Copied from original issue: PowerShell/PowerShell#2215_

**Comment by HemantMahawar** [comment]
_From @vors on September 9, 2016 17:44_

cc @juanpablojofre @sankethka @jongeller who are working on it

**Comment by HemantMahawar** [comment]
@Francisco-Gamino This is work in progress under https://github.com/PowerShell/PowerShell-Docs/tree/staging/reference /cc @juanpablojofre

**Comment by juanpablojofre** [comment]
@Francisco-Gamino, @HemantMahawar 
Actually, it is work in progress...
But, started and led by @joeyaiello and his AppVeyor effort in continuos integration (CI).

**Comment by HemantMahawar** [comment]
@Francisco-Gamino If you are satisfied with the [reference](https://github.com/PowerShell/PowerShell-Docs/tree/live/reference) folder, please close this issue.
