### ISSUE TITLE
Add What's New in PowerShell 6 document

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#755]
_From @TimCurwick on September 13, 2016 23:10_

Please add a What's New in PowerShell 6 document. PowerShell on Linux is cool, but what other enhancements have been implemented?

_Copied from original issue: PowerShell/PowerShell#2253_

**Comment by HemantMahawar** [comment]
_From @ealexjordan on September 14, 2016 17:8_

What do you see the benefit of this being over the changelog?

**Comment by HemantMahawar** [comment]
_From @RamblingCookieMonster on September 14, 2016 17:8_

[This repo](https://github.com/PowerShell/PowerShell-Docs/blob/staging/scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md) might be a better fit?

That said, definitely agree, very helpful to have this info if the list has solidified yet.  If not, could include notation for, or simply exclude features that might not make the final cut, if that's something that ever happens.

Cheers!

**Comment by HemantMahawar** [comment]
_From @RamblingCookieMonster on September 14, 2016 17:12_

@ealexjordan - check out the docs repo link vs. changelog - if I'm assuming correctly, Tim's looking for _what's different between PowerShell 5(.1) and PowerShell 6, ideally with some highlighting of big points_, where the changelog might include small bug fixes, and version-to-version changes - both are certainly valuable though : )

Cheers!

**Comment by HemantMahawar** [comment]
_From @MaximoTrinidad on September 14, 2016 17:30_

Definitely a Changelog stays under GitHub.  Then, the change log could be included as part of the What's New In PowerShell 6.0 Documentation. Forgot to mention .. downloadable Documentation.

**Comment by juneb** [comment]
@HemantMahawar , would this cover the difference between PowerShell core and full PowerShell? If not, we need an official doc for that, too.

**Comment by sdwheeler** [comment]
This has been published.
