### ISSUE TITLE
There is no about_Redirection

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#768]
_From @Liturgist on September 17, 2016 23:52_

## Steps to reproduce

Get-Help about_Redirection
## Expected behavior

Information about redirection in PowerShell appears.
## Actual behavior

PS C:\src\powershell> Get-Help about_Redirection
Get-Help : Get-Help could not find about_Redirection in a help file in this session. To download updated help topics type:
"Update-Help". To get help online, search for the help topic in the TechNet library at
https://go.microsoft.com/fwlink/?LinkID=107116.
At line:1 char:1
- Get-Help about_Redirection
- ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
  - FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
## Environment data

``` powershell
Name                           Value
----                           -----
PSEdition                      Core
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.10
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
CLRVersion
```

_Copied from original issue: PowerShell/PowerShell#2298_

**Comment by juanpablojofre** [comment]
@HemantMahawar,

If this is about PowerShell Core, then this issue needs to be moved under GitHub/PowerShell/PowerShell.
As this works fine in all Windows PowerShell versions.

**Comment by HemantMahawar** [comment]
@juanpablojofre  I would consider adding documentation for PowerShell core (6.0.0) in this repo /cc @joeyaiello @SteveL-MSFT

**Comment by juanpablojofre** [comment]
@HemantMahawar ,

I'd suggest we close this issue here and open an 'internal' conversation on how are both (Core and Windows) product documentation sets are going to be developed and maintained.
