### ISSUE TITLE
New topic: Using DSC on Azure

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#787]
We should have a topic page discussing the use of DSC in Azure.
Specifically, it can point to:
https://azure.microsoft.com/en-us/documentation/articles/automation-dsc-overview/
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-extensions-dsc-overview/
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-extensions-dsc-template/
and potentially 
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-extensions-dsc-credentials/

It should be a reference and not a full article, but right now there isn't an easy way to discover Azure DSC from the MSDN DSC docs.

**Comment by eslesar** [comment]
@zjalexander Addressed with #811 I'll leave open until you have a chance to sign off.

**Comment by zjalexander** [comment]
@eslesar awesome, thanks! looks good to me. we can always tweak it later ;)
