### ISSUE TITLE
Back-ticks are replaced by [CODE_Snippit] placeholder in the maml help files

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell-Docs#800]
1. Run `Update-Help`
1. Run `Get-Help Get-Help`

![image](https://cloud.githubusercontent.com/assets/816680/20281452/69bc6072-aa65-11e6-8af4-560bd2e7de2b.png)

The [markdown source](https://github.com/PowerShell/PowerShell-Docs/blob/a32e7912d75bac7fc3bfe6dcb80645167fdb239a/reference/5.1/Microsoft.PowerShell.Core/Get-Help.md) that produced it is:

```
To get help for a Windows PowerShell command, type `Get-Help` followed by the command name, such as: `Get-Help Get-Process`.
To get a list of all help topics on your system, type `Get-Help *`.
```

**Comment by vors** [comment]
There is a similar issue in platyPS: https://github.com/PowerShell/platyPS/issues/222 , but I think leaving back-ticks as-is much more readable then replacing them with `[CODE_Snippit]`

**Comment by joeyaiello** [comment]
Fixed
