### ISSUE TITLE
staging/dsc/pullServerSMB.md needs significantly more detail

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#814]
No details are given on how to publish a module to the share and the folder structure of the share is minimal.  Let's improve this. 

Filed based on customer feedback.

**Comment by dantraMSFT** [comment]
Actually, this is based on a customer support call. The doc  needs to be much more explicit  AND prescriptive.

**Comment by TravisEz13** [comment]
Filed this issue to create configuration to automate creating SMB pull server
https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/273

**Comment by eslesar** [comment]
Addressed with #891
