### ISSUE TITLE
Scrub the WMF 5.1 release notes for the word 'Preview'

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#858]
As we release WMF 5.1, release notes should be updated to remove "Preview" from it, where applicable.

**Comment by HemantMahawar** [comment]
@JKeithB #862 fixed most of the issues. There are some still lingering in [Install-Configure](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md) topic.

**Comment by JKeithB** [comment]
Accurate, the PR shows that as a TODO.

**Comment by HemantMahawar** [comment]
#969 fixes the remaining issues.
