### ISSUE TITLE
PowerShell-Docs/dsc/partialConfigs.md PowerShell mof files in blue screenshot seem incorrect

### ISSUE THREAD

**Issue by rkyttle** [PowerShell/PowerShell-Docs#879]
Looking at https://msdn.microsoft.com/en-us/powershell/dsc/partialConfigs

It mentions, "The RefreshMode for each partial configuration is set to "Push". The names of the PartialConfiguration blocks (in this case, "ServiceAccountConfig" and "SharePointConfig") must match exactly the names of the configurations that are pushed to the target node."

The blue PowerShell screenshot below under the (Publishing and starting push-mode partial configurations) section lists two mof files named SharePointServer.mof.  I am not sure that this is correct given the text listed above, or how it conveys the fact that the names of the PartialConfiguration blocks must match exactly the names of the configurations that are pushed to the target node.

I would expect this screenshot would show ServiceAccountConfig.mof and SharePointConfig.mof unless I am not understanding this properly.

**Comment by HemantMahawar** [comment]
@eslesar It might be worthwhile to convert the screenshot to PowerShell code block for easy fix/updates.

**Comment by eslesar** [comment]
@HemantMahawar That is my plan. Screen shots exist in early DSC docs, and I stopped creating them some time ago. I will correct and convert this.

**Comment by eslesar** [comment]
@rkyttle I am updating the docs to better explain this, and removing the image in favor of code blocks. The requirement for push mode partial config blocks is that the name specified in the block must match the name of the actual config (not the mof file name) given to the configuration.

**Comment by rkyttle** [comment]
Thanks @eslesar !

**Comment by HemantMahawar** [comment]
Fixed by @eslesar with #920
