### ISSUE TITLE
Get-ChildItem missing several parameter descriptions

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#889]
reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md

PARAMETERS

-Attributes

{{Fill Attributes Description}}

-Depth

{{Fill Depth Description}}

-Directory

{{Fill Directory Description}}

-File

{{Fill File Description}}

-Hidden

{{Fill Hidden Description}}

-System

{{Fill System Description}}

**Comment by juanpablojofre** [comment]
@zjalexander,
This is a wider problem than it looks like.
There are 59 topics, that span all versions, with the same problem.
For those 59 topics, there are 45 different place holders of the form: {{ <text> }}.
The total number of placeholders to fix is: 153.
I'll be working on this today and tomorrow (12/15, 12/16).

**Comment by doctordns** [comment]
I have updated get-ChildItem with many of these placeholders replaced with actual content. That update was merged into the Staging branch and is in the process of being merged to the site. Does that help?

**Comment by juneb** [comment]
Depth doesn't seem to work with -Include. We should probably doc that. Or, is it a bug?
(Also, missing an ending comma on the "added in PowerShell 5.0" clause.")

**Comment by sdwheeler** [comment]
The edits have been completed. I create an issue for the behavior of -Depth with -Include/-Exclude.
