### ISSUE TITLE
PowerShell Basics lacks links

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#890]
https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/getting-started/fundamental/Windows-PowerShell-Basics.md

Windows PowerShell was designed to take advantage of a user's historic knowledge of CLIs. In this chapter, we will talk about some basic tools and concepts that you can use to learn Windows PowerShell quickly. They include:

* Using Get-Command

* Using Cmd.exe and UNIX commands

* Using External Commands

* Using Tab-Completion

* Using Get-Help

none of these are linked and it's non-obvious where to go next.

sourced from customer feedback.

**Comment by sdwheeler** [comment]
@zjalexander - What should those items link to? There appear to be articles in the fundamental folder for Get-Command and Get-Help. I can't find articles fr the other bullet items.
