### ISSUE TITLE
Please provide more information how to configure a HA Pull Server with WMF 5

### ISSUE THREAD

**Issue by J0F3** [PowerShell/PowerShell-Docs#908]
Please provide some more information in the Configuration Planning and Installation Guide (https://github.com/PowerShell/Whitepapers/blob/master/PullServerCPIG/PullServerCPIG.md) how a highy available DSC Pull server can be realized with WMF 5.0.
Beginning with WMF 5.0  the clients get registered in the EDB Database an therefore a simple sync of the file to a second Pull Server does not work anymore (as it was possible with WMF 4.0). 
Also placing the EDB file on a file share does not work correctly or at least I was not able to accomplish that two different Pull Server cloud access the same EDB Database (which is located on a File Share)

So please give some advice how a DSC Pull Server with WMF 5.0, where clients are registered in a EDB Database, can be made highly available.

Thx
Jonas

**Comment by eslesar** [comment]
@J0F3 High Because of the change in how nodes register with the pull server, HA is not currently supported in PowerShell 5.0 and later.
