### ISSUE TITLE
DSC For Linux nxUser resource documentation

### ISSUE THREAD

**Issue by jeffpatton1971** [PowerShell/PowerShell-Docs#927]
https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxUserResource.md

You have listed mode as a property but it's undocumented. When I look in the source, I'm not seeing it as a property, at least one defined.

https://github.com/Microsoft/PowerShell-DSC-for-Linux/blob/master/Providers/nxUser/MSFT_nxUserResource.h

I assume the Mode property is perhaps a leftover? If so, can we remove it so we don't get confused please?

Thanks!

**Comment by eslesar** [comment]
Fixed with #971
