### ISSUE TITLE
Missing About_* files

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell-Docs#930]
In PowerShell, You can type Get-Help about_Locations but the resulting document is not here in the MSDN docs. It _used_ to be in the older Technet documentation - but now we get 404.

Another missing document is about_PathSyntax. 

There may be more. ;-)

**Comment by zjalexander** [comment]
There was a previous issue where these items were not published correctly. If you run PowerShell as administrator and run update-help -force , this issue should be fixed.

**Comment by doctordns** [comment]
True - but they do not appear to be on the MSDN  site.

**Comment by zjalexander** [comment]
.....ah. yes :) i misread, my bad!

**Comment by Jaykul** [comment]
It looks like `about_Path_Syntax` exists (extra underscore), but we're missing `about_Logical_Operators`?

**Comment by exchange12rocks** [comment]
No need for Sapien, since the content exists both on [Technet](https://technet.microsoft.com/library/hh847789.aspx) and in the old help repository available through Get-Help cmdlet. I'd add the required files myself, but I do not know what to put into the table which exists at the top of each md-file. @zjalexander can you advise me on how to fill that table?

**Comment by doctordns** [comment]
Can we get someone to add these pages to MSDN?

**Comment by zjalexander** [comment]
@juanpablojofre is currently figuring out the total set of stuff that is missing.

**Comment by juanpablojofre** [comment]
So far, my research is telling me we are missing:

- about_Classes
- about_Checkpoint-Workflow
- about_DesiredStateConfiguration
- about_Locations
- about_Logical_Operators
- about_PSConsoleHostReadLine

I'll do another pass and see what else is missing.

I just hope, I don't need to translate back from German to English... what was originally written in English :D !!

**Comment by exchange12rocks** [comment]
@juanpablojofre And you even have those files in Markdown already ;) https://github.com/juanpablojofre/About

**Comment by juanpablojofre** [comment]
@exchange12rocks ,
Yes!!
Going through the list... as some names were expanded.
Here is what I found...
After removing from the list the obvious duplicates, like about_Functions_Adv_M.

about_activitycommonparameters.md      
about_checkpoint-workflow.md           
about_classes.md                       
about_desiredstateconfiguration.md     
about_dsclogresource.md                
about_foreach-parallel.md              
about_hidden.md                        
about_inlinescript.md                  
about_locations.md                     
about_logical_operators.md             
about_parallel.md                      
about_psconsolehostreadline.md         
about_psreadline.md                    
about_schedjobs_ts.md                  
about_scheduled_jobs.md                
about_scheduled_jobs_advanced.md       
about_scheduled_jobs_basics.md         
about_scheduled_jobs_troubleshooting.md
about_sequence.md                      
about_sesconfig_files.md               
about_signing_deleted.md               
about_simplified_syntax.md             
about_suspend-workflow.md              
about_transactions_deleted.md          
about_type_accelerators.md             
about_wfactivitycomp.md                
about_wfsequence.md                    
about_windows_powershell_5.0.md        
about_workflowcommonparameters.md      
about_workflows.md                     
about_ws-management_cmdlets.md

**Comment by juanpablojofre** [comment]
I'll add them to 5.0, run broken links checking and recreate TOC.
Then I'll do a similar pass for 5.1.
For 6, it'll be a different game... as I need to double check if the about topic applies to PS6 as it is today.

**Comment by exchange12rocks** [comment]
Part of PSWorkflow:
about_activitycommonparameters.md
about_checkpoint-workflow.md
about_foreach-parallel.md
about_inlinescript.md
about_parallel.md
about_sequence.md
about_suspend-workflow.md
about_workflowcommonparameters.md
about_workflows.md

Part of Microsoft.WsMan.Management:
about_ws-management_cmdlets.md

Part of PSScheduledJob:
about_scheduled_jobs.md
about_scheduled_jobs_advanced.md
about_scheduled_jobs_basics.md
about_scheduled_jobs_troubleshooting.md

Which leaves us with:
about_classes.md
about_desiredstateconfiguration.md
about_dsclogresource.md
about_hidden.md
about_locations.md
about_logical_operators.md
about_psconsolehostreadline.md
about_psreadline.md
about_schedjobs_ts.md
about_sesconfig_files.md
about_signing_deleted.md
about_simplified_syntax.md
about_transactions_deleted.md
about_type_accelerators.md
about_wfactivitycomp.md
about_wfsequence.md
about_windows_powershell_5.0.md

**Comment by juanpablojofre** [comment]
Thanks

**Comment by juanpablojofre** [comment]
@doctordns, @exchange12rocks, @Jaykul, @zjalexander 

PR #1139 sent for review.
Once approved and merged, we should close this issue.

**Comment by doctordns** [comment]
Thanks Juan - great to have MSDN now up to date!

**Comment by juanpablojofre** [comment]
@doctordns, you're welcome!!

**Comment by juanpablojofre** [comment]
Closing issue as resolved
