### ISSUE TITLE
DSC: Enacting configurations: Clarification of last large paragraph.

### ISSUE THREAD

**Issue by robinmalik** [PowerShell/PowerShell-Docs#947]
The paragraph starting 'In pull mode, pull clients are configured to get their desired state configurations from a remote pull server.' reads unclearly to me (admittedly I am new to DSC).

It states that pull clients periodically check the configuration 'of the node' (i.e. itself). It then says that the first time this happens, LCM validates the configuration and if it's not configured as desired, LCM will request the pull server to 'get a given configuration'. Why would it 'get a given configuration' if it's just already validated itself against said configuration? In other words, if the client is aware of the configuration it needs to validate itself against, why does it then need to pull that config from the remote pull server? 

Could this be clarified somehow?

**Comment by eslesar** [comment]
@robinmalik, thank you for pointing this out. This is unclear, and I will work to clarify it in the docs. You are correct, this wording is misleading. The client checks for updated configurations on the pull server at intervals specified by the RefreshFrequencyMins property of its Local Configuration Manager (LCM). It applies pulled configurations at intervals specified by the ConfigurationModeFrequencyMins property.

**Comment by eslesar** [comment]
Addressed with #951
