### ISSUE TITLE
Major glitch in formatting for code samples in about_ files on TechNet

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell-Docs#950]
The code examples are a total mess, for example, the ones in [about_Comparison_Operators](https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Comparison_Operators) 

![image](https://cloud.githubusercontent.com/assets/192942/21898374/b0a0fa4c-d8ba-11e6-838f-2fa2ddd285c4.png)

**Comment by doctordns** [comment]
Is this a glitch in how MSDN formats the pages? Or is this an issue with the markdown on the page itself?

**Comment by Jaykul** [comment]
The markdown is wrong. All of those numbers have a "#" in front of them turning them into headers.

**Comment by doctordns** [comment]
I just took a look - yes. The markdown itself is a bit of a mess. I am happy to take a stab at getting this into better shape!

**Comment by doctordns** [comment]
I have gone through this document, adding markdown for the examples, removing the # tags around the place and trying to make this better. I've issues a pull request - hopefully this revolves that problem!

**Comment by Jaykul** [comment]
I think it's **most** of the about_ files though. I mean, I just spot-checked: 
* about_trap and about_Remote_Jobs have good code examples, actually in code blocks, and with syntax highlighting (even when it shouldn't be highlighted).
* about_arithmetic_operators, about_assignment_operators, about_commonparameters have the really bad code examples (like about_Comparison_Operators)
* about_Remote, about_Remote_Variables, and about_regular_expressions have no markup on their code examples at all (which I think is basically the same as the ones with the really bad code examples, except there just happened to not be # in the example code...)

**Comment by doctordns** [comment]
Thanks Jaykul. There is much work to be done. Once the current pull request is actioned, I am happy to work through those about_* files to correct them. Unless of course someone beats me to it.

**Comment by zjalexander** [comment]
Yeah, there's a general scrub of about_ topics that's called for at this point.
https://msdn.microsoft.com/en-us/powershell/reference/3.0/psworkflow/about/about_workflows
https://msdn.microsoft.com/en-us/powershell/reference/3.0/psworkflow/about/about_activitycommonparameters
https://msdn.microsoft.com/en-us/powershell/reference/3.0/microsoft.powershell.core/about/about_aliases

some are missing proper formatting. all are missing proper links in the "see also" section. I got to talk to @juanpablojofre and see if he had some tooling developed since it's not consistent across all about files and all versions, and I remember the process of getting stuff into markdown was quite .... iterative.

**Comment by Xalorous** [comment]
I see styling with markdown is accepted here in the comments, what about the "about_" pages?

The 'about_regular_expressions' page is an unformatted copy/pasta of output from `Get-Help about_regular_expressions`, but the help output contains space delimited tables that translate very poorly.  The website needs it converted to a table somehow, but I don't know the formatting used to go from what's on the github to what's seen on technet.

**Comment by zjalexander** [comment]
yup, markdown in the about_ topics is definitely allowed. we've fixed a few (about_pipelines at least, from #1262 ). I think @juanpablojofre had a plan for the rest according to a meeting today?
