### ISSUE TITLE
Fix formatting issues on about_Foreach for 3.0,4.0 and 5.0 version of document

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell-Docs#959]
Current rendering of [3.0](https://msdn.microsoft.com/en-us/powershell/reference/3.0/microsoft.powershell.core/about/about_foreach), [4.0](https://msdn.microsoft.com/en-us/powershell/reference/4.0/microsoft.powershell.core/about/about_foreach) and [5.0](https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.core/about/about_foreach) version of the document is difficult to read and understand.

Thanks to @briantist via #946, 5.1 version of the document is fixed. /cc: @juanpablojofre

**Comment by kiazhi** [comment]
Submitted the following fixes.
Fixing 3.0 About_ForEach.md reported Issue #959 #1043
Fixing 4.0 About_ForEach.md reported Issue #959 #1042
Fixing 5.0 About_ForEach.md reported Issue #959 #1044

**Comment by HemantMahawar** [comment]
Thank you @kiazhi for resolving this one. Much appreciated.
