### ISSUE TITLE
[5.1 Release notes] Please elaborate on PSReadLine's vi Mode in console-improvements.md

### ISSUE THREAD

**Issue by megamorf** [PowerShell/PowerShell-Docs#974]
In https://github.com/PowerShell/PowerShell-Docs/blob/65c38d03965fb31ab5df44afdab05d0e15bf3865/wmf/5.1/console-improvements.md you have the following section...

```markdown
### Vi mode support in PSReadline

[PSReadline](https://github.com/lzybkr/PSReadLine) adds support for vi mode. To use vi mode, run `Set-PSReadline -EditMode vi`.
```

... but fail to mention what this mode actually does. The PSReadline module docs don't cover it either. Could you elaborate on what vi mode actually does inside the console. I don't suppose I can use it to finally edit files directly in the cli on Windows without requiring a 3rd party editor.

Thanks in advance.

**Comment by lzybkr** [comment]
vi mode comes from GNU readline - typically used in bash.  Search for `bash vi mode` and you'll find plenty of documentation.

There are no plans to turn PSReadline into a real text file editor.

**Comment by lzybkr** [comment]
That's fine with me.
