### ISSUE TITLE
authoringResourceComposite.md renders incorrectly

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#979]
https://msdn.microsoft.com/en-us/powershell/dsc/authoringresourcecomposite

![image](https://cloud.githubusercontent.com/assets/6953993/22169832/29143a76-df2c-11e6-97b6-0eeb437fe441.png)

I don't know what's wrong or how to fix it.

**Comment by HemantMahawar** [comment]
Fixed by #983

**Comment by zjalexander** [comment]
@HemantMahawar

**Comment by zjalexander** [comment]
Still broken :\

**Comment by HemantMahawar** [comment]
@eslesar Any clue what's going on /cc @zjalexander

**Comment by eslesar** [comment]
Fixed with #1003
