### ISSUE TITLE
Smartcard support for Get-Credential and PSSessions

### ISSUE THREAD

**Issue by aarju** [PowerShell/PowerShell-Docs#990]
I would like to be able to use a smartcard + pin to authenticate a new PSSession on a remote host. The smartcard can be selected via the Get-Credential popup window, but the credential object created will not successfully authenticate to the domain or other hosts.

The enterprise network I work on has separation of account privileges along with enforcing 2FA for all accounts. This means that I have multiple smartcard readers on my system, and when I need to run as administrator I have to use the smartcard + pin to start a new powershell prompt with my admin account. When I try New-PSSession with a remote computer I receive a winRM client error because default authentication fails without HTTPS transport. My current work around for executing remote PSSessions is an exception to policy allowing login to an admin account without 2FA, not an ideal situation.

**Comment by joeyaiello** [comment]
@aarju: thanks for the request. Totally a useful feature that we should absolutely consider. 

I've gone ahead and [filed an issue](https://github.com/PowerShell/PowerShell/issues/3048) where we track feature requests over on the repository for PowerShell itself. (This repo is actually for documentation issues, so I'm going to go ahead and close it here.) 

Thanks!
