### ISSUE TITLE
New-localuser cmdlet fails length check on Name parameter

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#997]
_From @mirichmo on January 25, 2017 17:2_

Update: This is a documentation bug. Example 3 is not correct and should be removed.

The cmdlet should accept longer names such as MSAs as specified in the [MSDN help](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.localaccounts/new-localuser).

```powershell
PS F:\> nlu -name abcdefghijklmnopqrstuvwxyz
New-LocalUser : Cannot validate argument on parameter 'Name'. The character length of the 26 argument is too long. Shorten the character length of the argument so it is fewer than or equal to "20" characters, and then try the command again.
At line:1 char:11
+ nlu -name abcdefghijklmnopqrstuvwxyz
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-LocalUser], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.NewLocalUserCommand
```
Version:
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

TFS:10558531

_Copied from original issue: PowerShell/PowerShell#3045_

**Comment by joeyaiello** [comment]
_From @iSazonov on January 25, 2017 17:15_

@mirichmo Can you post the MSDN help link?

**Comment by joeyaiello** [comment]
_From @mirichmo on January 25, 2017 17:34_

Updated

**Comment by joeyaiello** [comment]
_From @iSazonov on January 25, 2017 17:41_

The help say:
> A user name can contain up to 20 uppercase characters or lowercase characters.

I believe that this happens from [here](https://msdn.microsoft.com/en-us/library/ms679635(v=vs.85).aspx)
What limit do you expect?

**Comment by joeyaiello** [comment]
_From @jeffbi on January 25, 2017 19:42_

The page the original decision came from was [here](https://technet.microsoft.com/en-us/library/cc770642.aspx).

**Comment by joeyaiello** [comment]
_From @mirichmo on January 25, 2017 22:27_

The original SAM API (pre-Win 7?) had that restriction, so it is documented in those locations, in net.exe, and lusrmgr.msc. However, I suspect that the "new" SAM API (aka what shipped in Win 10) allows longer names (up to 255+?), so we may be able to relax the restriction or get rid of it.

**Comment by joeyaiello** [comment]
_From @iSazonov on January 26, 2017 4:7_

Seems the documentation is still not updated. I could find nothing about this change. Is there a public description?

**Comment by joeyaiello** [comment]
_From @jeffbi on January 26, 2017 23:5_

I just stepped through the new-localuser cmdlet on my Windows 10 box with the name-length validation removed. The SAM API call fails with INVALID_USER on user names greater than 20 characters.

**Comment by joeyaiello** [comment]
_From @mirichmo on January 27, 2017 0:54_

Confirmed. I looked through the SAM source code and double-checked account name validation. The limit is 20 characters for users and 256 for groups. 

I am going to re-classify this as a documentation bug.

**Comment by joeyaiello** [comment]
@mirichmo make sure to file doc bugs for already shipped code in [http://github.com/PowerShell/PowerShell-Docs](PowerShell-Docs). That way @jpjofre can track it easily

**Comment by zjalexander** [comment]
What versions of PowerShell does this cmdlet have the issue in?

**Comment by sdwheeler** [comment]
The bad example has been removed the docs.
